### ISSUE TITLE
Error commenting on poject

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#10]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2473/#comment-7616

### Reproduction Steps ###
1. Login to site using pshah_customer/topcoder123
2. Navigate to project https://connect.topcoder-dev.com/projects/2473
3. Comment
4. Delete comment
5. Comment again

### Expected Result ###

*Enter the expected result here.*

Comnets is posted on proect

### Actual  Result ###
Error creating post

*Enter the expected result here.*

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36344109-58c170ce-140d-11e8-86c5-43a5a4d173ba.png)

### Issue Information ###

Frequency: Mostly

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
Can't reproduce the bug using the provided steps and details

**Comment by gargsaurabh86** [comment]
@sdgun Just for future challenges.
As few of the issues that reproduced were intermittent like this one.

Will they be accepted if I make a video as evidence?

**Comment by sdgun** [comment]
Not always but I will give you some tips;

- Provide solid descriptive steps + Test data
- If the ticket is about error messages, loading issues, system freeze > provide JS log
- Always provide a video if the ticket is about functional bug
- Some bugs only happen on certain devices; so fill the 'Issue Information' section with correct data like Browser version, OS version, If it is a laptop or a mobile device
- Video is an added advantage :)

Good Luck :)
