### ISSUE TITLE
Window-Member – We don’t have option to go back to start page from Log in page.  

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#100]
Summary:
Window-Member – We don’t have option to go back to start page from Log in page.  
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
3.Home Page appears
4.Click Log in
3. Try to navigate to home page by Clicking “Connect Logo”
### Expected Result ###
Window-Member – We should have option to go back to start page from Log in page.  

### Actual  Result ###
Window-Member – We don’t have option to go back to start page from Log in page.  
### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36346592-e10a0a32-1466-11e8-9f8f-fa40a9924c8c.png)
![image](https://user-images.githubusercontent.com/31862600/36346593-ebdb8710-1466-11e8-8d5f-f06eeb6c1c34.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
As per the design
