### ISSUE TITLE
Window-Member – Load more button should be disabled if we don’t have more project to display

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#101]
Summary:
Window-Member – Load more button should be disabled if we don’t have more project to display
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2.Log in with pshah_customer/topcoder123
3.Create 19 project 
4.Click Load more button
### Expected Result ###
Window-Member – Load more button should be disabled if we don’t have more project to display

### Actual  Result ###
Window-Member – Load more button is not disabled if we don’t have more project to display
App is displaying Welcome to Connect! I’m Coder the Robot. I see you have no projects yet. To get you started, press the “New Project” icon and let’s build something. Message with no option to create new project or Asking user to click “+” to create project
### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36346673-f166aa32-1468-11e8-973a-fdb86c5d2051.png)
![image](https://user-images.githubusercontent.com/31862600/36346677-f80f7cf6-1468-11e8-995d-cbcde6407e9d.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
After clicking on the button error is handled properly, so not a bug.

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1788
