### ISSUE TITLE
No notification triggered for active status

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#102]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com/
2. Login as pshah_customer
3. submit a project for review
4. Login as manager and change the status of the project to Active
5. goto customer page and observe the notification

### Expected Result ###
Notification should be triggered for active status also.

### Actual  Result ###

Notification not triggered for active status.

### Screenshots ###

https://youtu.be/37JpyoumCLI

![image](https://user-images.githubusercontent.com/31851673/36346675-d9e9b92c-143a-11e8-9a7f-8d9b5393f874.png)

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 64-bit

Browser: Chrome 64.0.3

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1740
