### ISSUE TITLE
Differnt option for list project view

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#103]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects?memberOnly=true&sort=updatedAt%20desc&status=paused

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. On the rightmost select Thumbnail view
3. Add new project option is visible
4. Now select list view

### Expected Result ###

Add new project option is visible
or Thumbnail view and List view are consistent

### Actual  Result ###

Add new project option is not visible

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36346681-0591a2f6-143b-11e8-96b0-54b9aaa389b5.png)

![image](https://user-images.githubusercontent.com/29735376/36346686-1abc2e08-143b-11e8-87aa-be164718ecea.png)

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: Chrome

**Comment by sdgun** [comment]
As per the design
