### ISSUE TITLE
Window-Member – Log out message is coming in top right coroner of the page.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#105]
Summary:
Window-Member – Log out message is coming in top right coroner of the page.
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2.Log in with pshah_customer/topcoder123
3.Click Log out
### Expected Result ###
Window-Member – Log out message should comine in center of the page.

### Actual  Result ###
Window-Member – Log out message is coming in top right coroner of the page.
### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36346769-0d502762-146b-11e8-8d5a-fcf26dee44d6.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
Not a Bug
