### ISSUE TITLE
Notification not triggered after adding a new member

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#107]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com/
2. Login as pshah_manager
3. Select any project where pshah_customer is not a member 
4. Now add pshah_customer as member
5. goto the customer notifications and observe

### Expected Result ###
Notification should be triggered if the user added to a project

### Actual  Result ###

There is not notification triggered to the user after adding him to the new project.

### Screenshots ###
https://youtu.be/oaMPN1PckeE

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 64-bit

Browser: Chrome 64.0.3

**Comment by sdgun** [comment]
Working as expected
