### ISSUE TITLE
Window-Member – Project is not created successfully, If user tries to create project without log in.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#108]
Summary:
Window-Member – Project is not created successfully, If user tries to create project without log in.
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Click “Start A Project”
3.Create a project
4. Application will ask for the Registration
5.Fill the registration form and Enter the verification code
6.Application will direct to created project page
### Expected Result ###
Window-Member – Project is not created successfully, If user tries to create project without log in.

### Actual  Result ###
Window-Member – Project is not created successfully, If user tries to create project without log in.
Getting below error message
### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36346819-c9cd4c20-146c-11e8-8e84-b10b3371bc12.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by vic-georgiev** [comment]
Let's investigate this one

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1805
