### ISSUE TITLE
Connect logo not clickable

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#109]
### Reported URL ###
*URL where the issue occured, if applicable*
https://accounts.topcoder-dev.com/connect?retUrl=https:%2F%2Fconnect.topcoder-dev.com%2F
https://connect.topcoder-dev.com/new-project/

### Reproduction Steps ###
1. https://connect.topcoder-dev.com/
2. Click on Login button - Observe Connect logo
3. Click Register for Free - Observe Connect logo
4. Navigate to https://connect.topcoder-dev.com/
5. Click Start a new project - Observe Connect logo

### Expected Result ###

Connect logo is clickable

### Actual  Result ###

Connect logo is not clickable

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36346839-69da1988-143f-11e8-8283-c08a153f257e.png)
![image](https://user-images.githubusercontent.com/29735376/36346841-781e282c-143f-11e8-93ba-2c436aee3215.png)
![image](https://user-images.githubusercontent.com/29735376/36346844-99944c52-143f-11e8-88a0-6908a6e157df.png)

### Issue Information ###

Frequency: Always
Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
As per the design
