### ISSUE TITLE
Status icon and Warning popup window are not aligned while changing the status

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#110]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com/
2. Login as pshah_manager
3. select a project from second in the list and try to change the status to Complete
4. Now observe the alignment of the warning message popup window and status icon

### Expected Result ###
All the windows should be aligned properly

### Actual  Result ###

Status icon and Warning popup window are not aligned while changing the status.
The defect will not found for the first project in the list.

### Screenshots ###

![image](https://user-images.githubusercontent.com/31851673/36346863-47f8c462-1440-11e8-8418-91b1a5ff2b8b.png)

https://youtu.be/DfWeOeFpuOs

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 64-bit

Browser: Chrome 64.0.3

**Comment by sdgun** [comment]
#79
