### ISSUE TITLE
Window-Member – Getting error message as “Error Creating posting” , While posting comments for created project.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#112]
Summary:
Window-Member – Getting error message as “Error Creating posting” , While posting comments for created project.
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a project
4.Post a comment
5.Repat Step 4 3 to 4 times
### Expected Result ###
Window-Member – Should not get error message as “Error Creating posting” , While posting comments for created project.

### Actual  Result ###
Window-Member – Getting error message as “Error Creating posting” , While posting comments for created project.
### Screenshots ###

https://youtu.be/eS64Ry38cqo

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
#11
