### ISSUE TITLE
Window-Member – Getting error message as “Whoops! we ran into a problem. Please try again later” , While adding new members in the project

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#114]
Summary:
Window-Member – Getting error message as “Whoops! we ran into a problem. Please try again later” , While adding new members in the project.
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a project
4.Add members
### Expected Result ###
Window-Member – Should not get error message as “Whoops! we ran into a problem. Please try again later” , While adding new members in the project.

### Actual  Result ###
Window-Member – Getting error message as “Whoops! we ran into a problem. Please try again later” , While adding new members in the project.
### Screenshots ###

https://youtu.be/JbgXjs-w9pg

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
#8
