### ISSUE TITLE
Year not shown if not current year

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#115]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=createdAt

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2.  Select All Projects
3. Sort with oldest first

 ## Expected Result ###
As per speces: Show year if it is not current year.

### Actual  Result ###

Year is not displayed

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36346990-3c74cfa2-1443-11e8-85f8-a552481fd49b.png)

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1764
