### ISSUE TITLE
Window-Member – Getting error message as “Whoops! we ran into a problem. Please try again later” , While removing the new members in the project.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#116]
Summary:
Window-Member – Getting error message as “Whoops! we ran into a problem. Please try again later” , While removing the new members in the project.
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a project
4.Add 2 members
5.Now remove the member
### Expected Result ###
Window-Member – Should not get  error message as “Whoops! we ran into a problem. Please try again later” , While removing the new members in the project
### Actual  Result ###
Window-Member – Getting error message as “Whoops! we ran into a problem. Please try again later” , While removing the new members in the project

 ### Screenshots ###

https://youtu.be/MHTZeadcT2w

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
#15

**Comment by youdare** [comment]
@sdgun 

Defect 15 and 116 are ddifferent

#15 is Leave project
#116 is Removing the members after adding 

So both are different could you please check again

**Comment by sdgun** [comment]
Both options use the same process here.
