### ISSUE TITLE
Options in Project list view not available on thumbnail view

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#118]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. Change Project view from list view to thumbnail and see differences

### Expected Result ###

In Thumbnail view, All the Options like ID, Project, Last Updated, Customer, Managers and Project status are visible.

### Actual  Result ###
Very less options are visible and user do not have the option to Change Project status as well!

*Enter the expected result here.*

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36347048-21c7480e-1445-11e8-9149-b66e602e4ed8.png)
![image](https://user-images.githubusercontent.com/29735376/36347049-37eae4ec-1445-11e8-8569-93f951cf7a69.png)

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
As per the design
