### ISSUE TITLE
Window-Member – App is showing added members only if we re-load the

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#119]
Summary:
Window-Member – App is showing added members only if we re-load the
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a project
4.Add members
5.Now remove the member
### Expected Result ###
Window-Member – App should show added members without re-loading the
### Actual  Result ###
Window-Member – App is showing added members only if we re-load the

 ### Screenshots ###

https://youtu.be/DljCU983EIA

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
Incomplete bug report
