### ISSUE TITLE
Error 500 when switching between My Projects and all projects

### ISSUE THREAD

**Issue by macs054** [topcoderinc/connect-test-cycle-1#12]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc&status=active

### Reproduction Steps ###
Go to https://connect.topcoder-dev.com/
Login as pat_monahan/topcoder123!
Toggle 'My Projects'
Switch to Tile View
Toggle 'My Projects' again

### Expected Result ###

Should show all projects properly

### Actual  Result ###

Page is returning a 500 error code

### Screenshots ###

![image](https://user-images.githubusercontent.com/1199534/36344104-55d24634-1450-11e8-9b78-c9c2e41972e6.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2

**Comment by sdgun** [comment]
Can't reproduce the bug using the provided steps and details
