### ISSUE TITLE
All Project Card View ordering issue

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#120]
### Reported URL ###
*URL where the issue occurred, if applicable*
https://connect.topcoder-dev.com/projects

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. In list view 
3. Select order by oldest first
4. Now Change view to card view
 

### Expected Result ###

As per specs: Ordering should be by latest activity

### Actual  Result ###

Ordering was by oldest first!

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36347074-f846835e-1445-11e8-9140-23965eedb621.png)

![image](https://user-images.githubusercontent.com/29735376/36347078-06008b3e-1446-11e8-8314-3b141e76db33.png)

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
Previously applied filter applied for grid view as well
