### ISSUE TITLE
Manager: Status filter menu bar is disappeared after applying the project type filter

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#121]
### Reported URL ###
https://connect.topcoder-dev.com/projects

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com/
2. Login as pshah_manager
3. click on filters button
4. apply a filter ex: QA and observe status filter menu bar is project with all project, active, draft.......etc
5. Now open any filtered project
6. Now click on View all projects in the dashboard page for the above opened project
7. Now look for the status filter menu bar

### Expected Result ###
Status filter menu bar should be shown always

### Actual  Result ###
Status filter menu bar is missing once we open the filtered project and then came back.

### Screenshots ###

![image](https://user-images.githubusercontent.com/31851673/36347062-964529d0-1445-11e8-9682-15ad52bf24de.png)

https://youtu.be/yPz0Fhu0KiE

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 64-bit

Browser: Chrome 64.0.3

**Comment by sdgun** [comment]
#106
