### ISSUE TITLE
Post feed->Create new post->User do not have option to cancel the post

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#122]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/1299

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. Select any project and navigate to its details page like https://connect.topcoder-dev.com/projects/1299
3. Start entering "Share the latest update with the team"

### Expected Result ###

As per specs: Post feed->Create new post-> Should be able to cancel post

### Actual  Result ###

Not able to cancel post. As there is no cancel button.

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36347110-f974f016-1446-11e8-9f7b-4691ed03a192.png)

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
Clicking on a empty space will hide the form

**Comment by gargsaurabh86** [comment]
@sdgun if you follow steps 3 i.e. enter something in form then you won't be able to hide form when clicking on empty space.

Thanks.

**Comment by gargsaurabh86** [comment]
@sdgun waiting for reply. Thank you.

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1766
