### ISSUE TITLE
Text warp issue on post card

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#123]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/1299

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. Select any project and navigate to its details page like https://connect.topcoder-dev.com/projects/1299
3 Start entering "Share the latest update with the team"
4. Enter details as fihferighisgjbsukrguiesrgsyfihferighisgjbsukrguiesrgsyfihferighisgjbsukrguiesrgsyfihferighisgjbsukrguiesrgsyfihferighisgjbsukrguiesrgsyfihferighisgjbsukrguiesrgsyfihferighisgjbsukrguiesrgsyfihferighisgjbsukrguiesrgsyfihferighisgjbsukrguiesrgsyfihferighisgjbsukrguiesrgsyfihferighisgjbsukrguiesrgsyfihferighisgjbsukrguiesrgsyfihferighisgjbsukrguiesrgsy
 5.Click Post

### Expected Result ###

As per spec: Post card should be responsive and text should be wrapped.

### Actual  Result ###

Text did not wrapped.

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36347158-16cadb84-1448-11e8-8e71-6da0046d249a.png)
![image](https://user-images.githubusercontent.com/29735376/36347163-2b5c1dc4-1448-11e8-83b7-4cd67ccbf386.png)

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by youdare** [comment]
@gargsaurabh86 Dont raise defect with out any context

![image](https://user-images.githubusercontent.com/31862600/36347159-31bc999a-1476-11e8-9959-ad0cfc28054f.png)

**Comment by gargsaurabh86** [comment]
@youdare  not sure what you mean by that all my defect have context.
Or this will happen when I'm creating the bug

**Comment by youdare** [comment]
@gargsaurabh86 Raise defect and submit don't edit , Read contest details.

**Comment by gargsaurabh86** [comment]
okay thank you

**Comment by sdgun** [comment]
Long text without spaces > This is not a valid input
