### ISSUE TITLE
Window-Member – Project ->Specification -File ->Drop box->Click Connect To Dropbox , Throws error message as Error (400) 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#124]
Summary:
Window-Member – Project ->Specification -File ->Drop box->Click Connect To Dropbox , Throws error message as Error (400) 
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a App project
4. Go Specification Click->  File
5.Drop box->Click Connect To Dropbox
### Expected Result ###
Window-Member – Project ->Specification -File ->Drop box->Click Connect To Dropbox , Should allow to connect and upload file

### Actual  Result ###
Window-Member – Project ->Specification -File ->Drop box->Click Connect To Dropbox , Throws error message as Error (400) 

 ### Screenshots ###
See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
Not a bug in the connect app
