### ISSUE TITLE
 user should not be able to click "Add File" button if the user does not have edit permission to the project 

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#126]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/2498/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. create a new project
3. then login using another user who has no manage permission to this project, go to https://connect.topcoder-dev.com/projects/2498/specification
4. scroll down, click Add File button, observe

### Expected Result ###

*should disable the Add File button.*

### Actual Result ###

*See screenshot, it's clickable.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="1367" alt="dis" src="https://user-images.githubusercontent.com/4590317/36347224-db636350-148c-11e8-9e99-bd6ba0f3adfb.png">

**Comment by winterflame** [comment]
Currently user is able to add file to the project which he/she only has view permission.

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1802
