### ISSUE TITLE
Window-Member – Project ->Specification-File->Upload a File, Not able to download the uploaded file

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#128]
Summary:
Window-Member – Project ->Specification-File->Upload a File, Not able to download the uploaded file

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a App project
4. Go Specification_>File
5.Upload a file
6.Click save
7.Click on the download file

### Expected Result ###
Window-Member – Project ->Specification-File->Upload a File, Should allow  to download the uploaded file
Need to add 5 second 3 seconds cool down time
### Actual  Result ###
Window-Member – Project ->Specification-File->Upload a File, Not able to download the uploaded file

 ### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36347525-a0ec230a-147e-11e8-8916-8fdccefd71b9.png)
![image](https://user-images.githubusercontent.com/31862600/36347527-ab942a5a-147e-11e8-9932-c61e470749de.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
#48
