### ISSUE TITLE
Window-Member – Project ->Specification->File -> upload a file-> Click edit button and update the description. Description are displaying in single line if we type in multiple lines 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#129]
Summary:
Window-Member – Project ->Specification->File -> upload a file-> Click edit button and update the description. Description are displaying in single line if we type in multiple lines 

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a App project
4. Go Specification->File -> upload a file-> Click edit button and update the description 
As below 1. Use the Doc
2.Read Fully
3.Add comments
4.Review

### Expected Result ###
Window-Member – Project ->Specification->File -> upload a file-> Click edit button and update the description. Description should display in multiple lines 
Need to add 5 second 3 seconds cool down time
### Actual  Result ###
Window-Member – Project ->Specification->File -> upload a file-> Click edit button and update the description. Description are displaying in single line if we type in multiple lines 

 ### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36347362-93e42e80-147b-11e8-945a-13e1fb7ad473.png)
![image](https://user-images.githubusercontent.com/31862600/36347370-bf982dc4-147b-11e8-824f-662d6a11a0c1.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
Not an issue
