### ISSUE TITLE
Manager: Analytics & Data science option should be removed from filter.

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#130]
### Reported URL ###
https://connect.topcoder-dev.com/projects

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com/
2. Login as pshah_manger
3. Click on filter button
4. observe the filter options

### Expected Result ###
As there is no analytics & Data science project type so this option should be removed from filter.

### Actual  Result ###

Analytics & Data science option should be removed from filter which is not there in the project types given.

### Screenshots ###
List of project types:
![image](https://user-images.githubusercontent.com/31851673/36347372-b28497ea-144d-11e8-9259-52c02e0670c8.png)

filter options:
![image](https://user-images.githubusercontent.com/31851673/36347378-c5951f94-144d-11e8-8390-30c88aaead0f.png)

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 64-bit

Browser: Chrome 64.0.3

**Comment by sdgun** [comment]
Not a Bug
