### ISSUE TITLE
Window-Member – Creature a new App Project ->Dashboard-> Click (+) Create Project-> Close the create project page , While closing the create project page entire application getting loaded.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#131]
Summary:
Window-Member – Creature a new App Project ->Dashboard-> Click (+) Create Project-> Close the create project page , While closing the create project page entire application getting loaded.

Note:- In other pages if we close it is navigating without reloading

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a App project
4. Go Specification->File -> upload a file-> Click edit button and update the description 

### Expected Result ###
Window-Member – Creature a new App Project ->Dashboard-> Click (+) Create Project-> Close the create project page , While closing the create project page entire application should not get loaded.
### Actual  Result ###
Window-Member – Creature a new App Project ->Dashboard-> Click (+) Create Project-> Close the create project page , While closing the create project page entire application getting loaded.

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/ouPpLqDopvE

**Comment by sdgun** [comment]
Not a Bug, Similar to https://github.com/topcoderinc/connect-test-cycle-1/issues/34
