### ISSUE TITLE
Owner is able to submit project for review

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#132]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2554

### Reproduction Steps ###
Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123
Select project under Draft phase for which you customer is owner
Navigate to its Specification
Complete all fields and Click Save
Click on Submit for review button

### Expected Result ###

As per Specification owner should not be able to Submit project for review 

### Actual  Result ###

Owner is able to Submit project for review.
https://youtu.be/poGodmrUwdc

### Screenshots ###

*Paste screenshots here.*

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: *browser and version used on test*

**Comment by sdgun** [comment]
Not a Bug

**Comment by gargsaurabh86** [comment]
@sdgun  please check extract from specs: Project can be submitted for review (all fields are completed, but members/owner **didn’t** submit project for review)
Please let me know if m understanding is wrong.

Regards

**Comment by sdgun** [comment]
1. Create a project using pshah_customer/topcoder123
2. Check the drop down it is disabled

![2018-02-22_3-33-44](https://user-images.githubusercontent.com/4592712/36530641-3fa681f2-1781-11e8-8500-4b289cfbf606.jpg)

**Comment by gargsaurabh86** [comment]
Right @sdgun but what about customer able to submit from Specification page? Is that expected behaviour?
![image](https://user-images.githubusercontent.com/29735376/36531709-ada805b0-17b6-11e8-8da6-f72308db710d.png)

**Comment by sdgun** [comment]
@vic-topcoder

**Comment by vic-georgiev** [comment]
This is the mechanics of the system - once a project is created, and all the specification required fields are set, the team members and owner can submit the project for review. Team members can't change project status. Not a bug.
