### ISSUE TITLE
Window-Member – All project are not listed while clicking “View All Project” link, If we follow this steps Creature a new App Project ->Dashboard-> Click (+) Create Project-> Close the create project page -> Click View All Project

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#133]
Summary:
Window-Member – All project are not listed while clicking “View All Project” link, If we follow this steps Creature a new App Project ->Dashboard-> Click (+) Create Project-> Close the create project page -> Click View All Project

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a App project
4. Go to Dashboard-> Click (+) Create Project-> Close the create project page -> Click View All Project

### Expected Result ###
Window-Member – All project are should be listed while clicking “View All Project” link, If we follow this steps Creature a new App Project ->Dashboard-> Click (+) Create Project-> Close the create project page -> Click View All Project
### Actual  Result ###
Window-Member – All project are not listed while clicking “View All Project” link, If we follow this steps Creature a new App Project ->Dashboard-> Click (+) Create Project-> Close the create project page -> Click View All Project
.

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/yIkHHIvmmIo

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/29
