### ISSUE TITLE
Other design project is not asking 160 characters as mandatory for description

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#135]
### Reported URL ###
https://connect.topcoder-dev.com/new-project/generic-design

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com/
2. Login as pshah_customer
3. Click on New project icon
4. Click on view all under Design
5. Click on other design
6. Provide the project name other details
7. Observe the no. of character for description field

### Expected Result ###
It should 160 character minimum as mandatory

### Actual  Result ###

Other design project is not asking 160 characters as mandatory for description

### Screenshots ###

![image](https://user-images.githubusercontent.com/31851673/36347480-e551e2fc-144f-11e8-8136-82f249146ba6.png)

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 64-bit

Browser: Chrome 64.0.3

**Comment by sdgun** [comment]
Not a Bug
