### ISSUE TITLE
Window-Member – “Read More link” is missing if the project have larger description 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#136]
Summary:
Window-Member – “Read More link” is missing if the project have larger description 

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a App project with larger description and name
4.Again Create a App project with smaller description and name

### Expected Result ###
Window-Member – “Read More link” is should be displayed if the project have larger description 
### Actual  Result ###
Window-Member – “Read More link” is missing if the project have larger description 
.

 ### Screenshots ###

See Comments 

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/3NPFBks3Uxs

**Comment by sdgun** [comment]
Not a Bug, The 'Read Me' link appears on the second project card is because you are zooming out the screen. All the long description have 'Read more' link

**Comment by youdare** [comment]
@sdgun 
Both defects are different(Steps also different) could you please check again

**Comment by youdare** [comment]
@sdgun Still iam seeing log of projects dont have "read more link"

![image](https://user-images.githubusercontent.com/31862600/36488758-495ce83a-174a-11e8-8cad-8de4eca23a08.png)
![image](https://user-images.githubusercontent.com/31862600/36488808-5df863aa-174a-11e8-9f4e-c84b69281bc2.png)

Could you please check again

**Comment by sdgun** [comment]
This happens mostly in none space paragraphs. So not an issue

**Comment by youdare** [comment]
Okay  Thank fir Update.
