### ISSUE TITLE
user should not be able to delete uploaded file if the user doesnot have edit permission to the project 

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#137]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/2498/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123 
2. create a new project and upload some files to the project
3. then login as another user (pshah_manager/topcoder123) who has no manage permission to this project, go to https://connect.topcoder-dev.com/projects/2498/specification
4. scroll down, click the trash icon for the uploaded file, observe

### Expected Result ###

*should not allow the user to delete the file.*

### Actual Result ###

*See screenshot, user can delete the file.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
Before deleting:
<img width="1274" alt="beforedeleting" src="https://user-images.githubusercontent.com/4590317/36347648-6717d37c-1497-11e8-914c-1548fba61e0c.png">


After deleting:
<img width="943" alt="afterdeletion" src="https://user-images.githubusercontent.com/4590317/36347649-73248c82-1497-11e8-8e51-4214ef88cf21.png">

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/126
