### ISSUE TITLE
Window-Member – Creature a new App Project ->Specification-> Click (+) Create Project-> Close the create project page , While closing the create project page entire application getting loaded.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#139]
Summary:
Window-Member – Creature a new App Project ->Specification-> Click (+) Create Project-> Close the create project page , While closing the create project page entire application getting loaded.

Note:- In other pages if we close it is navigating without reloading

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a App project
4. Go Specification->File -> upload a file-> Click edit button and update the description 

### Expected Result ###
Window-Member – Creature a new App Project ->Specification-> Click (+) Create Project-> Close the create project page , While closing the create project page entire application should not get loaded.
### Actual  Result ###
Window-Member – Creature a new App Project ->Specification-> Click (+) Create Project-> Close the create project page , While closing the create project page entire application getting loaded.

 ### Screenshots ###

See comments
![image](https://user-images.githubusercontent.com/31862600/36347592-fd307da8-1480-11e8-9d36-7da4e09e465a.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
Note Defect 139 and  134 are different , Dont get confuse while review 

139 - from Specification
131 - From Dashboard

**Comment by sdgun** [comment]
Bug description is entirely incorrect. Incomplete bug report. The title won't match with the steps etc ...
