### ISSUE TITLE
Window-Member – Project is submitted for review if user click cancel on message prompt “

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#142]
Summary:
Window-Member – Project is submitted for review if user click cancel on message prompt “

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a Web project with larger description and Project name
4.Go to specification and Enter the required information
5.With out saving enter some fields like Deice IOS, Fill Notes
6.Click “Submit For Review” button
7.Application will prompt “You have unsaved changes” with “OK” and Cancel” button
8.Click “Cancel” button 

### Expected Result ###
Window-Member – Project should not be submitted for review if user click cancel on message prompt “
### Actual  Result ###
Window-Member – Project is submitted for review if user click cancel on message prompt “

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/PC5qQAm91eA

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1739
