### ISSUE TITLE
Manage is able to add customer and make it owner

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#143]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2202

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com as pshah_manager/topcoder123
2. Select Active project like  2202
3. Click on add project team
4.Search for pshah_customer
5. Select and add it

### Expected Result ###

As per spec: Managers can add Managers, Copilots, Members and not Customers
Also Manager cannot make customer as owners

### Actual  Result ###

Manager is able to add customer
### Screenshots ###

*Paste screenshots here.*
https://youtu.be/Jh8lZG6DmEU
### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: *browser and version used on test*

**Comment by sdgun** [comment]
Not a Bug
