### ISSUE TITLE
 sometimes the uploaded file does not automatically show on the page

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#144]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/2498/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123 
2. create a new project and upload some files to the project
3. observe

### Expected Result ###

*the page should refresh automatically.*

### Actual Result ###

*See screenshot/screencasts.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
See https://youtu.be/nEc6zOzYXLc

**Comment by sdgun** [comment]
I have uploaded the same file and upload process is working
