### ISSUE TITLE
UI issue if the title contains Chinese character

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#145]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/2498/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. create a new project with Chinese character in the title
3. observe the specification page: https://connect.topcoder-dev.com/projects/2498/specification

### Expected Result ###

*title should not overlap with the dotted line.*

### Actual Result ###

*See screenshot/screencasts.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="1404" alt="ui" src="https://user-images.githubusercontent.com/4590317/36347787-3af469dc-149b-11e8-9f51-4087f34da472.png">

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/140
