### ISSUE TITLE
Window-Member – User is able to submit the wireframe application for review without defining the app screen 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#146]
Summary:
Window-Member – User is able to submit the wireframe application for review without defining the app screen 

Note:- I have been using add for more than 

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a Design - Wireframe project with larger description and Project name
4.Go to specification and verify the “Submit for Review button” 

### Expected Result ###
Window-Member – User should not be able to submit the wireframe application for review without defining the app screen 
### Actual  Result ###
Window-Member – User is able to submit the wireframe application for review without defining the app screen 

 ### Screenshots ###

See comments 

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/36347812-155b376e-1487-11e8-9cc8-0b7e69bd3505.png)

**Comment by sdgun** [comment]
No an issue, as per the design
