### ISSUE TITLE
Cancelled project should not be editable anymore

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#147]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/2498/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123 
2. create a new project, then cancel it
3. go to the specification page, try to edit its description, upload some files, etc.

### Expected Result ###

*Cancelled project should not be editable anymore.*

### Actual Result ###

*Still editable, except the project title.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="1417" alt="can" src="https://user-images.githubusercontent.com/4590317/36347813-0b830022-149c-11e8-97ae-8228aa3b8bae.png">

**Comment by sdgun** [comment]
As per the design
