### ISSUE TITLE
Should not allow creating projects with same title

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#148]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/2575*
*https://connect.topcoder-dev.com/projects/2576*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123 
2. create 2 projects with same project title, observe

### Expected Result ###

*Should not allow creating projects with same title*

### Actual Result ###

*It's allowable.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="1200" alt="aa" src="https://user-images.githubusercontent.com/4590317/36347832-dd45c1a8-149c-11e8-9e95-dc3122183085.png">
<img width="1192" alt="bb" src="https://user-images.githubusercontent.com/4590317/36347833-dd8e30d2-149c-11e8-87eb-77159b322af3.png">

**Comment by sdgun** [comment]
No an issue, as per the design
