### ISSUE TITLE
Managers able to see link without joining project

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#149]
### Reported URL ###
*URL where the issue occured, if applicable*

### Reproduction Steps ###
1. Login as **customer**
and navigate to https://connect.topcoder-dev.com/projects/2560 or 
2. Create a project with valid data
3. Go to specification enter valid data and submit for review
4. Add valid link as test.com
5. Logout and **Login as manager** using **pshah_manager**
6. Go to Projects In Review phase
7. Select above created project from list or navigate to https://connect.topcoder-dev.com/projects/2560

### Expected Result ###

As per specs: Managers can see the links only when they join the project
### Actual  Result ###

Manager was able to see link without joining

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36347823-77266eec-1459-11e8-8bee-9c1eb2a1d631.png)

### Issue Information ###

Frequency: Always
Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
Not a bug, As per the design
