### ISSUE TITLE
file is uploaded even though the user does not click "Save Changes" button

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#150]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/2576*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123 
2. create a project
3. then go to specification page, upload a file, observe

### Expected Result ###

*File should be saved only if the user clicks "Save Changes" button on the page.*

### Actual Result ###

*file is uploaded even though the user does not click "Save Changes" button.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="1121" alt="save" src="https://user-images.githubusercontent.com/4590317/36347862-83b11614-149d-11e8-8bda-6b24d34f39de.png">

**Comment by sdgun** [comment]
As per the design, No need to click on 'Save changes' again to save the uploaded documents. If user doesn't want uploaded documents, user can simply remove them by clicking on the delete button
