### ISSUE TITLE
Window-Member – In Let's setup your Visual Design project, PROJECT ESTIMATE IS WRONG AND PROJECT ESTIMATE IS NOT UPDATED WHILE CLIKING 1-3,4-8 AND 9-4

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#151]
Summary:
Window-Member – In Let's setup your Visual Design project, PROJECT ESTIMATE IS WRONG AND PROJECT ESTIMATE IS NOT UPDATED WHILE CLIKING 1-3,4-8 AND 9-45
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a Design - Visual Design project with larger description and Project name
4. Check project , PROJECT ESTIMATE
5. CLIK  PROJECT ESTIMATE 1-3,4-8 AND 9-45

### Expected Result ###
Window-Member – In Let's setup your Visual Design project, PROJECT ESTIMATE SHOULD BECORRECT AND PROJECT ESTIMATE SHOULD BE UPDATED WHILE CLIKING 1-3,4-8 AND 9-45
### Actual  Result ###
Window-Member – In Let's setup your Visual Design project, PROJECT ESTIMATE IS WRONG AND PROJECT ESTIMATE IS NOT UPDATED WHILE CLIKING 1-3,4-8 AND 9-45

 ### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/31862600/36347880-eb797a30-1488-11e8-8012-a8ea8a67d31d.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/81

**Comment by youdare** [comment]
@sdgun 
Defect# 81 is for Wire frame project
Defecrt#151 is for Visual Design project

Both are different

**Comment by sdgun** [comment]
Same section, so can't count as separate bugs

**Comment by youdare** [comment]
Thanks for Update
