### ISSUE TITLE
Edit link option not coming for member

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#152]
### Reported URL ###
*URL where the issue occured, if applicable*

### Reproduction Steps ###
1. Login as https://connect.topcoder-dev.com as pat_monahan/topcoder123!
2. open any project or https://connect.topcoder-dev.com/projects/2560
3. join the project if not already joined
4 . Create new links if old links not present 
5. Now hover mouse over added link

### Expected Result ###
As per specs: Links: All project members can edit the link

### Actual  Result ###

Edit option was not present ony delete is present

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36347875-be1802a6-145a-11e8-90e6-bbf98b41035a.png)

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1801
