### ISSUE TITLE
[common] text input (Notes) should be trimmed

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#153]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/2576/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123 
2. create a project, select the type as App, 
3. enter some additional spaces for each text field, save it
4. then observe the specification

### Expected Result ###

*"Notes" field should be trimmed.*

### Actual Result ###

*See screenshot, it's not trimmed.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="1199" alt="notes" src="https://user-images.githubusercontent.com/4590317/36347901-d4893af2-149e-11e8-934b-25e81663cfcc.png">

**Comment by sdgun** [comment]
Not an issue
