### ISSUE TITLE
Read more description option not coming for member

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#154]
### Reported URL ###
*URL where the issue occured, if applicable*

### Reproduction Steps ###
Login as https://connect.topcoder-dev.com as pat_monahan/topcoder123!
open any project or https://connect.topcoder-dev.com/projects/2560
join the project if not already joined

### Expected Result ###

Since project description is not displayed completely as its more than 160 characters so person should get option to **read more**

### Actual  Result ###

Read more option is not present

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36347903-c93a44ae-145b-11e8-8767-46a478c7fd30.png)

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
Text without spaces, Not a bug
