### ISSUE TITLE
Window-Member – Wireframe ->Other Design- Not able to to navigate to specification tab

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#155]
Summary:
Window-Member – Wireframe ->Other Design- Not able to to navigate to specification tab
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a Design - Other Design project with larger description and Project name
4. Try to go to specification of Other Design project

### Expected Result ###
Window-Member – Wireframe ->Other Design- Should allow to navigate to specification tab
### Actual  Result ###
Window-Member – Wireframe ->Other Design- Not able to to navigate to specification tab

 ### Screenshots ###

See coments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/36347908-037344e4-148a-11e8-9fa8-64e6c8e4c2ba.png)

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/96
