### ISSUE TITLE
project budget should not be negative

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#156]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/2579/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123 
2. create a project, select the type as App, proceed
3. then enter negative number for project budget, save

### Expected Result ###

*Should validate project budget.*

### Actual Result ###

*See screenshot, it can be saved.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="1036" alt="budget" src="https://user-images.githubusercontent.com/4590317/36347937-925a5638-149f-11e8-9744-2be4b372cf86.png">

**Comment by sdgun** [comment]
#65
