### ISSUE TITLE
Mark all should be Mark all as read

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#158]
### Reported URL ###

*https://connect.topcoder-dev.com/notifications*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123 
2. create some projects , ensure some notifications are receieved
3. click the icon, observe
4. go to https://connect.topcoder-dev.com/notifications, observe

### Expected Result ###

*"Mark all" should be "Mark all as read" on the view all notifications page, to be consistence.*

### Actual Result ###

*See screenshots.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="475" alt="allre" src="https://user-images.githubusercontent.com/4590317/36347954-810ddd72-14a0-11e8-8974-c473fbbf6be2.png">

<img width="1136" alt="mark" src="https://user-images.githubusercontent.com/4590317/36347955-81480182-14a0-11e8-8c52-ed1561326c39.png">

**Comment by sdgun** [comment]
Not a Bug
