### ISSUE TITLE
id should not contain comma

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#159]
### Reported URL ###

*https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. observe the projects list

### Expected Result ###

*id should not contain comma.*

### Actual Result ###

*See screenshot.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="1180" alt="id" src="https://user-images.githubusercontent.com/4590317/36347970-0ddccbf0-14a1-11e8-929b-df33d345d6c9.png">

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/182
