### ISSUE TITLE
error message should be detailed for the user

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#160]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/800/discussions/2258*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. open https://connect.topcoder-dev.com/projects/800/discussions
3. create a new discussion, then update its topic name to a long title
4. save changes, observe

### Expected Result ###

*Error message should be detailed for the user.*

### Actual Result ###

*See screenshot, not sure if it's due to long topic title or backend error.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Safari Version 11.0.3*

**Comment by winterflame** [comment]
<img width="1439" alt="error" src="https://user-images.githubusercontent.com/4590317/36348019-bab8cd32-14a2-11e8-9f3c-c6b93a645c53.png">

**Comment by sdgun** [comment]
Not an issue
