### ISSUE TITLE
Window-Manger – Create App project – Specification should not be non editable, If the project is completed 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#162]
Summary:
Window-Manger – Create App project – Specification should not be non editable, If the project is completed 
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a App project with larger description and Project name
4. Move the project to completed
5.Go to Specification tab
6. Try to edit the Specification

### Expected Result ###
Window-Manger – Create App project – Specification should not be non editable, If the project is completed 
### Actual  Result ###
Window-Manger – Create App project – Specification is editable, If the project is completed 

 ### Screenshots ###

see comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/36348089-aba1671e-148e-11e8-91ef-057ff4140ce8.png)

![image](https://user-images.githubusercontent.com/31862600/36348095-bee10fb4-148e-11e8-95a9-840e2e1d61ac.png)

**Comment by sdgun** [comment]
As per the design
