### ISSUE TITLE
Window-Manger – Application showing error message as “D’oh! Something went wrong” and Create new project page while clicking Clear filter button

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#163]
Summary:
Window-Manger – Application showing error message as “D’oh! Something went wrong” and Create new project page while clicking Clear filter button
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Go to Tile View and Click Filter button
4.Click Clear Filter button without entering anything 

### Expected Result ###
Window-Manger – Application should show any error message as “D’oh! Something went wrong” and should nor show any Create new project page while clicking Clear filter button
### Actual  Result ###
Window-Manger – Application showing error message as “D’oh! Something went wrong” and Create new project page while clicking Clear filter button

 ### Screenshots ###

see comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/V2OHwlFFfLs

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/104
