### ISSUE TITLE
project name should be underlined only if hovering on the name

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#164]
### Reported URL ###

*https://connect.topcoder-dev.com/projects?sort=best%20match*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. hovering on any row, observe

### Expected Result ###

*project name should be underlined only if hovering on the name.*

### Actual Result ###

*See screenshot, it's underlined when hovering on the row.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="1432" alt="un" src="https://user-images.githubusercontent.com/4590317/36348181-022bd1ee-14a5-11e8-9f1d-6db66d826f77.png">

**Comment by sdgun** [comment]
Whole row in a hyperlink
