### ISSUE TITLE
Window-Manger – RFID should have separate column, It should not merged with the project description

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#165]
Summary:
Window-Manger – RFID should have separate column, It should not merged with the project description
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Find the RFID

### Expected Result ###
Window-Manger – RFID should have separate column, It should not merged with the project description

If we are going to merge please make a fair display dont overlap with Description 
### Actual  Result ###
Window-Manger – RFID is not having separate column, It is merged with the project description

 ### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36348222-c555b92e-1490-11e8-8e7e-98b4bcbb498b.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
As per the design
