### ISSUE TITLE
topics are not sorted properly after creating a new discussion

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#166]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/800/discussions/2262*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. go to https://connect.topcoder-dev.com/projects/800/discussions
3. create some new discussions, observe the left side 

### Expected Result ###

*Topics should be sorted by last updated date.*

### Actual Result ###

*See screenshot.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Safari Version 11.0.3*

**Comment by winterflame** [comment]
<img width="1376" alt="sorting" src="https://user-images.githubusercontent.com/4590317/36348242-38729430-14a6-11e8-83e1-c495877490b7.png">

**Comment by winterflame** [comment]
"27m" and "28m" rows should be shown above "7h", "8h"

**Comment by sdgun** [comment]
Time displayed in front of the title is the update time of the current discussion thread.
