### ISSUE TITLE
Window-Manger – When user clicks empty search , App should throw some message as “Enter Keyword for search”

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#167]
Summary:
Window-Manger – When user clicks empty search , App should throw some message as “Enter Keyword for search”
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Click search button without entering anything

### Expected Result ###
Window-Manger – When user clicks empty search , App should throw some message as “Enter Keyword for search”
### Actual  Result ###
Window-Manger – When user clicks empty search , App is not throwing any message to user

 ### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36348246-6326cd5a-1491-11e8-914f-8b3a5f0ce2d0.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
Nothing happens when the user clicks on the empty search field, so this is as per the design. Not a bug
