### ISSUE TITLE
Window-Manger – Filter count is not increased

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#168]
Summary:
Window-Manger – Filter count is not increased
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Click Filter button
4.Apply more than 3 filter

### Expected Result ###
Window-Manger – Filter count should be increased
### Actual  Result ###
Window-Manger – Filter count is not increased

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/36348261-f24ef408-1491-11e8-94af-d37ff11e0081.png)

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/75
