### ISSUE TITLE
Continue does nothing but saving the project and staying at the same page

### ISSUE THREAD

**Issue by kaygee1** [topcoderinc/connect-test-cycle-1#17]
Open https://connect.topcoder-dev.com/
Login as pshah_manager/topcoder123

CLick on + and CLick on Create an app priject

Enter details of project - all details and click on contine

Observe

actual - the project is saved but it stays in the same page
How many ever times we click on Continue it keeps saving and staying in the same page

win 10
Google Chrome is up to date
Version 64.0.3282.167 (Official Build) (64-bit)

**Comment by sdgun** [comment]
Can't reproduce the bug using the provided steps and details. Must be a network issue.
