### ISSUE TITLE
tooltip for adding discussion should be changed

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#170]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/800/discussions*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. go to https://connect.topcoder-dev.com/projects/800/discussions
3. create some new discussions one after another, it will display error message
4. then hover on the + icon, observe the tooltip

### Expected Result ###

*Tooltip should be changed to meaningful content.*

### Actual Result ###

*See screenshot.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="1210" alt="add" src="https://user-images.githubusercontent.com/4590317/36348343-5d2059dc-14a8-11e8-807c-37b2e77915ee.png">

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1768
