### ISSUE TITLE
Window-Manger – Filter order is getting changed while clearing search 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#171]
Summary:
Window-Manger – Filter order is getting changed while clearing search 
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123 and Verify the filter order
3.Enter some text to search and Click Search button
4.Result will be displayed 
5.Clear serach
6.Verify the Filter order

### Expected Result ###
Window-Manger – Filter order should get changed automatically while clearing search 
### Actual  Result ###
Window-Manger – Filter order is getting changed while clearing search 

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/8LlIA92QYWU

**Comment by sdgun** [comment]
Expected Result = Actual Result, Can't count this because of the incomplete bug report

I assume;

Expected Result: After clearing the search result by the (x) all the projects must be displayed on the table sorted by the 'Last Updated' (OR currently selected value)

**Comment by youdare** [comment]
@sdgun My expected and Actual are different, my intention is while clearing search ,App should reset to original order.

Please consider this as valid bug,

Expected Result
Window-Manger – Filter order should get changed automatically while clearing search

Actual Result
Window-Manger – Filter order is getting changed while clearing search
