### ISSUE TITLE
Not able to add member in Project Team

### ISSUE THREAD

**Issue by rahulranjanmca** [topcoderinc/connect-test-cycle-1#172]
### Reported URL ###

https://connect.topcoder-dev.com/projects/2587/

### Reproduction Steps ###
1. Create Project with login / without login
2. Go to Project Page
3. Try to add member in project team

### Expected Result ###
User should be added to project team.

### Actual  Result ##
Once you add the project team, it give the error.

### Screenshots ###
<img width="1680" alt="screen shot 2018-02-18 at 10 07 48 am" src="https://user-images.githubusercontent.com/1094805/36348353-b1d844e0-1493-11e8-9a98-7035fb16fee9.png">

### Issue Information ###

Frequency: Every time

Device: Mac Pro 2017

OS: High Seira

Browser: Mac Safari Version 11.0.2

**Comment by sdgun** [comment]
#8
