### ISSUE TITLE
Window-Manger – Not able to remove first added filter  

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#173]
Summary:
Window-Manger – Not able to remove first added filter  
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123 and Verify the filter order
3.Apply filter as Website and Chatbot
4.Now try to remove Website filter

### Expected Result ###
Window-Manger – Should allow to remove first added filter  
### Actual  Result ###
Window-Manger – Not able to remove first added filter  

 ### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36348408-4937111c-1495-11e8-90ed-83ba754cb4af.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/67
