### ISSUE TITLE
Window-Manger – All the applied filter are removed if we press “ESC” button from keyboard 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#174]
Summary:
Window-Manger – All the applied filter are removed if we press “ESC” button from keyboard 
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123 and Verify the filter order
3.Apply all the filter as Website and Chatbot ect
4.Now press EXC button 2 time

### Expected Result ###
Window-Manger – filter should not be removed if we press “ESC” button from keyboard 
### Actual  Result ###
Window-Manger – All the applied filter are removed if we press “ESC” button from keyboard 

 ### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36348459-54ced810-1496-11e8-85e1-111ee73fa263.png)
![image](https://user-images.githubusercontent.com/31862600/36348463-5a58a0fe-1496-11e8-9eb2-be32f34e00c0.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
Expected behavior
