### ISSUE TITLE
Delete Comment is having the text of delete post

### ISSUE THREAD

**Issue by rahulranjanmca** [topcoderinc/connect-test-cycle-1#176]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2592

### Reproduction Steps ###
1.  login with pshah_manager/topcoder123
2. create any project
3. This will add a post into the feed
4. comment something
5. now click on edit, select delete comment
6. The popup shows the text as delete post

### Expected Result ###
Are you sure you want to delete this comment?

### Actual  Result ###

It shows the text "Are you sure you want to delete this post?" 

### Screenshots ###

<img width="1680" alt="screen shot 2018-02-18 at 11 16 32 am" src="https://user-images.githubusercontent.com/1094805/36348823-04219936-149e-11e8-9c7a-b735d0669d49.png">

### Issue Information ###

Frequency: every time
Device: Mac Pro 2017
OS: High Seira
Browser: Safari 11.0.2

**Comment by sdgun** [comment]
Not a Bug
