### ISSUE TITLE
Window-Manger – Search and filter is not removed, If manager create a new project after applying Search and filter

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#177]
Summary:
Window-Manger – Search and filter is not removed, If manager create a new project after applying Search and filter
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123 and Verify the filter order
3.Apply all the filter as Website and Chatbot ect
4.Srearch keyword as”demo”
5.Click create project and create a project
6.After project created click view all project

### Expected Result ###
Window-Manger – Search and filter should be removed, If manager create a new project after applying Search and filter
### Actual  Result ###
Window-Manger – Search and filter is not removed, If manager create a new project after applying Search and filter

 ### Screenshots ###
![image](https://user-images.githubusercontent.com/31862600/36348878-3f4b4ace-149f-11e8-8f73-159114bbd384.png)
![image](https://user-images.githubusercontent.com/31862600/36348879-4286c952-149f-11e8-91ba-15f4efc5d827.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
Filter won't reset till user click on 'Clear filter' option
