### ISSUE TITLE
Window-Manger – Project status tab is removing the applied filter, if we click (+) create project and cancel.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#178]
Summary:
Window-Manger – Project status tab is removing the applied filter, if we click (+) create project and cancel.
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123 and Verify the filter order
3.In Project status tab click “Draft”
4.Click (+) create project
5.Click cancel button

### Expected Result ###
Window-Manger – Project status tab should not remove the applied filter, if we click (+) create project and cancel.
### Actual  Result ###
Window-Manger – Project status tab is removing the applied filter, if we click (+) create project and cancel.

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/36348932-ba94b746-14a0-11e8-9793-434273400105.png)
![image](https://user-images.githubusercontent.com/31862600/36348933-bd36a70c-14a0-11e8-8daa-76ba521384eb.png)
![image](https://user-images.githubusercontent.com/31862600/36348934-c0ab3402-14a0-11e8-84f0-533430f6e337.png)

**Comment by sdgun** [comment]
As per the design
