### ISSUE TITLE
Project "App Project" created appears twice

### ISSUE THREAD

**Issue by kaygee1** [topcoderinc/connect-test-cycle-1#18]
Open https://connect.topcoder-dev.com/
Login as pshah_manager/topcoder123

CLick on + and CLick on Create an app priject

Enter details of project - all details and click on continue

Observe

actual - the project is saved but it stays in the same page
Click continue again immediately and see

actual - Project "App Project created appears twice

expected - this should not happen

Google Chrome is up to date
Version 64.0.3282.167 (Official Build) (64-bit)

**Comment by kaygee1** [comment]
![5](https://user-images.githubusercontent.com/5115050/36344247-5ce09af6-143d-11e8-889e-736ff1837350.png)

**Comment by sdgun** [comment]
Can't reproduce the bug using the provided steps and details
