### ISSUE TITLE
Window-Manger –  Not able to search with project ID 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#181]
Summary:
Window-Manger –  Not able to search with project ID 
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123 and Verify the filter order
3.Search with Project ID “944”

### Expected Result ###
Window-Manger –  should allow to search with project ID 
### Actual  Result ###
Window-Manger –  Not able to search with project ID 

 ### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36348997-945d5040-14a2-11e8-968b-93a200e15d18.png)
![image](https://user-images.githubusercontent.com/31862600/36348998-a186ae56-14a2-11e8-9691-23b03d68e2f1.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
Not a Bug
