### ISSUE TITLE
Window-Manger –  Project ID should not be separated with ,-Comma  

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#182]
Summary:
Window-Manger –  Project ID should not be separated with ,-Comma  
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123 and Verify the filter order
3.View the project ID

### Expected Result ###
Window-Manger –  Project ID should not be separated with ,-Comma  
### Actual  Result ###
Window-Manger –  Project ID is separated with ,-Comma  

 ### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36349009-e74467b2-14a2-11e8-968d-032ab3a1815f.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
As per the design
