### ISSUE TITLE
Window-Manger –  We are getting multiple error message when we lost internet connectivity  

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#183]
Summary:
Window-Manger –  We are getting multiple error message when we lost internet connectivity   
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123 and Verify the filter order
3.Go to notification page
4. Disconnect the internet connectivity 
5.Click any nonfiction 
### Expected Result ###
Window-Manger –  We Should get single error message when we lost internet connectivity   
### Actual  Result ###
Window-Manger –  We are getting multiple error message when we lost internet connectivity   

 ### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36349119-d024bd36-14a5-11e8-90b0-b539d9e989ec.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
No an issue, as per the design
