### ISSUE TITLE
App is logging out then logging in again after closing new project window

### ISSUE THREAD

**Issue by macs054** [topcoderinc/connect-test-cycle-1#184]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc&status=active

### Reproduction Steps ###
Go to https://connect.topcoder-dev.com/
Login as pat_monahan/topcoder123!
Click All Projects tab
Scroll down and click 'Load more projects'
Switch to Tile View
Scroll down and click the New Project tile
Close the new project window

### Expected Result ###

Should return to the previous page

### Actual  Result ###

App is logging out then logging in again

### Screencast ###

https://youtu.be/msNzTr6VcZQ

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2t

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1737
