### ISSUE TITLE
Window-Manger – Not able to view Feature requirements notes in specification page, Manager have to click “Add/Edit Feature” button to see notes.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#185]
Summary:
Window-Manger – Not able to view Feature requirements notes in specification page, Manager have to click “Add/Edit Feature” button to see notes.

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123 and Verify the filter order
3.Create a new App project
4. Go to specification 
5.Click “Add/Edit Feature” button and Add some features and Notes
6.Click save and close

### Expected Result ###
Window-Manger – Should allow to view Feature requirements notes in specification page, Manager have to click “Add/Edit Feature” button to see notes.
### Actual  Result ###
Window-Manger – Not able to view Feature requirements notes in specification page, Manager have to click “Add/Edit Feature” button to see notes.

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/_KmD2iZan8k

**Comment by sdgun** [comment]
No such requirement, not a bug

**Comment by youdare** [comment]
@sdgun This is valid defect, Please refer below screenshot.

When i try to Add a custom feature, iam able see the note. the issue is only on proposed features 

![image](https://user-images.githubusercontent.com/31862600/36486419-7646a1a2-1744-11e8-9263-3506a1e738ff.png)
![image](https://user-images.githubusercontent.com/31862600/36486427-7c04fca6-1744-11e8-8fd0-469216d86a22.png)

**Comment by sdgun** [comment]
Not a Bug, For custom feature 'Notes' will display but not for others

**Comment by youdare** [comment]
@sdgun Thanks For Update Agree
