### ISSUE TITLE
Window-Copilot – Not able to view notification from the Notification page

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#188]
Summary:
Window-Copilot – Not able to view notification from the Notification page

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_copilot/topcoder123
3.Go to notification page
4.Access the notification

### Expected Result ###
Window-Copilot – Should able to view notification from the Notification page
### Actual  Result ###
Window-Copilot – Not able to view notification from the Notification page

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/mdLrPvwBO0I

**Comment by sdgun** [comment]
There is no specific test data or a direct URL provided to reproduce this issue. Incomplete bug report. When I click on a notification it will open the project related to that.

This Notification may be related to a deleted project.

**Comment by youdare** [comment]
@sdgun  Just now tried same step mentioned in the defect able to reproduce the issue.
Please check video in comment

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1736
