### ISSUE TITLE
No projects appear when page is refreshed

### ISSUE THREAD

**Issue by macs054** [topcoderinc/connect-test-cycle-1#190]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc

### Reproduction Steps ###
Go to https://connect.topcoder-dev.com/
Login as pshah_customer/topcoder123
Take note of the project list
Refresh the page

### Expected Result ###

Should load all the projects

### Actual  Result ###

No projects appear when user refreshes the page, the workaround for this is to click the logo.

### Screenshot ###
![image](https://user-images.githubusercontent.com/1199534/36349437-ddf144ea-14c1-11e8-84ee-1f2e04c1b44b.png)

### Screencast ###

https://youtu.be/iK9U5XsVMvU

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2

**Comment by sdgun** [comment]
#189
