### ISSUE TITLE
Newly created project is at the bottom of the list

### ISSUE THREAD

**Issue by macs054** [topcoderinc/connect-test-cycle-1#191]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc

### Reproduction Steps ###
Go to https://connect.topcoder-dev.com/
Login as pshah_customer/topcoder123
Create a new project of any type
After being redirected to the new project's dashboard, click View All Projects
Scroll down and notice that the new project is at the bottom of the list

### Expected Result ###

The new project should be at the top from the beginning and according to the doc 'Ordering should be by latest activity'.

### Actual  Result ###

The newly created project appears at the bottom of the list, it will only appear at the top when you refresh the page (by clicking the logo). 

### Screencast ###

https://youtu.be/7JWftw6uThI

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2t

**Comment by sdgun** [comment]
Side effect of https://github.com/topcoderinc/connect-test-cycle-1/issues/22, When user goes into 'All Projects' Sorting is not properly working
