### ISSUE TITLE
Load more projects redirects to 'No projects' page 

### ISSUE THREAD

**Issue by macs054** [topcoderinc/connect-test-cycle-1#193]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc

### Reproduction Steps ###
Go to https://connect.topcoder-dev.com/
Login as pshah_customer/topcoder123
(Prerequisite: Must have more than 20 projects to make 'Load more projects' show)
Scroll down and click 'Load more projects'

### Expected Result ###

Should load more projects

### Actual  Result ###

Page redirects to 'No projects page'

### Screencast ###

https://youtu.be/BKaP56zE_JE

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/101
