### ISSUE TITLE
Search bar replacing space with %20 and appending with 25 after % for each search button click.

### ISSUE THREAD

**Issue by Raveem13** [topcoderinc/connect-test-cycle-1#194]
### Reported URL ###
https://connect.topcoder-dev.com/projects?keyword=vgg%20fgg%20gg&sort=best%20match

### Reproduction Steps ###
Go to https://connect.topcoder-dev.com/
Login as pat_monahan/topcoder123!
Search eg 'vgg fgg', click Search
Put cursor in search bar
Click Search or press Enter multiple times (without changing the search text)

### Expected Result ###
1. Search bar input field should display entered text as vgg fgg

### Actual  Result ###
1.Search bar replacing space with %20 and appending with 25 after % for each search button click.

### Screenshots ###

![image](https://user-images.githubusercontent.com/32996922/36349727-a8e19eb8-14b1-11e8-84d6-81f15bfe87ab.png)

Frequency: Always

Device: Dell 3537

OS: Windows 10

Browser: Chrome Version 64.0.3282.167

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/19
