### ISSUE TITLE
Count on Filters button not updating.

### ISSUE THREAD

**Issue by Raveem13** [topcoderinc/connect-test-cycle-1#195]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc&type=website%2Cvisual_design%2Canalytics%2Cquality_assurance%2Cchatbot
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Login with test accounts
3. Click on filters and add two or more project types to filters.

### Expected Result ###

Count on Filters button will update number as much project types you add to filter.

### Actual  Result ###

Filter button updating for only one filter type and showing count as on for two or more project types to filters.

### Screenshots ###

![image](https://user-images.githubusercontent.com/32996922/36349945-94aea01e-14b4-11e8-9bae-f281979d4f21.png)
![image](https://user-images.githubusercontent.com/32996922/36349948-ae04253e-14b4-11e8-8e91-07316b373edf.png)

### Issue Information ###

Frequency: Always

Device: Dell 3537

OS: Windows 10

Browser: Chrome Version 64.0.3282.167

**Comment by sdgun** [comment]
Only one filter is here so the count is ok
