### ISSUE TITLE
User unable to figure out mandatory fields on create new project page

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#199]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/new-project/mobility-testing

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ with pshah_copilot/topcoder123
2. Create new project
3. Select QA project
4. Mobile testing project
5. Now you are on Let's setup your Mobility Testing project page.

## Expected Result ###
 You should be able to identify mandatory field by looking at them

### Actual  Result ###

User unable to find which are mandatory fields

### Screenshots ###
![image](https://user-images.githubusercontent.com/29735376/36350229-bc3cacde-148c-11e8-8897-1443ac56408e.png)

*Paste screenshots here.*

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
Not a Bug, All the projects won't have required field marked on the form
