### ISSUE TITLE
Project Page getting disabled!!

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#20]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2473/

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123
2. navigate to https://connect.topcoder-dev.com/projects/2473/ project
3. On left side under Project team
4. Hover over Parth Customer(you)
5. Click leave Project
6. You are about to leave project
7. Hit Leave button again
8. **Wait for sometime**
9. You will get error
10 Hover over Parth Customer(you)
11 Click leave Project
12 You are about to leave project
13 Observe

### Expected Result ###

*Enter the expected result here.*
Project team section is enabled

### Actual  Result ###

*Enter the expected result here.*
Project team section is disabled

Error on page. Screenshot attached

### Screenshots ###
![image](https://user-images.githubusercontent.com/29735376/36344259-6bec6526-140f-11e8-8b3b-9d50ea0cc75b.png)

*Paste screenshots here.*

### Issue Information ###

Frequency: Mostly

Device: *device used for testing*

OS: Windows

Browser: Edge

**Comment by sdgun** [comment]
Duplicate. Side effect of the issue https://github.com/topcoderinc/connect-test-cycle-1/issues/15
