### ISSUE TITLE
Manager: Able to apply the same status again

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#200]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com 
2. Login as pshah_manager
3. From dashboard select any project and observe the status of that project
4. Now apply the same status again using drop down and observe

### Expected Result ###

Should not allow to change the status to the same status.

### Actual  Result ###

It allowing manager to change the status to same status.
i.e. If the project is already completed and again manager is able apply the completed status and Project updated message displayed.
There no warning message displayed for this action.

### Screenshots ###

https://youtu.be/cqKiyrF4uAo

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 7 64 bit

Browser: Chrome 64.0

**Comment by bikakk** [comment]
@sdgun , can you please mention the duplicate id

**Comment by sdgun** [comment]
#180
