### ISSUE TITLE
User able to upload any type of file extesion

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#201]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2606/specification

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com using pshah_copilot/topcoder123
2. Navigate to Specification page of any project like https://connect.topcoder-dev.com/projects/2606/specification
3. Now you have the option to upload file
4. Try uploading .bat file like BatchFileuploadTest

### Expected Result ###

User should be restricted to upload only specific file extension

### Actual  Result ###

User is unrestricted to upload any file extension
And there is no info regarding same in upload section

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36350420-5b21d390-148f-11e8-8f4d-444a85e2c42b.png)

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: Edge

Browser: *browser and version used on test*

**Comment by sdgun** [comment]
@vic-topcoder

**Comment by vic-georgiev** [comment]
We don't restrict files attached to a project. The reason is that customers can upload any files that would help us understand the problem. Good observation! Not a bug
