### ISSUE TITLE
User is able to enter numbers in  name field in link  section 

### ISSUE THREAD

**Issue by JAMa1994** [topcoderinc/connect-test-cycle-1#203]
### Reported URL ###
https://connect.topcoder-dev.com/projects/263/

### Reproduction Steps ###
Invoke url
2.sign in with valid credentials [ [pshah_copilot/topcoder123]]
3.Tap on All projects option
4.Tap on any project or bug fix project option
5.Tap on + icon in links section
6.Tap on  name field
7.Enter the numbers
8,Verify the result

### Expected Result ###

User should not be allowed to enter  the numbers in  name field
### Actual  Result ###

User  is able to enter the numbers in name field section

### Screenshots ###

![issue](https://user-images.githubusercontent.com/34433543/36350575-bcb338ca-14c0-11e8-8dd0-7560dab518ee.png)

![image](https://user-images.githubusercontent.com/34433543/36418167-0e7c13ea-1654-11e8-9890-b45931b9b326.png)

### Issue Information ###

Frequency: Always 
Device: Desktop

OS: Windows
Browser:  ALL (chrome , firefox)

**Comment by JAMa1994** [comment]
Firefox version :58.0.2
chrome version: 62.0.3202.94

**Comment by sdgun** [comment]
Anything can be entered as the Name, Not a bug
