### ISSUE TITLE
No session time out on site

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#204]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com using any valid  credentials pshah_copilot/topcoder123
2. Now on projects page wait for or than 1, 2,3, 4, 5 hrs

### Expected Result ###

Session should expire and user should navigate to login page

### Actual  Result ###

Session donot expire and user always stays where it was.

### Screenshots ###

*Paste screenshots here.*

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
Not a Bug
