### ISSUE TITLE
Unable to select another font styles , when the user taps on </> option in post section  in discussion page 

### ISSUE THREAD

**Issue by JAMa1994** [topcoderinc/connect-test-cycle-1#207]
### Reported URL ###
https://connect.topcoder-dev.com/projects/263/discussions

### Reproduction Steps ###
1. Invoke url
2.sign in with valid credentials [ [pshah_copilot/topcoder123]]
3.Tap on All projects option 
4.Tap on any project or bug fix project option
5.Tap on discussion option
6.Enter the coments and tap on  </>  font style option 
7.Tap on another font styles  or(please refer the video)
8.Verify the result

### Expected Result ###

User should be able select another styles

### Actual  Result ###
Unable to select another font styles , when the user taps on </> option  (all other font option are disabled)

*Paste screenshots here.*

![ise](https://user-images.githubusercontent.com/34433543/36350829-e1ec029e-14c4-11e8-945d-fdbd307c34ac.png)

### Issue Information ###

Frequency: always

Device:  Desktop

OS:  Windows

Browser:  Firefox, chrome

**Comment by JAMa1994** [comment]
Please find the video your reference

https://youtu.be/2YP6dSoxjO0

**Comment by JAMa1994** [comment]
Firefox version :58.0.2
chrome version: 62.0.3202.94

**Comment by sdgun** [comment]
Can't select another if you select that icon

**Comment by JAMa1994** [comment]
@sdgun 

We are unable to select another icon if you tap on </> icon
