### ISSUE TITLE
Terms page is not opened on a new tab

### ISSUE THREAD

**Issue by barranquerox** [topcoderinc/connect-test-cycle-1#209]
### Reported URL ###
https://connect.topcoder-dev.com/

### Reproduction Steps ###
1. Click on the terms link on the bottom  of the page

### Expected Result ###

*Page should be opened on a new tab, as the other links on the botton*

### Actual  Result ###

*Terms page is opened on the same tab*

### Screenshots ###

*No screenshots*

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome 64*

**Comment by sdgun** [comment]
#2
