### ISSUE TITLE
error occurred while cancel project 

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#21]
### Reported URL ###
*https://connect.topcoder-dev.com/projects/2179/*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. go to https://connect.topcoder-dev.com/projects/2179/, first change it to completed status
3. then select "CANCELLED", click Cancel Project button, select an option, click "Cancel Project", observe

### Expected Result ###

*No error shown.*

### Actual Result ###

*See screenshot.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="1192" alt="e2" src="https://user-images.githubusercontent.com/4590317/36344286-d25895bc-1452-11e8-86b1-d2e05262cc83.png">

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1750
