### ISSUE TITLE
Spacing is not correct on the letters of the connect logo on Firefox

### ISSUE THREAD

**Issue by barranquerox** [topcoderinc/connect-test-cycle-1#210]
### Reported URL ###
https://accounts.topcoder-dev.com/connect

### Reproduction Steps ###
1. Open the page
2. Check the spacing of the letters on the Connect logo on the top left corner

### Expected Result ###

*Spacing should be equal to the other browsers*

### Actual  Result ###

*Letters are significantly closer on Firefox than on the other browsers*

### Screenshots ###

*No screenshots
![chrome](https://user-images.githubusercontent.com/4928043/36351011-dc71cece-14a2-11e8-9692-602a253d1047.PNG)
![firefox](https://user-images.githubusercontent.com/4928043/36351012-e26ef176-14a2-11e8-8462-6783fed2f1ff.PNG)

*

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Firefox 58.0.2*

**Comment by sdgun** [comment]
Not a Bug
