### ISSUE TITLE
Customer:[Inconsistent]: Reload page to view updates notification triggered even though there is no updates

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#211]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2608/

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com 
2. Login as pshah_Customer
3. Open a project which in review status
4. Now post a new comment in the thread
5. Add couple of comments more
6. observe the notification

### Expected Result ###

Reload page to view updates notification should not be triggered if there is no updates.

### Actual  Result ###
Reload page to view updates notification triggered even though there is no updates posted.
Click on Reload page to view updates and observe that there is no new updates.
Note: This is inconsistent behaviour, we need to try couple of times to reproduce this behaviour.

### Screenshots ###

https://youtu.be/C-PyPRyPPZs

### Issue Information ###

Frequency: 2 out of 5 times

Device: Laptop

OS: Windows 7 64 bit

Browser: Chrome 64.0

**Comment by sdgun** [comment]
Not a bug, This is to slow down the commenting speed, Better to have a user-friendly error message than this
