### ISSUE TITLE
T letter is rendered incomplete on the Connect logo

### ISSUE THREAD

**Issue by barranquerox** [topcoderinc/connect-test-cycle-1#212]
### Reported URL ###
*https://accounts.topcoder-dev.com/connect*

### Reproduction Steps ###
1. Open the page
2. Zoom in the page
3. Check the Connect Logo. The T is not completely rendered

### Expected Result ###

*The T letter should be rendered complete*

### Actual  Result ###

*The T letter is missing a line on the right side of the letter*

### Screenshots ###

![edge](https://user-images.githubusercontent.com/4928043/36351033-808cc55e-14a3-11e8-9f98-afdf9f41c9ef.PNG)
![ie11](https://user-images.githubusercontent.com/4928043/36351036-8b05e01a-14a3-11e8-8747-212d8350b67c.PNG)

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome 64, IE11, Edge 41.16299.248.0*

**Comment by sdgun** [comment]
Not a Bug, Fluid screens are not supported
