### ISSUE TITLE
Copyright year is 2017 instead of current year

### ISSUE THREAD

**Issue by barranquerox** [topcoderinc/connect-test-cycle-1#213]
### Reported URL ###
https://accounts.topcoder-dev.com/connect
https://accounts.topcoder-dev.com/connect/forgot-password
https://accounts.topcoder-dev.com/connect/registration

### Reproduction Steps ###
1. Open the reported URLs

### Expected Result ###

*Copyright year should be current year 2018*

### Actual  Result ###

*Copyright year is 2017*

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome 64*

**Comment by sdgun** [comment]
#7
