### ISSUE TITLE
User unable to create project without any category

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#216]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/new-project/

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. Click on Add new project or https://connect.topcoder-dev.com/new-project/
3. Observe on this page there is no option to create project without category
4. Select Design
5. then you are on https://connect.topcoder-dev.com/new-project/all-designs page
6.  Observe on this page there is no option to create project without category

### Expected Result ###
As per Spec: Create project (logged in) : User should be able to create a project with no category

### Actual  Result ###
User unable to create project without any category on page 
https://connect.topcoder-dev.com/new-project/
or
https://connect.topcoder-dev.com/new-project/all-designs

*Enter the expected result here.*

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36351615-ba35ebc2-14a4-11e8-8c27-a7ded882d8ac.png)

![image](https://user-images.githubusercontent.com/29735376/36351618-cc7cee02-14a4-11e8-96e0-9cc439640528.png)

### Issue Information ###

Frequency: Always
Device: Desktop
OS: Win 10
Browser: Edge

**Comment by sdgun** [comment]
As per the design, these are the categories they have

**Comment by gargsaurabh86** [comment]
@sdgun As per Spec: Create project (logged in) : User should be able to create a project with no category.
But we are forcing the user to select category !!

Please check.
Regards

**Comment by sdgun** [comment]
@vic-topcoder

**Comment by vic-georgiev** [comment]
I think wording in the document is off. Thanks for reporting!
