### ISSUE TITLE
New page reload suggestion is not triggered for Response Edit

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#219]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2608

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com 
2. Login as pshah_customer
3. Open the project where post has been already created and response was posted
4. Now click on Edit comment against any post
5. Edit the comment and Save change
6. Make sure other team member page is already opened the with same project
7. Now goto other team member/manager page and observe the suggestion for "Reload page to view updates"

### Expected Result ###

As per doc: https://docs.google.com/document/d/1OBUhMGUtqU-Eqpufaom_eAKDbLiR8mq6syb-PSavXDI/edit
Should trigger new page reload suggestion for project members currently on the feed for Response Edit

### Actual  Result ###

Reload page to view updates suggestion is not triggered for response Edit. But if create a new comment then the suggestion is triggered.
Attache the detailed video.

### Screenshots ###

https://youtu.be/D_gvMRjjgm0

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 7 64 bit

Browser: Chrome 64.0

**Comment by sdgun** [comment]
@vic-topcoder

**Comment by vic-georgiev** [comment]
Valid

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1729
