### ISSUE TITLE
Customer first see error immediately post login before coming to projects page

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#221]
### Reported URL ###
*URL where the issue occured, if applicable*

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123
2. And keep observing

### Expected Result ###

Customer is navigated to projects page without seeing Error message

### Actual  Result ###

The customer is navigated to projects page BUT will see the Error message. Please check video

### Screenshots ###

https://youtu.be/1cimwwolggI

### Issue Information ###

Frequency: Mostly
Device: Desktop
OS: Win 10
Browser: Edge

**Comment by sdgun** [comment]
For pshah_customer only

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1727
