### ISSUE TITLE
Filter UI issue in Chrome

### ISSUE THREAD

**Issue by macs054** [topcoderinc/connect-test-cycle-1#223]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc&status=active

### Reproduction Steps ###
Go to https://connect.topcoder-dev.com/ using Chrome
Login as pshah_manager/topcoder123
Click Filter

### Expected Result ###

Filter should be properly positioned

### Actual  Result ###

Filter position is broken

### Screenshots ###

![image](https://user-images.githubusercontent.com/1199534/36352002-d681ace2-14ec-11e8-983e-7fed35cd684f.png)

### Screencast ###

https://youtu.be/H8vyShJMiM8

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome 64.0.3282.140

**Comment by sdgun** [comment]
#227

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1770
