### ISSUE TITLE
Page content is going outside mobile viewport

### ISSUE THREAD

**Issue by Neha-2208** [topcoderinc/connect-test-cycle-1#224]
### Reported URL ###
*https://connect.topcoder-dev.com/new-project/*

### Reproduction Steps ###
1. Go to the url
2. observe the page

### Expected Result ###

*Page should be responsive*

### Actual  Result ###

*Page is not responsive*

### Screenshots ###

*
![image](https://user-images.githubusercontent.com/20572731/36352279-80e2945a-14dc-11e8-849e-33446334319c.png)
*

### Issue Information ###

Frequency: *always*

Device: * mobile- redmi note3, iphone6*

OS: *android*

Browser: *chrome*

**Comment by sdgun** [comment]
Mobile is not in scope
