### ISSUE TITLE
text is going outside the defined space

### ISSUE THREAD

**Issue by Neha-2208** [topcoderinc/connect-test-cycle-1#226]
### Reported URL ###
*https://connect.topcoder-dev.com/new-project/wireframes*

### Reproduction Steps ###
1. Go to the url
2. fill project name ex. 'test'
3. choose screen num and device
4.Now fill the description part, its saying enter min 160 char
5. Notice the project online section, the description you have entered is going outside the box

### Expected Result ###

*Description text should not go outside the box*

### Actual  Result ###

*Description text should is going outside the box*

### Screenshots ###

*
![image](https://user-images.githubusercontent.com/20572731/36352347-a24727ae-14dd-11e8-9007-5ae95c6e0277.png)
*

### Issue Information ###

Frequency: *always*

Device: *Desktop*

OS: *Windows10*

Browser: *Chrome  62.0.3202.94*

**Comment by sdgun** [comment]
Already reported
