### ISSUE TITLE
Overlapping Search for project bar

### ISSUE THREAD

**Issue by InfinityToP** [topcoderinc/connect-test-cycle-1#227]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc&status=active

### Reproduction Steps ###
1. Login as: pat_monahan/topcoder123!
2. In the above URL, Click on Filters near the search bar.

### Expected Result ###
The "search for project" bar isn't being overlapped by the filter bar.

### Actual  Result ###

"The search for project" bar is being overlapped by the filter bar.

### Screenshots ###

![image](https://user-images.githubusercontent.com/32297688/36352372-f3360d4c-14dd-11e8-9ae7-dbba70d9271a.png)

![image](https://user-images.githubusercontent.com/32297688/36352500-fc4f8794-14df-11e8-827d-49225a691ad1.png)

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome Version 64.0.3282.140 (Official Build) (32-bit)*

**Comment by InfinityToP** [comment]
@sdgun Could you please let me know the issue number this issue is duplicate of

**Comment by sdgun** [comment]
#223
