### ISSUE TITLE
Not able to edit Project name and reference code once it is submitted for review

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#228]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2632/specification

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com 
2. Login as pshah_customer
3. Create a new project and submit it for Review
4. Not goto specifications and try to edit the project name and reference code

### Expected Result ###

As per doc: https://docs.google.com/document/d/1OBUhMGUtqU-Eqpufaom_eAKDbLiR8mq6syb-PSavXDI/edit
Project name and reference code can be edited at all states

### Actual  Result ###
Not able to edit Project name and reference code once it is submitted for review

### Screenshots ###
[project name Edit.docx](https://github.com/topcoderinc/connect-test-cycle-1/files/1734761/project.name.Edit.docx)

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 7 64 bit

Browser: Chrome 64.0

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1725
