### ISSUE TITLE
"Filter" bar is not collapsing

### ISSUE THREAD

**Issue by InfinityToP** [topcoderinc/connect-test-cycle-1#229]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc&status=active

### Reproduction Steps ###
1. Login as: pat_monahan/topcoder123!
2. In the above URL, Click on Filters near the search bar.

### Expected Result ###

The "search for project" bar should collapse on clicking other options.

### Actual  Result ###

The "search for project" bar is not collapsing on clicking other options.

### Screenshots ###

![image](https://user-images.githubusercontent.com/32297688/36352372-f3360d4c-14dd-11e8-9ae7-dbba70d9271a.png)

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome Version 64.0.3282.140 (Official Build) (32-bit)*

**Comment by sdgun** [comment]
Clicking on the Filter button will collapse the bar
