### ISSUE TITLE
No Tool-tips present

### ISSUE THREAD

**Issue by InfinityToP** [topcoderinc/connect-test-cycle-1#230]
### Reported URL ###
https://connect.topcoder-dev.com/projects/800

### Reproduction Steps ###
1. Login as: pat_monahan/topcoder123!
2. Click on "Share the Project updates with the team." bar.

### Expected Result ###

Tool tips are present when hovered over styling options.

### Actual  Result ###

Tool tips are not present when hovered over styling options.

### Screenshots ###

![image](https://user-images.githubusercontent.com/32297688/36352540-87955536-14e0-11e8-8b10-86c854d81a21.png)

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome Version 64.0.3282.140 (Official Build) (32-bit)*

**Comment by sdgun** [comment]
No need
