### ISSUE TITLE
Broken "Let's Talk" link

### ISSUE THREAD

**Issue by InfinityToP** [topcoderinc/connect-test-cycle-1#233]
### Reported URL ###
https://connect.topcoder-dev.com/projects/800

### Reproduction Steps ###
1. Login as: pat_monahan/topcoder123!
2. In the above link, Click on "Project in Topcoder Direct" seen to the left of the page.
3. New page opens - https://www.topcoder-dev.com/direct/projectOverview?formData.projectId=10859
4. Scroll down to find "Let's Talk" option in Project Forum section.

### Expected Result ###

"Let's Talk" link isn't broken.

### Actual  Result ###

Broken "Let's Talk" link.

### Screenshots ###

![image](https://user-images.githubusercontent.com/32297688/36352668-78d0887a-14e2-11e8-825d-db0136d1ae1a.png)
Error seen:
![image](https://user-images.githubusercontent.com/32297688/36352672-86ce2c52-14e2-11e8-8cf0-bdb28124f017.png)

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome Version 64.0.3282.140 (Official Build) (32-bit)*

**Comment by sdgun** [comment]
out of scope
