### ISSUE TITLE
"Configure Project Forum" is having erratically behaving "Add More Forums" & "Delete Selected" functionalities.

### ISSUE THREAD

**Issue by InfinityToP** [topcoderinc/connect-test-cycle-1#235]
### Reported URL ###
https://connect.topcoder-dev.com/projects/800

### Reproduction Steps ###
1.Login as: pat_monahan/topcoder123!
2.In the above link, Click on "Project in Topcoder Direct" seen to the left of the page.
3.New page opens - https://www.topcoder-dev.com/direct/projectOverview?formData.projectId=10859
4.Scroll down to find "Configure Project Forum" option in Project Forum section.
5. Click on "Add more Forums" to give random test Forum Name and Description.
6. Click on "Insert" and then try deleting the Inserted forum.

### Expected Result ###

No error message comes or proper message is shown when deleting a newly Inserted forum.

### Actual  Result ###

An error message is shown saying that the form has already been processed when that is the first time the forum is being deleted and when refreshed and checking again the forum is shown deleted. 

### Screenshots ###

![image](https://user-images.githubusercontent.com/32297688/36352871-0e512ae2-14e5-11e8-976e-6c7c20a38b5a.png)

**Screen Recording**
https://youtu.be/NSQq8tArms4

### Issue Information ###

Frequency: *4/5*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome Version 64.0.3282.140 (Official Build) (32-bit)*

**Comment by sdgun** [comment]
out of scope
