### ISSUE TITLE
page spacing is not constant, box is expanding and shrinking

### ISSUE THREAD

**Issue by Neha-2208** [topcoderinc/connect-test-cycle-1#236]
### Reported URL ###
*https://connect.topcoder-dev.com/projects/2636/*

### Reproduction Steps ###
1. go to the url
2. observe the page.
3. now scroll down little, now observe the left box, its shrinking and expanding
4. also observe the space between left and right panes while scrolling up and down
### Expected Result ###

*The page should remain consistent, box should not shrink and expand*

### Actual  Result ###

* box is expanding and shrinking*

### Screenshots ###

*
initially

![image](https://user-images.githubusercontent.com/20572731/36353064-95138eec-14e7-11e8-9f34-29bdacdf7145.png)

after scrolling
![image](https://user-images.githubusercontent.com/20572731/36353075-c779718a-14e7-11e8-88fd-c21d0305a98e.png)

*

### Issue Information ###

Frequency: *always*

Device: *Desktop*

OS: *Windows10*

Browser: *Chrome  62.0.3202.94*

**Comment by sdgun** [comment]
Too trivial
