### ISSUE TITLE
All projects only shows 1 item

### ISSUE THREAD

**Issue by macs054** [topcoderinc/connect-test-cycle-1#238]
### Reported URL ###
https://connect.topcoder-dev.com/projects?keyword=OPO&sort=best%20match

### Reproduction Steps ###
Go to https://connect.topcoder-dev.com/
Login as pshah_manager/topcoder123
Search for 'OPO', or click the REF code of item with id 1356
Click All projects

### Expected Result ###

Should show more than 1 result because there are more results in the other tabs.

### Actual  Result ###

Only 1 item is shown,  also the item with the REF code OPO is not shown.

### Screenshots ###
REF code
![image](https://user-images.githubusercontent.com/1199534/36353200-676f3696-14fe-11e8-9fee-66ac690b6850.png)

Result
![image](https://user-images.githubusercontent.com/1199534/36352913-7e07fb3a-14fa-11e8-85be-b403947703de.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2

**Comment by sdgun** [comment]
Search filter applied to the 'All projects' tab

**Comment by macs054** [comment]
I don't understand, it says 'All projects' so the more reason to show more results. Results from other tabs should show under 'All projects'.
