### ISSUE TITLE
Privacy policy link broken

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#24]
### Reported URL ###
*URL where the issue occured, if applicable*
https://www.topcoder-dev.com/community/how-it-works/privacy-policy/

### Reproduction Steps ###
1. Navigate to https://accounts.topcoder-dev.com/connect/registration
2. Click Privacy Policy

### Expected Result ###

Privacy policy is dispalyed

### Actual  Result ###

Page is broken

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36344313-61fca480-1410-11e8-9d6a-220b6f36f5b0.png)

### Issue Information ###

Frequency: Always

Device: *device used for testing*

OS: *operating system used on test*

Browser: Chrome

**Comment by sdgun** [comment]
Out of Scope, link issue not with the connect app
