### ISSUE TITLE
Window-Manager – Entire Project team members section is getting disabled, While following below steps.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#242]
Summary:
Window-Manager – Entire Project team members section is getting disabled, While following below steps.

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a new project
4.Cick the project – Project should be in dashboard
5.Add teamers as Copilot and Mangers  
6.Now click Remove Copilot button
7. App will throw error message as “You are about to remove a copilot”
10. Without closing above prompt , Post any comment for the project

### Expected Result ###
Window-Manager – Entire Project team members section should not get disabled, While following below steps.
### Actual  Result ###
Window-Manager – Entire Project team members section is getting disabled, While following below steps.

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/h5rMRw2GAc0

**Comment by sdgun** [comment]
#39

**Comment by youdare** [comment]
@sdgun 
Both defects are different(Steps also different) could you please check again

**Comment by youdare** [comment]
@sdgun  Could you please check again, Both defects are different(Steps also different)

Requesting you to see the video i have attached
