### ISSUE TITLE
Window-Manager – Entire Project team members section is getting disabled, if leave “You are about to remove a copilot” prompt ideal for 40 seconds.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#243]
Summary:
Window-Manager – Entire Project team members section is getting disabled, if leave “You are about to remove a copilot” prompt ideal for 40 seconds.

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a new project
4.Cick the project – Project should be in dashboard
5.Add teamers as Copilot and Mangers  
6.Now click Remove Copilot button
7. App will throw error message as “You are about to remove a copilot”
10. Without closing above prompt , Leave it ideal for 40 Seconds
11. Now Click “Cancel” button

### Expected Result ###
Window-Manager – Entire Project team members section should not get disabled, if leave “You are about to remove a copilot” prompt ideal for 40 seconds.
### Actual  Result ###
Window-Manager – Entire Project team members section is getting disabled, if leave “You are about to remove a copilot” prompt ideal for 40 seconds.

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/rpLQ44Cujew

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/39
