### ISSUE TITLE
Window-Manager – Getting alert message as “Project  created”, While creating App project, But actually project is not created.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#245]
Summary:
Window-Manager – Getting alert message as “Project  created”, While creating App project, But actually project is not created.

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a new project
4.Enter project name as “Which is your primary device      <Mobile>” (With space as mentioned)
5.Fill the remaining field 
6.Click “Continue” button

### Expected Result ###
Window-Manager – Should throw some valid error message 
### Actual  Result ###
Window-Manager – Getting alert message as “Project  created”, While creating App project, But actually project is not created.

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/8ikXLuSPoHQ

Step 4: Step please see video ,git hub not accepting the input what iam giving

**Comment by sdgun** [comment]
The project is created successfully. Can't reproduce the bug using the provided steps and details

**Comment by youdare** [comment]
@sdgun  Able to reproduce this issue multiple Time , As i mentioned Step 4 git-hub is not showing the given input, iam pasting step 4 screen shot here, it will be help full to reproduce.(Attached detail video already )

![image](https://user-images.githubusercontent.com/31862600/36487370-b473a202-1746-11e8-8576-8ea24b682594.png)

@sdgun  in step four we have 2 space before <mobile>

**Comment by sdgun** [comment]
Still I can create the project https://www.screencast.com/t/6kd29udbLG

**Comment by youdare** [comment]
@sdgun Dont know why its happening to me , Thanks for update 

iam taking your points i dont want to appeal any more on this .Thanks
