### ISSUE TITLE
Window-Manager – Filter is shown when we log in and log out

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#246]
Summary:
Window-Manager – Filter is shown when we log in and log out

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Click Filter button
4.Click Click Logout
5.Again log in to app

### Expected Result ###
Window-Manager – Filter should not show when we log in and log out
### Actual  Result ###
Window-Manager – Filter is shown when we log in and log out

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/CX6QEas2-HA

**Comment by youdare** [comment]
@sdgun Attached video in comment section it is reproducible, Just now tried

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1719
