### ISSUE TITLE
Manger  unable to update status 

### ISSUE THREAD

**Issue by karthikbecse** [topcoderinc/connect-test-cycle-1#248]
### Reported URL ###
https://connect.topcoder-dev.com/projects

### Reproduction Steps ###
1. Goto https://connect.topcoder-dev.com
2. Login as pshah_manager
3.see project "Tony 7"
4.Change status of the project Pasued to active
5.observe

### Expected Result ###
Should update properly

### Actual  Result ###
Error message appered "Please add a name for your project and then try saving again."

### Screenshots ###

*Paste screenshots here.*

### Issue Information ###

Frequency: *frequentlys*

Device: Laptop

OS: Windows 8.1
Browser:  FF58.0.2

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/21
