### ISSUE TITLE
Window-Manager – File Icon or Logo is getting disappeared and Appeared again while Delete-> Cancel button after the file upload 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#251]
Summary:
Window-Manager – File Icon or Logo is getting disappeared and Appeared again while Delete-> Cancel button after the file upload 

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create the project.
4.Go To Project specification
5.Click File and upload 3 or 4 File
6.Click Delete button
7. App will display message as “You're about to delete the file” with Cancel and Delete File button
8.Cancel button

### Expected Result ###
Window-Manager – File Icon or Logo should not get disappeared and Appeared again while Delete-> Cancel button after the file upload 
### Actual  Result ###
Window-Manager – File Icon or Logo is getting disappeared and Appeared again while Delete-> Cancel button after the file upload 

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/SZoXHJS0aSA

**Comment by sdgun** [comment]
Trivial issue
