### ISSUE TITLE
Show extended list of more managers is not shown for listing of managers

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#252]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc&status=active

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com 
2. Login as pshah_manager
3. Add 8 manager to a project
4. Now observe the listing of managers in the dashboard

### Expected Result ###

As per doc: https://docs.google.com/document/d/1OBUhMGUtqU-Eqpufaom_eAKDbLiR8mq6syb-PSavXDI/edit
•	Correct listing of managers (none, 1, 2, 3, 4+)
o	Tooltips
o	Show extended list of more managers

### Actual  Result ###

Show extended list of more mangers is not shown even though after adding 8 managers to a project.

### Screenshots ###
![image](https://user-images.githubusercontent.com/31851673/36354538-0c8ed798-14ce-11e8-9714-3bb44230f9e4.png)

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 7 64 bit

Browser: Chrome 64.0

**Comment by sdgun** [comment]
Listing is correct
