### ISSUE TITLE
Window-Manager – File Upload Retry Button is not displayed if we try to upload two different file format. 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#253]
Summary:
Window-Manager – File Upload Retry Button is not displayed if we try to upload two different file format. 

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create the project.
4.Go To Project specification
5.Click File and upload Two different format -MP4 and Text File
6.During upload click “Cancel” button

### Expected Result ###
Window-Manager – File Upload Retry Button should be displayed if we try to upload two different file format. 
### Actual  Result ###
Window-Manager – File Upload Retry Button is not displayed if we try to upload two different file format. 

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/MB0FCns9Bbs

**Comment by sdgun** [comment]
File upload widget is a third-party tool not related to connect app
