### ISSUE TITLE
Manager: Save changes button enabled even though there is no changes in that section

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#254]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc&status=active

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com 
2. Login as pshah_manager
3. Open the App project
4. Goto Specification tab
5. Edit the comment in the design specification section
6. Observe save changes buttons enabled for all the sections without any changes

### Expected Result ###

Save changes button should enable only for the section where changes are made.

### Actual  Result ###

Save changes button enabled for all the sections where there is no changes also.

### Screenshots ###

https://youtu.be/h4DW3z3rrLA

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 7 64 bit

Browser: Chrome 64.0

**Comment by sdgun** [comment]
Save changes button should enable only for the section where changes are made. > No, All the Save button as enabled as per the design
