### ISSUE TITLE
Window-Manager – In specification page, When we drag and drop a file to upload, Application is not showing option to Cancel and Uploaded message to user. 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#255]
Summary:
Window-Manager – In specification page, When we drag and drop a file to upload, Application is not showing option to Cancel and Uploaded message to user. 

Note:-USer will not get any message when uploaded is completed 

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create the project.
4.Go To Project specification
5.Scroll down and go to Upload file section
6.Drag and Drop a file 

### Expected Result ###
Window-Manager – In specification page, When we drag and drop a file to upload, Application should show option to Cancel and Uploaded message to user. 
### Actual  Result ###
Window-Manager – In specification page, When we drag and drop a file to upload, Application is not showing option to Cancel and Uploaded message to user. 

 ### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36354884-af837d6e-1500-11e8-9f52-3a2bc40a11ab.png)
![image](https://user-images.githubusercontent.com/31862600/36354885-b9c749ea-1500-11e8-8070-e11d5e2559aa.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
Not a Bug
