### ISSUE TITLE
Manager: Save changes button is not enabled if we only uploads a file

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#256]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc&status=active

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com 
2. Login as pshah_manager
3. Open a project and goto specifications tab
4. Now add a file by drag and drop
5. Once the file is added then observe the Save changes button

### Expected Result ###

Save changes button should enable even if we adds only files also.

### Actual  Result ###

Save changes button is not enabled if we adds only files. But it is enabled if we edit any other fields along with file upload.

### Screenshots ###
Save changes button before adding the file:
![image](https://user-images.githubusercontent.com/31851673/36354950-bfe6db1a-14d3-11e8-8208-2155c0d7bdda.png)
Now add a file and observe still the button is not enabled.
![image](https://user-images.githubusercontent.com/31851673/36354973-e3f7c050-14d3-11e8-947a-58a9f601da37.png)

https://youtu.be/ZAYyB9eYvIU

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 7 64 bit

Browser: Chrome 64.0

**Comment by sdgun** [comment]
By looking at the screenshot you are missing 1 required enter in the question section. I can see 8 of 9

https://user-images.githubusercontent.com/31851673/36354950-bfe6db1a-14d3-11e8-8208-2155c0d7bdda.png
