### ISSUE TITLE
Window-Manager –In How precise is your budget? section – we are able to select option button by clicking on lines

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#257]
Summary:
Window-Manager –In How precise is your budget? section – we are able to select option button by clicking on lines

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create the project.
4.Go To Project specification
5.Scroll down and go to In How precise is your budget? section
6.Clik on the lines 

### Expected Result ###
Window-Manager –In How precise is your budget? section – Should not allow to select option button by clicking on lines
### Actual  Result ###
Window-Manager –In How precise is your budget? section – we are able to select option button by clicking on lines

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/bptDDV5N6CM

**Comment by sdgun** [comment]
Not a Bug
