### ISSUE TITLE
user has to select the username from the modal to enable the Add button

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#26]
### Reported URL ###
*https://connect.topcoder-dev.com/projects/2499/*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123
2. create a new project (id is 2499)
3. then go to https://connect.topcoder-dev.com/projects/2499/
4. on the left side, enter "pshah_copilot", observe the Add button

### Expected Result ###

*The Add button should be enabled if entered username is valid.*

### Actual Result ###

*See screenshot, user has to click the username in the dropdown to enable the Add button.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="386" alt="add" src="https://user-images.githubusercontent.com/4590317/36344384-8e35e9d2-1454-11e8-94d3-1516099306a9.png">

**Comment by sdgun** [comment]
You must select the 'pshah_copilot' from the drop down to enable 'Add' button
