### ISSUE TITLE
Customer able to make admin as owner

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#260]
### Reported URL ###
*URL where the issue occured, if applicable*

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123
2. Navigate to Any project and add pat_monahan as member
3. try to make pat_monahan as owner

### Expected Result ###

As per specs: Member management : Managers, Copilots, **Admins** can’t be project owners

### Actual  Result ###

Customer is able to make Admin as owner

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36355135-908c609e-14d6-11e8-8931-813584899c1a.png)

### Issue Information ###

Frequency: Always
Device: Desktop
OS: Windows 10
Browser: Edge

**Comment by sdgun** [comment]
Manager, copilot and customer phrase in the username is used to identify the roles. Any user can become copilot, manager etc...
