### ISSUE TITLE
Admin is able to delete owner

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#261]
### Reported URL ###
*URL where the issue occured, if applicable*

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123
2. Navigate to Any project and add member to project
3. Now promote the same member as owner
4. Log out
5.Login to https://connect.topcoder-dev.com/ using pat_monahan/topcoder123
6. Navigate to the same project
7. Try to delete member which is an owner as well 

### Expected Result ###

Admin should not be allowed to delete owner of the project

### Actual  Result ###

Admin is allowed to delete owner of the project

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36355213-01d624fa-14d8-11e8-8075-9ff52fce740b.png)
![image](https://user-images.githubusercontent.com/29735376/36355221-1c2aef34-14d8-11e8-8d9c-41853234d4c3.png)

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: *browser and version used on test*

**Comment by sdgun** [comment]
Expected behaviour
