### ISSUE TITLE
Admin user not able to leave project

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#262]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2613

### Reproduction Steps ###
1.Login to https://connect.topcoder-dev.com/ using pat_monahan/topcoder123
2. Navigate to the project where pat_monahan has joined or  if not join him in project
3. Try to leave pat_monahan from the project

### Expected Result ###

Pat_monahan is able to leave the project

### Actual  Result ###

Pat_monahan is unable to leave the project. Keep waiting on the same page for around 30second you will see the error on page. Or if you decide to refresh page thinking that no action is taken then you will again see pat_monahan there in project and no action occurred
### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36355297-f311865c-14d8-11e8-98a3-2831ef2e3f3c.png)

### Issue Information ###

Frequency: Always
Device: Desktop
OS: Windows 10
Browser: Edge

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/15
