### ISSUE TITLE
No alert message shown while navigating to add member in middle of the post

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#263]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2652

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com 
2. Login as pshah_manager
3. Open the project and try to create a new post but don't post it
4. Now click in + icon to add a new team member
5. observe for no alert message

### Expected Result ###

As per doc: https://docs.google.com/document/d/1OBUhMGUtqU-Eqpufaom_eAKDbLiR8mq6syb-PSavXDI/edit
o	Alert when navigating away without posting

### Actual  Result ###

No alert message shown while navigating to add member in middle of the post.

### Screenshots ###
https://youtu.be/ZwoSWrXqdhk

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 7 64 bit

Browser: Chrome 64.0

**Comment by sdgun** [comment]
![2018-02-22_11-16-15](https://user-images.githubusercontent.com/4592712/36553417-d63859fc-17c1-11e8-8140-913f22f0d2be.jpg)
