### ISSUE TITLE
Colour adjust bar is not movable in specification tabe

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#264]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2652/specification

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com 
2. Login as pshah_customer
3. Open the app project goto specification tab
4. click on + under What colors do you like? (Select all that apply)
5. Colour window will open
6. Now try adjust second colour bar

### Expected Result ###

Both colour bar should be movable

### Actual  Result ###
Second colour bar is not moving to adjust the colour.

### Screenshots ###
![image](https://user-images.githubusercontent.com/31851673/36355413-b71de116-14da-11e8-9eb8-dc6740355866.png)

https://youtu.be/QtojSNhAopw

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 7 64 bit

Browser: Chrome 64.0

**Comment by sdgun** [comment]
Not a Bug
