### ISSUE TITLE
Able to save the project while add colour window is opened

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#266]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2652/specification

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com 
2. Login as pshah_customer
3. Open the App project, goto the specification tab
4. Click on + icon for What colors do you like? (Select all that apply) under design specification section
5. Add 1 colour then save changes button enabled
6. Now don't close the colour popup window and click on save changes button
7. observe

### Expected Result ###

Should not allow to save changes until the colour windows are closed.

### Actual  Result ###

Able to save the project while add colour popup window is opened.

### Screenshots ###

https://youtu.be/GEtJXtlCJbE

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 7 64 bit

Browser: Chrome 64.0

**Comment by sdgun** [comment]
If the color is the last item to select in that section, selecting a color won't enable the Save button (in video you have deleted a selected color) so if this is the last step anyway button is enabled

Selected color won't get saved without pressing the add button. So clicking on Save button while the popup is opened won't do any harm. No issue
