### ISSUE TITLE
No edit option for 1st post in discussion

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#267]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/665/discussions/2432

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123
2. Navigate to Discussion like https://connect.topcoder-dev.com/projects/665/discussions/
3. Create a new discussion
4. Post on that discussion 2-3 replies
5. You will see edit option against all replies 
6. Observe Chat post 

### Expected Result ###

Edit option should appear in 1st reply/post as well

### Actual  Result ###

Edit option does not appear in 1st reply/post 

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36355574-23580472-14dd-11e8-91e7-437ef24fdefa.png)

### Issue Information ###

Frequency: Always
Device: Desktop
OS: Windows 10
Browser: Edge

**Comment by sdgun** [comment]
Can be seen in few more instances

https://connect.topcoder-dev.com/projects/800/discussions/2267
https://connect.topcoder-dev.com/projects/800/discussions/2265

But for some of the items, edit button is there

https://connect.topcoder-dev.com/projects/800/discussions/2106
https://connect.topcoder-dev.com/projects/800/discussions/2076

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1772
