### ISSUE TITLE
Error for maximum messages in day appearing in discussion

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#268]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/665/discussions/

### Reproduction Steps ###

1. Login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123
2. Navigate to Discussion like https://connect.topcoder-dev.com/projects/665/discussions/
3. Create a new discussion topic.
4. Enter topic and  Enter post and then Click Post Button
4. Observe 
### Expected Result ###

As per specs:  There is no maximum limit on creating the new discussion
### Actual  Result ###

Sometimes error when trying to post new discussion topic.

### Screenshots ###
![image](https://user-images.githubusercontent.com/29735376/36355594-772ef5b0-14dd-11e8-990f-bdd3346ba9dc.png)

*Paste screenshots here.*

### Issue Information ###

Frequency: Intermittent 
Device: Desktop
OS: Windows 10
Browser: Edge

**Comment by sdgun** [comment]
After 19min you can post another
