### ISSUE TITLE
Error for maximum messages in day appearing on Project Dashboard page

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#269]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2560

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123
2. Navigate to **Project dashboard** page like https://connect.topcoder-dev.com/projects/2560
3. Start Typing in **Share the latest update with the team**
4. Enter topic and Enter post and then Click Post Button
5. Observe

### Expected Result ###

As per specs: There is no maximum limit on creating the new post.

### Actual  Result ###

Sometimes error when trying to post on Project dashboard page.

### Screenshots ###

![image](https://user-images.githubusercontent.com/29735376/36355700-045eeaac-14df-11e8-9892-2822339081af.png)

### Issue Information ###

Frequency: Always
Device: Desktop
OS: Windows 10
Browser: Edge

**Comment by sdgun** [comment]
This is mot max post per day, System is slowing down the commenting by applying a waiting time in between comments
