### ISSUE TITLE
Reset pwd page system error

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#27]
### Reported URL ###
*URL where the issue occured, if applicable*
https://accounts.topcoder-dev.com/connect/forgot-password

### Reproduction Steps ###
1. Navigate to https://accounts.topcoder-dev.com/connect/forgot-password
2. Enter in email as xhjshjjhdshjsdjhsdtest@test.com

### Expected Result ###

*Enter the expected result here.*
Error should not say system error but may be email not found.

### Actual  Result ###

*Enter the expected result here.*

We weren't able to send a reset link because of a system error. Please try again or contact support@topcoder.com.

### Screenshots ###

*Paste screenshots here.*
![Uploading image.png…]()

### Issue Information ###

Frequency: Always

Device: *device used for testing*

OS: *operating system used on test*

Browser: All

**Comment by sdgun** [comment]
Marked as a Placeholder

**Comment by sdgun** [comment]
Not an Issue
