### ISSUE TITLE
Filters not working when adding new project team

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#272]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/1459

### Reproduction Steps ###
1. Login to application using pshah_manager / topcoder123
2. Navigate to any project  like https://connect.topcoder-dev.com/projects/1459
3. Add new team member
4. Select 'Member' filter
5. search for co-pilot or Manager like pshah_copilot or pshah_manager

### Expected Result ###

Only Members should show in the dropdown and user should not be able to select pshah_copilot or pshah_manager

### Actual  Result ###

Even after selecting Member filter user can search pshah_copilot or pshah_manager.
vice versa after selecting co-pilot as filter user is able to search member and manager
similarly after selecting manager as filter user is able to select copilot and member

### Screenshots ###

*Paste screenshots here.*

![image](https://user-images.githubusercontent.com/29735376/36357773-c8a623ce-14fa-11e8-9c8b-540638056aa5.png)

![image](https://user-images.githubusercontent.com/29735376/36357785-eba62860-14fa-11e8-965a-63fa13df2c23.png)

Frequency:Always

Device: Desktop

OS: Windows 10

Browser: Edge

**Comment by sdgun** [comment]
pshah_copilot or pshah_manager also normal users. Any user can assign as a manager or copilot
