### ISSUE TITLE
Admin can add customer as copilot

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#274]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/1459

### Reproduction Steps ###
1. Login as pat_monahan / topcoder123!
2 Navigate to any project say https://connect.topcoder-dev.com/projects/1459
3. if pshah_customer is already added please remove it and refresh the page to check it has been removed
4. Now click + to add a new team member
5. select copilot filter
6. Search for pshah_customer
7. Click Add and refresh the page

### Expected Result ###

pshah_customer should not be added as copilot

### Actual  Result ###

Admin can add customer pshah_customer as copilot.

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36358128-f24e9098-1500-11e8-924d-406b5f727a40.png)

### Issue Information ###

Frequency:Always

Device: Desktop

OS: Windows 10

Browser: Firefox

**Comment by sdgun** [comment]
pshah_customer is a normal user; so adding him using copilot tab will add him as a copilot
