### ISSUE TITLE
Correct listing of managers not shown in Card view

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#275]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc

### Reproduction Steps ###
1. Login as customer pshah_customer/ topcoder123
2. observe a project with more than 3 managers added to it. 
3. observe manager listings shown

### Expected Result ###

Correct listing of managers (none, 1, 2, 3, 4+)

### Actual  Result ###

Issue 1. Full team are shown including copilot, members and managers
Issue 2. team listing shown as (1, 2, 3, 4,5, 6, 7, 8, 9, 10, 11+)
Issue 3. First three avatars are overlapping slightly while others are not.

### Screenshots ###

![image](https://user-images.githubusercontent.com/29735376/36358604-e1c5ee8a-1508-11e8-8771-90dba3732659.png)

### Issue Information ###

Frequency:Always

Device: Desktop

OS: Windows 10

Browser: Chrome

**Comment by sdgun** [comment]
I can't see any bug here

**Comment by gargsaurabh86** [comment]
@sdgun do you mean in card view above mentioned issues are expected behavior?

Thanks.

**Comment by sdgun** [comment]
Yes
