### ISSUE TITLE
Direct project is created when the project is in draft

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#277]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2666

### Reproduction Steps ###
1. Login as manager pshah_manager / topcoder123
2. create a new design- visual design project by clicking on + button
3. Provide all valid details and continue
4. Project is created
5. observe integration links

### Expected Result ###

As per specs: Project integrations -> Direct project is created when the project goes into Active status
OR Project status -> Project should create corresponding Direct project when goes into Active status

### Actual  Result ###

Direct project is created even when the project is in draft status

### Screenshots ###

![image](https://user-images.githubusercontent.com/29735376/36358756-6ab254ac-150b-11e8-9488-bf1bb36df628.png)

### Issue Information ###

Frequency:Always

Device: Desktop

OS: Windows 10

Browser: Edge

**Comment by sdgun** [comment]
Check comment on #415
