### ISSUE TITLE
No Dismisss all link present for notification

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#278]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer / topcoder123
2. Click on Bell icon
3 Observe

### Expected Result ###

As per specs: Notification: Dismiss all link/button should be present

### Actual  Result ###
No **Dismiss all** link present for notification

### Screenshots ###
![image](https://user-images.githubusercontent.com/29735376/36358916-53d3e17c-150d-11e8-9fc9-6dd1c8eb0d7f.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome

**Comment by gargsaurabh86** [comment]
Dismiss all is also not present on Notification center:
![notification center](https://user-images.githubusercontent.com/29735376/36359005-8006fac6-150e-11e8-9530-44dc6f494c4f.png)

**Comment by sdgun** [comment]
Dismisss all = Mark all as read
