### ISSUE TITLE
Added person doesnt show up immediately. PAge needs to be refreshed to see the added person to the project

### ISSUE THREAD

**Issue by kaygee1** [topcoderinc/connect-test-cycle-1#28]
Open https://connect.topcoder-dev.com/
Login as pshah_manager/topcoder123

Create a new project - App project

Now in the project dashboard try to add ppl to it.
Click on + and add a copilot
Select a copilot and click add

Observe

actual - nothing happens
REfresh the page and then the new copilot gets added

expected
It should be done immediately and displayed on the screen

Frequency - always
Desktop
OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2

![7](https://user-images.githubusercontent.com/5115050/36344427-0ccdabe6-1440-11e8-9c96-6eaa398e7f4b.png)

**Comment by sdgun** [comment]
I can see the added item on the list real-time
