### ISSUE TITLE
Window-Manager – Clear filter button is getting vanished when we enter long text filter, Filter should be a dropdown selective it should not treat like Input box

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#280]
Summary:
Window-Manager – Clear filter button is getting vanished when we enter long text filter, Filter should be a dropdown selective it should not treat like Input box

Note: Please limit the Filter text box 

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Click Filter button
4.Enter long text in filter box
## Expected Result ###
Window-Manager – Clear filter button should not get vanished when we enter long text filter 
### Actual  Result ###
Window-Manager – Clear filter button is getting vanished when we enter long text filter, Filter should be a dropdown selective it should not treat like Text Input box

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/g2qlY43Y13s

**Comment by youdare** [comment]
https://youtu.be/g2qlY43Y13s

**Comment by sdgun** [comment]
No such long text is entered by a typical user
