### ISSUE TITLE
Wording/typo issue on Notification center

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#281]
### Reported URL ###
https://connect.topcoder-dev.com/notifications

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer / topcoder123
2. Click on Bell icon
3 Click View all notifications
4. Now you are on Notification center

### Expected Result ###

The option should say Mark All as read

### Actual  Result ###

The option is Mark All

### Screenshots ###

![notification center-markall](https://user-images.githubusercontent.com/29735376/36359071-394db52e-150f-11e8-8f08-53e0a018604a.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome

**Comment by sdgun** [comment]
As per the design
