### ISSUE TITLE
Window-Manager – Incorrect logic In Filter -Predictive drop-down suggestion is wrong for Software development.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#282]
Summary:
Window-Manager – Incorrect logic In Filter -Predictive drop-down suggestion is wrong for Software development.

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Click Filter button
4.Enter text as “App” and Select “App” from Dropdown
5.Again Enter text as “App” and observe the suggestion
## Expected Result ###
In Filter -Predictive dropdown suggestion should be correct Software development.

### Actual  Result ###
In Filter -Predictive dropdown suggestion is wrong for Software development.

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/_AasSu3HFU8

**Comment by sdgun** [comment]
No an issue, as per the design
