### ISSUE TITLE
Inconsistent behaviour for Customer in card view

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#287]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc

### Reproduction Steps ###
Login to https://connect.topcoder-dev.com/ using pshah_customer / topcoder123
Observe current project statuses of different projects

### Expected Result ###

Customer should either be allowed or not allowed to **change** Project status from Cards but it should be consistent across all cards

### Actual  Result ###

The customer was allowed to change Project status for some projects and not for others. Even when 2 different projects have the same status

### Screenshots ###

![image](https://user-images.githubusercontent.com/29735376/36359600-d54ce6d4-1514-11e8-89c3-cee35add9b62.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Edge

**Comment by sdgun** [comment]
![2018-02-22_10-33-15](https://user-images.githubusercontent.com/4592712/36550828-d6177ec2-17bb-11e8-890f-6405495caccf.jpg)

**Comment by gargsaurabh86** [comment]
@sdgun as mentioned this is inconsistent.
Not sure if you would like to re-review and consider it.
Thank you.

**Comment by sdgun** [comment]
If this can't reproduce now, can't accept as a valid issue, but you have mentioned  **Frequency: Always**

**Comment by gargsaurabh86** [comment]
Sorry I added inconsistent in title then missed updating frequency.
