### ISSUE TITLE
User unable to search project using ref code

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#289]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects

### Reproduction Steps ###
1. Login as manager
2. Create a new project with ref code as abc
3. Once Project is created
4. Enter abc in search 

### Expected Result ###

User is able to search new project via ref code and if its unique then it should be 1st result

### Actual  Result ###

Its very difficult for user to search using exact ref code as well

### Screenshots ###

![image](https://user-images.githubusercontent.com/29735376/36359883-1a91e4d6-1517-11e8-8214-43b55290a513.png)
![image](https://user-images.githubusercontent.com/29735376/36359892-2b7d2012-1517-11e8-9615-1d9467f613c9.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Edge

**Comment by sdgun** [comment]
Not required
