### ISSUE TITLE
Payments page, items missing

### ISSUE THREAD

**Issue by wgitk** [topcoderinc/connect-test-cycle-1#290]
### Reported URL ###
https://community.topcoder-dev.com

### Reproduction Steps ###
1. Log in with username as **pshah_customer** and password as **topcoder123**
2. Notice user name and accompanied avatar image
3. Hover on username or avatar and select "Payments" option
4. Header is missing the COMMUNITY list and the user avatar is replace by text

### Expected Result ###
The user avatar and community link must be displayed, in addition to any content/details (considering the live top coder site)

### Actual  Result ###
Community link was missing and the avatar image uploaded for the user was replaced with text. There was no page content on payment or the usual message that says "No Payments found"

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/36453494/36361667-75637bbe-14f3-11e8-895b-e87b9b0a5f11.png)

![image](https://user-images.githubusercontent.com/36453494/36361736-22a93b38-14f4-11e8-93d6-8922d6dcd703.png)

Smaller Screen
![image](https://user-images.githubusercontent.com/36453494/36361784-83784094-14f4-11e8-9ede-6149e8c87a3d.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Firefox 58.0.2

**Comment by sdgun** [comment]
Out of scope. This is not related to the topcoder connect app or edit profile section
