### ISSUE TITLE
Status update from reviewed to active: returns error message

### ISSUE THREAD

**Issue by wgitk** [topcoderinc/connect-test-cycle-1#291]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2673

### Reproduction Steps ###
1. Log in as pshah_copilot with password topcoder123
2. Select ALL PROJECTS from navbar
3. Click on Trial Project 1, which is the project name
4. Click on the dropdown that indicates "Project is reviewed"
5. Select "Active" to update project status
6. Error message reads: "Please add name for your project and then try saving"

### Expected Result ###

Project status must be update to ACTIVE once the project copilot makes the change

### Actual  Result ###

Project status is not updated and the error message does not seem logical, for we have assigned the project name already.

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/36453494/36362766-468e4878-14fd-11e8-8bbb-a4d12382c5b1.png)

### Issue Information ###

Frequency: Repeatable

Device: Desktop

OS: Windows 10

Browser: Firefox 58.0.2

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/21
