### ISSUE TITLE
Project manager : Update from Complete to Active displays error

### ISSUE THREAD

**Issue by wgitk** [topcoderinc/connect-test-cycle-1#292]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc

### Reproduction Steps ###
1.  Log in as pshah_manager with password topcoder123
2.  Select ALL PROJECTS from navbar
3.  For the project Trial Project 1, try to update status from COMPLETED to ACTIVE
4.  Error message reads: "Please add name for your project and then try saving"

Expected Result

Project status must be update to ACTIVE once the project copilot makes the change
Actual Result

Project status is not updated and the error message does not seem logical, for we have assigned the project name already.
Screenshots

Paste screenshots here.
image
Issue Information

Frequency: Repeatable

Device: Desktop

OS: Windows 10

Browser: 

### Expected Result ###
Seems like every project manager has the ability to update project status from complete to active at anytime. So this updated must have processed, and Trial Project 1 must have updated to an active project.

### Actual  Result ###

The project status was never updated and the error reads that the project name must be entered before saving which is mostly the wrong message.

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/36453494/36362983-dc37cc36-14fe-11e8-9cf4-993294a1e010.png)

### Issue Information ###

Frequency:  Always

Device: Desktop

OS: Windows 10

Browser: Firefox 58.0.2

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/21
