### ISSUE TITLE
canceled should be cancelled for consistency

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#293]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/2669*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. create a project, then cancel it
3. go to project dashboard: https://connect.topcoder-dev.com/projects/2669, observe

### Expected Result ###

*canceled should be cancelled for consistency.*

### Actual Result ###

*See screenshot.*

### Screenshots ###

<img width="1215" alt="cancel" src="https://user-images.githubusercontent.com/4590317/36364125-2421f0f2-157d-11e8-9d8d-797b0afe12b7.png">

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by sdgun** [comment]
@vic-topcoder

**Comment by vic-georgiev** [comment]
Yes, valid, should be "Canceled" - US English

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1776
