### ISSUE TITLE
should not show multiple successful modals

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#294]
### Reported URL ###

*https://connect.topcoder-dev.com/settings/notifications*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. go to https://connect.topcoder-dev.com/settings/notifications
3. repeatedly click Save settings when the button is enabled, observe

### Expected Result ###

*Should not show multiple successful modals if clicking repeatedly.*

### Actual Result ###

*See screenshot.*

### Screenshots ###

<img width="1425" alt="setting" src="https://user-images.githubusercontent.com/4590317/36364634-2d6c5c08-1580-11e8-827f-2ae0550d8e45.png">

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by sdgun** [comment]
#88
