### ISSUE TITLE
Validation not complete , budget accepts letter "e"

### ISSUE THREAD

**Issue by InfinityToP** [topcoderinc/connect-test-cycle-1#298]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2652/specification

### Reproduction Steps ###
1. Login as: pat_monahan/topcoder123!
2. Scroll down to What is your project budget?
3. The box accepts "e" as the budget.

### Expected Result ###

The should only accept numerical values.

### Actual  Result ###

The letter "e" is accepted

### Screenshots ###

![image](https://user-images.githubusercontent.com/32297688/36365857-61e88bfa-1571-11e8-9e53-2fadafece20f.png)

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome Version 64.0.3282.140 (Official Build) (32-bit)*

**Comment by sdgun** [comment]
Validation displayed: 
![2018-02-22_8-51-17](https://user-images.githubusercontent.com/4592712/36545047-95ea4ea0-17ad-11e8-9903-03a7ba6c7a02.jpg)
