### ISSUE TITLE
Removing  a user from the project doesnt show up immediately

### ISSUE THREAD

**Issue by kaygee1** [topcoderinc/connect-test-cycle-1#30]
Open https://connect.topcoder-dev.com/
Login as pshah_manager/topcoder123

Create a new project - App project

Now in the project dashboard try to add ppl to it.
Click on + and add a copilot
Select a copilot and click add

Now select that copilot and then click on remove and observe

actual - the copilot still is present in the list

we need to refresh the page to see him deleted
Frequency - always
Desktop
OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2

![8](https://user-images.githubusercontent.com/5115050/36344445-6b4ff138-1440-11e8-9abb-17fca133f7b8.png)

**Comment by sdgun** [comment]
Tested on: Chrome 64.0.3282.140 | Comment: Added user will remove immediately
