### ISSUE TITLE
Tooltip giving strange name 

### ISSUE THREAD

**Issue by InfinityToP** [topcoderinc/connect-test-cycle-1#300]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2652/specification

### Reproduction Steps ###
1. Login as: pat_monahan/topcoder123!
2. Scroll down "Feature requirements".
3. A new page(Project features) opens ,Scroll down and click on add a custom feature, give a name and click on save feature .
4.Observe the tool tips by hovering over the trash icons

### Expected Result ###

The tool tips should give a correct description

### Actual  Result ###

The tool tips give description like "Icon UI trash Simple" and "Icon UI pencil"
### Screenshots ###

![image](https://user-images.githubusercontent.com/32297688/36366821-d535f49a-1575-11e8-9b39-bb2b0b47bf04.png)

![image](https://user-images.githubusercontent.com/32297688/36366897-3cc28ea2-1576-11e8-956c-011d2d608233.png)

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome Version 64.0.3282.140 (Official Build) (32-bit)*

**Comment by sdgun** [comment]
Same section, duplicate with https://github.com/topcoderinc/connect-test-cycle-1/issues/299
