### ISSUE TITLE
Strange Delete option functionality in Project files

### ISSUE THREAD

**Issue by InfinityToP** [topcoderinc/connect-test-cycle-1#301]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2677/specification

### Reproduction Steps ###
1. Login as: pshah_copilot/topcoder123
2. Go to the above URL, Scroll down to Project Files"
3. Upload any random file.
4. Try deleting the file immediately, it works and get's deleted.
5. Try deleting the file after sometime on the page, It shows "Record not found" error, then have to refresh the page and delete again.

### Expected Result ###

The file should get deleted when clicked on delete, no error message. 

### Actual  Result ###

No error message should be shown saying the record not found, when the file is still shown on the page in uploaded list. 

### Screenshots ###

**Screen Recording**
[Delete option functonality.zip](https://github.com/topcoderinc/connect-test-cycle-1/files/1735863/Delete.option.functonality.zip)

### Issue Information ###

Frequency: *4/5*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome Version 64.0.3282.140 (Official Build) (32-bit)*

**Comment by sdgun** [comment]
I think someone has deleted it while you are performing the delete action. I can't reproduce it on my side.
