### ISSUE TITLE
No heading present for "Questions"

### ISSUE THREAD

**Issue by InfinityToP** [topcoderinc/connect-test-cycle-1#302]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2677/specification

### Reproduction Steps ###
1. Login as: pshah_copilot/topcoder123
2. Go to the above URL and in the left Navigation tabs labels, Click on "Questions".

### Expected Result ###

The heading "Questions" is present in the page, as headings are present for all other navigations -Project Name, Notes, Testing Needs, Scope, Tester Details etc.

### Actual  Result ###

No heading for Questions is present which is a bit confusing for the user.

### Screenshots ###

![image](https://user-images.githubusercontent.com/32297688/36367349-4e705600-1578-11e8-8526-5e2bc5b0003c.png)

But No heading for questions:
![image](https://user-images.githubusercontent.com/32297688/36367694-e7fa76ce-1579-11e8-9342-928a91b8909e.png)

![image](https://user-images.githubusercontent.com/32297688/36367384-7508a998-1578-11e8-9a33-8fb003bc50e4.png)
![image](https://user-images.githubusercontent.com/32297688/36367459-baab5f68-1578-11e8-97d4-e12a6ae22c76.png)

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome Version 64.0.3282.140 (Official Build) (32-bit)*

**Comment by sdgun** [comment]
Not a Bug
