### ISSUE TITLE
No save changes option after uploading file

### ISSUE THREAD

**Issue by InfinityToP** [topcoderinc/connect-test-cycle-1#303]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2677/specification

### Reproduction Steps ###
1.Login as: pshah_copilot/topcoder123
2.Go to the above URL.
3.Scroll down to the bottom, to Project files, Upload a file.
### Expected Result ###

"Save changes" should be available since the file is added/ there should be a required fields alert for populating previous fields after which the "Save changes" option is seen available.

### Actual  Result ###

"Save changes" is not available even when the file is added, but after populating the previous fields the option is available. 

### Screenshots ###

[Uploading No save option after uploading file .zip…]()

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome Version 64.0.3282.140 (Official Build) (32-bit)*

**Comment by sdgun** [comment]
Not a Bug, it auto saves
