### ISSUE TITLE
Wrong grammar on Submit for review page

### ISSUE THREAD

**Issue by InfinityToP** [topcoderinc/connect-test-cycle-1#304]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2677/specification

### Reproduction Steps ###
1.Login as: pshah_copilot/topcoder123
2.Go to the above URL.
3.Scroll down to the bottom, to Project files,Submit a review.
### Expected Result ###

The sentence should be grammatically correct.It should be-"In order to submit your project, please fill in all the required information. **Once you do that, we"ll be able to give you a good estimate.**"

### Actual  Result ###

It's not grammatically correct. It's-"In order to submit your project please fill in all the required information. Once **that** you do that we"ll be able to give you a good estimate."

### Screenshots ###

![image](https://user-images.githubusercontent.com/32297688/36368410-17963780-157d-11e8-942c-c78696767e49.png)

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome Version 64.0.3282.140 (Official Build) (32-bit)*

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1799
