### ISSUE TITLE
footer on the intermediate page is different with others

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#305]
### Reported URL ###

*https://connect.topcoder-dev.com/*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. click the Down arrow on the top right, click Log out, observe the footer part on the intermediate page

### Expected Result ###

*The footer part should be consistent with other pages.*

### Actual Result ###

*See screenshots.*

### Screenshots ###
Intermediate page footer:
<img width="1439" alt="logout" src="https://user-images.githubusercontent.com/4590317/36369967-2e5ffddc-1598-11e8-8662-1ac1db117fc5.png">

Other page footer:
<img width="1439" alt="log2" src="https://user-images.githubusercontent.com/4590317/36369985-3a4b169a-1598-11e8-8acc-1da7eefe1b89.png">

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by sdgun** [comment]
Not an issue
