### ISSUE TITLE
click on the notification message should dismiss the modal

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#306]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/2652/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. create a new project, then update the project (e.g. edit project details) so that some notifications are received
3. go to specification page: https://connect.topcoder-dev.com/projects/2652/specification
4. click the Bell icon, click on the notification message on the modal, observe

### Expected Result ###

*Click on the notification detail should dismiss the modal.*

### Actual Result ###

*See screencasts, if it is already on the current specification page, it won't dismiss the modal.*

### Screencasts ###
https://youtu.be/Z5sEDGXfFqE

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by vic-georgiev** [comment]
by design the notifications are not dismissed when clicking on them.

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1790
