### ISSUE TITLE
 tooltip for bell icon should be adjusted

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#307]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/2652/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. go to specification page: https://connect.topcoder-dev.com/projects/2652/specification, check tooltip of the bell icon

### Expected Result ###

*Tooltip should be adjusted.*

### Actual Result ###

*See screenshot.*

### Screenshots ###

<img width="442" alt="tool" src="https://user-images.githubusercontent.com/4590317/36371138-30c06dec-159c-11e8-941e-c6d26daa8412.png">

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by sdgun** [comment]
Too trivial and text in the tooltip is displayed
