### ISSUE TITLE
footer should be moved to bottom center of the page

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#308]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/2652/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. go to specification page: https://connect.topcoder-dev.com/projects/2652/specification, check footer part

### Expected Result ###

*footer should be moved to bottom center of the page.*

### Actual Result ###

*See screenshot.*

### Screenshots ###

<img width="1412" alt="footer" src="https://user-images.githubusercontent.com/4590317/36371324-ba0c1178-159c-11e8-8109-ed420b804591.png">

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Google Chrome Version 64.0.3282.167 (Official Build) (64-bit)*

**Comment by sdgun** [comment]
As per the design
