### ISSUE TITLE
layout issue if entering a long description for the uploaded file

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#309]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/2652/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. create a new project (select App as project type), then upload a text file
3. go to specification page: https://connect.topcoder-dev.com/projects/2652/specification, edit the description with the text "demoklfdsklafdsafsdademoklfdsklafdsafsdademoklfdsklafdsafsdademoklfdsklafdsafsdademoklfdsklafdsafsdademoklfdsklafdsafsdademoklfdsklafdsafsdademoklfdsklafdsafsdademoklfdsklafdsafsdademoklfdsklafdsafsdademoklfdsklafdsafsdademoklfdsklafdsafsdademoklfdsk", save and observe

### Expected Result ###

*Should not have layout issue.*

### Actual Result ###

*See screenshot.*

### Screenshots ###

<img width="1428" alt="lay" src="https://user-images.githubusercontent.com/4590317/36371848-4cf517ea-159e-11e8-962f-042cfd65c1f4.png">

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by sdgun** [comment]
Name without spaces, Not a bug
