### ISSUE TITLE
No option to save short bio

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#31]
### Reported URL ###
*URL where the issue occured, if applicable*
https://www.topcoder-dev.com/settings/profile/

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123	
2. Navigate to https://www.topcoder-dev.com/settings/profile/
3. Enter a short bio like I'm tester
4.  Hit Save button

### Expected Result ###

The short bio is saved.

### Actual  Result ###

Error as screen attached.

### Screenshots ###

*Paste screenshots here.*

![image](https://user-images.githubusercontent.com/29735376/36344470-a0f59690-1412-11e8-901a-3fc7b07883db.png)

### Issue Information ###

Frequency: Always

Device: *device used for testing*

OS: *operating system used on test*

Browser: Chrome

**Comment by sdgun** [comment]
User must select at least one 'TRACKS' before saving
