### ISSUE TITLE
description for uploaded file should be trimmed

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#311]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/2679/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. create a new project (select App as project type), then upload a text file
3. edit the description (e.g. "   This is a text file.   ") of the uploaded file, save it
4. then click the edit icon again, observe

### Expected Result ###

*description for uploaded file should be trimmed.*

### Actual Result ###

*See screenshot, not trimmed.*

### Screenshots ###

<img width="720" alt="text" src="https://user-images.githubusercontent.com/4590317/36372560-5c7bd7ec-15a0-11e8-88b7-8dbada09eb8e.png">

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by sdgun** [comment]
Not an issue
