### ISSUE TITLE
Specification, Discussions Tab not opening for projects

### ISSUE THREAD

**Issue by InfinityToP** [topcoderinc/connect-test-cycle-1#313]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2677/specification

### Reproduction Steps ###
1.Login as: pat_monahan/topcoder123!
2. Go to the above URL
3. Click on the Dashboard,Specification,Discussions tab

### Expected Result ###

The page should open

### Actual  Result ###

Page doesn't open

### Screenshots ###

Screen recording:  [Specification, Discussions Tab not opening for projects.zip](https://github.com/topcoderinc/connect-test-cycle-1/files/1736300/Specification.Discussions.Tab.not.opening.for.projects.zip)

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome Version 64.0.3282.140 (Official Build) (32-bit)*

**Comment by sdgun** [comment]
Old test data issue, Not a bug
