### ISSUE TITLE
Not specific Tool-tip for edit button in Share latest projects updates

### ISSUE THREAD

**Issue by InfinityToP** [topcoderinc/connect-test-cycle-1#314]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2681

### Reproduction Steps ###
1. Login as: pshah_customer/topcoder123
2. Go to the above link, and share something in "Share the latest project updates with the team".
3. Hover over the edit button besides.

### Expected Result ###

Correct tool-tip present.

### Actual  Result ###

The tool tips give description like "ui-16px-1_edit-73" 

### Screenshots ###

![image](https://user-images.githubusercontent.com/32297688/36372992-c4ede1c6-158c-11e8-8365-1911adaed243.png)

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome Version 64.0.3282.140 (Official Build) (32-bit)*

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1781
