### ISSUE TITLE
Owner tag disappearing when hovered over

### ISSUE THREAD

**Issue by InfinityToP** [topcoderinc/connect-test-cycle-1#315]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2681

### Reproduction Steps ###
1. Login as: pshah_customer/topcoder123
2. Go to the above link, and hover over the tag "Owner" besides the name in the left side.

### Expected Result ###

Doesn't disappear when hovered over.

### Actual  Result ###

Disappears when hovered over.

### Screenshots ###

[Owner disappering when hovered over..zip](https://github.com/topcoderinc/connect-test-cycle-1/files/1736344/Owner.disappering.when.hovered.over.zip)

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome Version 64.0.3282.140 (Official Build) (32-bit)*

**Comment by sdgun** [comment]
Not a Bug
