### ISSUE TITLE
Never see a White bell icon even if the notification present is very old

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#316]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects

### Reproduction Steps ###
1. Login as manager pshah_manager / topcoder123
2. Click on the notification , please make sure that notifications dropdown has only old notification, like in this case it is 3 hours old
**Please note that this data may change around testing as multiple testers using same user logins.
3. Observe the notification logo

### Expected Result ###

As per spec : Notification icon should be shown as White bell icon

### Actual  Result ###

Notification icon is shown as white bell with red dot

### Screenshots ###
![image](https://user-images.githubusercontent.com/29735376/36373368-db3bbf7a-155f-11e8-8d55-255aa05a9141.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 7

Browser: Chrome

**Comment by sdgun** [comment]
#241
