### ISSUE TITLE
should restrict file name length

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#317]
### Reported URL ###

*https://connect.topcoder-dev.com/projects/2679/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. create a new project (select App as project type), then upload a text file with file name "contentcontentcontentcontentcontentcontentcontentcontentconetncontentcontentcontent.txt"
3. observe

### Expected Result ###

*should restrict file name length*

### Actual Result ###

*See screenshot, text is overlapped.*

### Screenshots ###
<img width="852" alt="l" src="https://user-images.githubusercontent.com/4590317/36374004-dbad177a-15a4-11e8-9862-8650b3d3b725.png">

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by sdgun** [comment]
File name without spaces
