### ISSUE TITLE
Error on navigation back from terms page for customer

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#318]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com as customer pshah_customer/topcoder123
2. Click terms at bottom right of page
3. On terms page now
4. Click browser back button

### Expected Result ###
User navigates back on https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc page and can see project cards

### Actual  Result ###
Error on page is displayed

### Screenshots ###
![image](https://user-images.githubusercontent.com/29735376/36375865-e3a17d36-1568-11e8-9bbc-4506ba1ab5e4.png)

*Paste screenshots here.*

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 7

Browser: Chrome

**Comment by sdgun** [comment]
Out of scope
