### ISSUE TITLE
Term open in same tab for Customer login

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#319]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc

### Reproduction Steps ###

1. Login to https://connect.topcoder-dev.com as customer pshah_customer/topcoder123
2. Click terms at bottom right of page

### Expected Result ###

Terms should open in new tab to be consistent with other footer links

### Actual  Result ###

Terms page opens in the same tab

### Screenshots ###
![image](https://user-images.githubusercontent.com/29735376/36376029-8e0950aa-1569-11e8-88fb-d3fe7812a92e.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 7

Browser: Chrome

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/2
