### ISSUE TITLE
Footer items missing on login page and showing Topcoder 2017

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#320]
### Reported URL ###
*URL where the issue occured, if applicable*
https://accounts.topcoder-dev.com/connect?retUrl=https:%2F%2Fconnect.topcoder-dev.com%2F

### Reproduction Steps ###
1. Navigate to login page i.e. https://accounts.topcoder-dev.com/connect?retUrl=https:%2F%2Fconnect.topcoder-dev.com%2F

### Expected Result ###

User can see footer links like 
About
Contact us
Privacy
Terms

Copyright should be 2018 i.e. Topcoder 2018

### Actual  Result ###

Issue 1: Footer links are missing

Issue 2: Copyright shown as 2017 i.e. Topcoder 2017

### Screenshots ###

![image](https://user-images.githubusercontent.com/29735376/36376303-85271228-156a-11e8-81eb-1ac7cd829d97.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 7

Browser: IE11, Chrome

**Comment by sdgun** [comment]
As per the design. #7 and #213
