### ISSUE TITLE
Log out Terms -> login Navigating to wrong URL

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#321]
### Reported URL ###
*URL where the issue occured, if applicable*

https://accounts.topcoder.com/connect?retUrl=https:%2F%2Fconnect.topcoder.com%2F

### Reproduction Steps ###
1. Navigate to https://connect.topcoder-dev.com/
2. Click Terms
3. Click Log in button on terms page

### Expected Result ###

User is navigated to https://accounts.topcoder-dev.com/connect?retUrl=https:%2F%2F**connect.topcoder-dev.com**%2F

Login button is consistent with https://connect.topcoder-dev.com/ page

### Actual  Result ###
Issue 1: User is navigated to  https://accounts.topcoder.com/connect?retUrl=https:%2F%2F**connect.topcoder.com**%2F

issue 2:  Log in button https://connect.topcoder-dev.com/ is white and on terms is Blue

### Screenshots ###
![image](https://user-images.githubusercontent.com/29735376/36376563-6ff3e2ea-156b-11e8-9c2c-e7120b25186a.png)
![image](https://user-images.githubusercontent.com/29735376/36376587-8d3ec8a6-156b-11e8-8ebb-e081a427f049.png)
![image](https://user-images.githubusercontent.com/29735376/36376615-9ef5d828-156b-11e8-8c47-cdc7f159c9e1.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 7

Browser: Chrome

**Comment by sdgun** [comment]
URL out of scope: https://connect.topcoder.com/terms
