### ISSUE TITLE
should not print message in the console 

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#322]
### Reported URL ###

*https://connect.topcoder-dev.com/projects*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. observe the web developer console

### Expected Result ###

*should not print any message*

### Actual Result ###

*See screenshot.*

### Screenshots ###

<img width="1405" alt="console" src="https://user-images.githubusercontent.com/4590317/36377860-95c8b91c-15b3-11e8-8f3e-0384956163cb.png">

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Google Chrome Version 64.0.3282.167 (Official Build) (64-bit)*

**Comment by sdgun** [comment]
Without 'What cause this?' can't accept as a bug
