### ISSUE TITLE
Profile picture is different on the project list and page

### ISSUE THREAD

**Issue by macs054** [topcoderinc/connect-test-cycle-1#323]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc&status=active

### Reproduction Steps ###
Go to https://connect.topcoder-dev.com/
Login as pshah_manager/topcoder123
Click My projects
Notice your profile picture you have to the projects that you belong to on the managers column and compare it on the one at the menu bar.
Click any projects that you belong to and check your profile picture there.

### Expected Result ###

The profile picture that you have should also be the picture on the list and project dashboard.

### Actual  Result ###

Profile picture is only shown as PM

### Screenshots ###

![image](https://user-images.githubusercontent.com/1199534/36378785-434a409e-15b7-11e8-8ff1-6e0a240f9f45.png)
![image](https://user-images.githubusercontent.com/1199534/36378801-52ceb43c-15b7-11e8-93f7-4c4020e311d1.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2

**Comment by sdgun** [comment]
Not a Bug.
