### ISSUE TITLE
Navigation back is not working in https://connect.topcoder-dev.com/new-project/

### ISSUE THREAD

**Issue by neethyashok** [topcoderinc/connect-test-cycle-1#324]
### Reported URL ###
https://connect.topcoder-dev.com/new-project/

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com/
2.Click on start a project
3. https://connect.topcoder-dev.com/new-project/ open up
4. Click on Browser Back button

### Expected Result ###

The page https://connect.topcoder-dev.com/ should open

### Actual  Result ###

The page https://connect.topcoder-dev.com/ is not opening on one click

### Screenshots ###

![image](https://user-images.githubusercontent.com/34745773/36379038-18d64c7c-15a3-11e8-96d1-6d5f7cd295fb.png)

### Issue Information ###
Frequency: 3/3

Device: Desktop

OS: Windows 10

Browser: Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by sdgun** [comment]
It's popup not a page, Not a bug
