### ISSUE TITLE
Word-wrap not present in the already created Projects page

### ISSUE THREAD

**Issue by InfinityToP** [topcoderinc/connect-test-cycle-1#325]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2685

### Reproduction Steps ###
1. Login as: pat_monahan/topcoder123!
2. Create a project with a long name.

### Expected Result ###

The name is being word-wrapped

### Actual  Result ###

The name is not being word-wrapped

### Screenshots ###

![image](https://user-images.githubusercontent.com/32297688/36379235-cf67c380-15a3-11e8-94a0-a2022956bc67.png)

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome Version 64.0.3282.140 (Official Build) (32-bit)*

**Comment by sdgun** [comment]
Text without spaces and this is already reported https://github.com/topcoderinc/connect-test-cycle-1/issues/71
