### ISSUE TITLE
email and phone numbers are not validated

### ISSUE THREAD

**Issue by neethyashok** [topcoderinc/connect-test-cycle-1#326]
### Reported URL ###
http://crowdsourcing.topcoder.com/piqued_by_crowdsourcing

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com/ and click on start project
2. scroll down and click on get in touch with us link
3. http://crowdsourcing.topcoder.com/piqued_by_crowdsourcing opens up
4. enter the phone number as "dfhsdkjfhksjd"
5.Enter email as "a@wo.com"
6. Enter other details and click on Lets Talk

### Expected Result ###

The Form should not process without valid email and phone number

### Actual  Result ###

The Form is processed without valid email and phone number

### Screenshots ###
![image](https://user-images.githubusercontent.com/34745773/36379456-a4c86ef8-15a4-11e8-9222-d9a6fd8e9d97.png)

### Issue Information ###
Frequency: 3/3

Device: Desktop

OS: Windows 10

Browser: Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by vic-georgiev** [comment]
this page is out of scope
