### ISSUE TITLE
Inconsistent minimum length of description for different project

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#329]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/new-project/generic-development
https://connect.topcoder-dev.com/new-project/generic-design

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com as customer i.e. pshah_customer/topcoder123
2. Create different new projects by clicking on + button
3. Create Development Integration project-> Type just 1 letter in 'Description' field on Let's set up your Development Integration project page. And Observe
4. Now try to create another new project, this time for Other Design project.
5. Enter just 1 letter in description
6. Observe

### Expected Result ###

The minimum length for every project 'Description' field should be consistent. Most of the projects its Actually 160 characters.

### Actual  Result ###

Other Design project **don't** have minimum 'Description' field length

### Screenshots ###
**When min length error is present:**
![image](https://user-images.githubusercontent.com/29735376/36384938-ecb4dd76-1588-11e8-9f6e-d29ad37d54c5.png)

**When no minimum length error:**

![image](https://user-images.githubusercontent.com/29735376/36384974-0c92e37c-1589-11e8-921e-248d81ff6cfa.png)

*Paste screenshots here.*

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 7

Browser: Chrome

**Comment by sdgun** [comment]
As per the design. https://github.com/topcoderinc/connect-test-cycle-1/issues/135
