### ISSUE TITLE
Save button always enabled on profile page

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#33]
### Reported URL ###
*URL where the issue occured, if applicable*
https://www.topcoder-dev.com/settings/profile/

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123	
2. Navigate to https://www.topcoder-dev.com/settings/profile/

### Expected Result ###

*Enter the expected result here.*
Save button is disabled

### Actual  Result ###

*Enter the expected result here.*

Save button is enabled.

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36344511-64b89c44-1413-11e8-8586-7e616a4e186d.png)

### Issue Information ###

Frequency: Always

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
If you didn't do anything the 'Save' button is in disabled mode. Can't reproduce the bug using the provided steps and details
