### ISSUE TITLE
Customer- create new project always asks "Do you want to continue where you left off or create a new project?"

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#331]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/new-project/generic-development/incomplete

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com as customer i.e. pshah_customer/topcoder123
2. Create new projects by clicking on + button
3. **Complete** creating this project with all valid values. Click **Continue** and  Observe here : Issue: 1
4. In case there is no Issue: 1 and you are on https://connect.topcoder-dev.com/projects page 
if there is Issue 1, then close the modal and then you should be on https://connect.topcoder-dev.com/projects page 
5. Create new projects by clicking on + button
6. Observe

### Expected Result ###

You are on https://connect.topcoder-dev.com/new-project/     page 

### Actual  Result ###

Issue 1: Sometimes: You are not navigated to https://connect.topcoder-dev.com/projects page
Issue 2: You are on https://connect.topcoder-dev.com/new-project/generic-development/incomplete
The code thinks that old project that you start is still incomplete!

### Screenshots ###

Issue:2 
![image](https://user-images.githubusercontent.com/29735376/36386010-4aaa74ba-158c-11e8-904e-06daabadbbe9.png)

*Paste screenshots here.*

### Issue Information ###

Frequency: Issue1 : Sometimes , Issue 2: Always

Device: Desktop

OS: Windows 7

Browser: Chrome

**Comment by sdgun** [comment]
If you haven't completed a project creation process you will get 'continuation' screen next time. 
**Issue 1: Sometimes: You are not navigated to https://connect.topcoder-dev.com/projects page > You should give the steps to reproduce**

By following the steps to reproduce; I can't see a bug here. If the 'Issue 1' is happening we need exact steps
