### ISSUE TITLE
New project window is not modal from project details page

### ISSUE THREAD

**Issue by macs054** [topcoderinc/connect-test-cycle-1#34]
### Reported URL ###
https://connect.topcoder-dev.com/new-project/?returnUrl=https://connect.topcoder-dev.com/projects/2481

### Reproduction Steps ###
Go to https://connect.topcoder-dev.com/
Login as pat_monahan/topcoder123!
Click any projects
Click the '+' button to open create project window

### Expected Result ###

New project window should be modal according to the docs

### Actual  Result ###

New project window is not modal from project details page

### Screenshots ###

![image](https://user-images.githubusercontent.com/1199534/36344478-eaa8099c-1455-11e8-8ab9-5fcc78b6d688.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2

**Comment by sdgun** [comment]
Not a Bug
