### ISSUE TITLE
Window-Manager – In Project Feature page->Add a custom feature-> Project Feature count is getting increased while enabling and disabling the “Enable Feature” button

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#340]
9.Summary:
Window-Manager – In Project Feature page->Add a custom feature-> Project Feature count is getting increased while enabling and disabling the “Enable Feature” button
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a new App project
4.Go to Specification and Go to Feature requirements section
5.Click “Add/Edit Feature” button
6.App navigate to Project Feature page
7.Scroll down and Click “Add a custom feature” button
8. in Feature name enter name as “A1” and Click “Save Feature” button
9..Now we have “A1” features
10. Now keep enabling and disabling the “Enable Feature” button for 5 to 6 time

## Expected Result ###
Window-Manager – In Project Feature page->Add a custom feature-> Project Feature count should not get increased while enabling and disabling the “Enable Feature” button

### Actual  Result ###
Window-Manager – In Project Feature page->Add a custom feature-> Project Feature count is getting increased while enabling and disabling the “Enable Feature” button

 ### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/D146ZKkjyrM

**Comment by sdgun** [comment]
Count related bug reported earlier: #341.

**Comment by youdare** [comment]
@sdgun 
Defect 340 and 341 are completely different, Please check the provided vedio

Defect 340- Project Feature count is getting increased while enabling and disabling the “Enable" Feature button

Defect 341 - After disabling the the feature requirement we are seeing the count
 (Please compare both steps and Video)

This is valid defect

**Comment by sdgun** [comment]
This happens because of an error in the enable/disable feature. Steps are different but Use have used that feature (enable/disable) in both occasions

**Comment by youdare** [comment]
@sdgun  i understand the pain and sorry that iam troubling you again and Again.
I will explain in detail now

Defect 340- Project Feature count is getting increased while enabling and disabling the “Enable" Feature button

Here after adding the features,iam just clicking enable and disable  button , the project features count increases for every click.

Defect 341 - After disabling the the feature requirement we are seeing the count

1.Here after adding the features, iam disabling the all features and Now Project Feature count is becoming "0"
2. I have saved and closed the window
3. Returned back and saw the count again, iam seeing count equal to the added features.

I think iam clear now Thanks for Responding.

**Comment by sdgun** [comment]
#340 - Step 10 - You are using enable/disable feature and count issue happens
#314 - Step 12/13 - You are using enable/disable feature 

This is an issue in the enable/disable feature. So can't count both. Then there are many more scenarios to workout and we can report many more bugs around the same feature.
