### ISSUE TITLE
Window-Manager – In Project Feature page->Add a custom feature-> “Add a custom Feature” button is getting hided and Having scroll issue to view the “Add a custom Feature” button Note: This issue is seen while creating custom Feature for every 2nd one

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#342]
11.Summary:
Window-Manager – In Project Feature page->Add a custom feature-> “Add a custom Feature” button is getting hided and Having scroll issue to view the “Add a custom Feature” button
Note: This issue is seen while creating custom Feature for every 2nd one
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a new App project
4.Go to Specification and Go to Feature requirements section
5.Click “Add/Edit Feature” button
6.App navigate to Project Feature page
7.Scroll down and Click “Add a custom feature” button
8. in Feature name enter name as “A1” and Click “Save Feature” button
9..Now we have “A1” features
10. Again Click “Add a custom feature” button
11. in Feature name enter name as “A2” and Click “Save Feature” button
12. Now we have “A2” features
13.Observe the scroll bar and “Add a custom feature” button
14. Repeat steps from 7 to 13
## Expected Result ###
Window-Manager – In Project Feature page->Add a custom feature-> “Add a custom Feature” button should not get hided and should not Have scroll issue to view the “Add a custom Feature” button

### Actual  Result ###
Window-Manager – In Project Feature page->Add a custom feature-> “Add a custom Feature” button is getting hided and Having scroll issue to view the “Add a custom Feature” button

 ### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/4m0I8L_IKTM

**Comment by sdgun** [comment]
Not a bug, user can simply scroll down and click on the button
