### ISSUE TITLE
Window-Manager – In Project Feature page->Add a custom feature-> Entered notes is not getting retested while disabling and enabling the “Enable Feature” button

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#343]
12.Summary:
Window-Manager – In Project Feature page->Add a custom feature-> Entered notes is not getting retested while disabling and enabling the “Enable Feature” button

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a new App project
4.Go to Specification and Go to Feature requirements section
5.Click “Add/Edit Feature” button
6.App navigate to Project Feature page
7.Scroll down and Click “Add a custom feature” button
8. in Feature name enter name as “A1” and Click “Save Feature” button
9..Now we have “A1” features
10. Enter some notes as “This is Demo”
11. Now click disable and enable the “Enable Feature” button

## Expected Result ###
Window-Manager – In Project Feature page->Add a custom feature-> Entered notes should get retested while disabling and enabling the “Enable Feature” button

### Actual  Result ###
Window-Manager – In Project Feature page->Add a custom feature-> Entered notes is not getting retested while disabling and enabling the “Enable Feature” button

 ### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/hOxIXhMRJdk

**Comment by sdgun** [comment]
No required, As per the design
