### ISSUE TITLE
  Window-Manager – In Project Feature page, Not able to minimize the note section after dragging and Expanding the note section as bigger

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#344]
1. Summary:

Window-Manager – In Project Feature page, Not able to minimize the note section after dragging and Expanding the note section as bigger

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a new App project
4.Go to Specification and Go to Feature requirements section
5.Click “Add/Edit Feature” button
6.App navigate to Project Feature page
7.Click “Email Log in” and Click Enable feature button
8.Enter the large content in note section and Expend as much as possible 
## Expected Result ###

Window-Manager – In Project Feature page, Should allow  to minimize the note section after dragging and Expanding the note section as bigger

### Actual  Result ###

Window-Manager – In Project Feature page, Not able to minimize the note section after dragging and Expanding the note section as biggerr

 ### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/hYCQla9mzQw

**Comment by sdgun** [comment]
Expand/Collapse is a browser feature not to do with the connect app
