### ISSUE TITLE
Add/Edit Project Feature Notes issue

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#345]
### Reported URL ###
*URL where the issue occured, if applicable*

### Reproduction Steps ###
1. Log in to https://connect.topcoder-dev.com/ with pshah_manager/topcoder123
2. .Create a new App project
3. Navigate to Specification and Go to Feature requirements section
5. Click “Add/Edit Feature” button
6. Now navigate to Project Feature page
7. Click “Email Log in” and Click Enable feature button
8. Add notes
9. Create custom feature 
10 Add notes

### Expected Result ###

Notes for Email feature is displayed on Specification page as they are getting displayed for Custom feature

### Actual  Result ###

Notes for Email feature is **not** displayed on Specification page as they are getting displayed for Custom feature

### Screenshots ###

*Paste screenshots here.*
 In comments

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Window 7

Browser: Chrome

**Comment by gargsaurabh86** [comment]
![image](https://user-images.githubusercontent.com/29735376/36389957-098b727e-1599-11e8-87db-cac4919a656e.png)
![image](https://user-images.githubusercontent.com/29735376/36389967-12fa15a4-1599-11e8-81d1-37fe8d6bfa36.png)

**Comment by sdgun** [comment]
Not a Bug, As designed
