### ISSUE TITLE
Window-Manager – In Project Feature page, If we cancel the created feature, App is not navigating to the created feature section

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#346]
1. Summary:
Window-Manager – In Project Feature page, If we cancel the created feature, App is not navigating to the created feature section
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a new App project
4.Go to Specification and Go to Feature requirements section
5.Click “Add/Edit Feature” button
6.App navigate to Project Feature page
7. Scroll down and Click “Add a custom feature” button
8. in Feature name enter name as “A1” and Click “Save Feature” button
9.Click Edit button
10.Click Cancel button from the confirmation prompt
 
## Expected Result ###
Window-Manager – In Project Feature page, If we cancel the created feature, App should navigating to the created feature section

### Actual  Result ###
Window-Manager – In Project Feature page, If we cancel the created feature, App is not navigating to the created feature section

 ### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/bdj8FPsvPcA

**Comment by sdgun** [comment]
Not a Bug
