### ISSUE TITLE
Window-Manager – In Project Feature page, Project Feature count is show as “Project Features- - 1 Selected” while deleting the created feature (After disabling the feature)

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#347]
1. Summary:
Window-Manager – In Project Feature page, Project Feature count is show as “Project Features- - 1 Selected” while deleting the created feature (After disabling the feature)
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a new App project
4.Go to Specification and Go to Feature requirements section
5.Click “Add/Edit Feature” button
6.App navigate to Project Feature page
7. Scroll down and Click “Add a custom feature” button
8. in Feature name enter name as “A1” and Click “Save Feature” button
9.Go to A1 and Disable the feature
10.Click Delete button and Delete the A1 feature

## Expected Result ###
Window-Manager – In Project Feature page, Project Feature count should be show as “Project Features- 0 Selected” while deleting the created feature (After disabling the feature)

### Actual  Result ###
Window-Manager – In Project Feature page, Project Feature count is show as “Project Features- - 1 Selected” while deleting the created feature (After disabling the feature)

 ### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/uQvc6sUIqkc

**Comment by sdgun** [comment]
Count related bug reported earlier: https://github.com/topcoderinc/connect-test-cycle-1/issues/341.
