### ISSUE TITLE
Add/Edit Project Feature Custom feature issue

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#348]
### Reported URL ###
*URL where the issue occured, if applicable*

### Reproduction Steps ###

1. Log in to https://connect.topcoder-dev.com/ with pshah_manager/topcoder123
2. Create a new App project
3. Navigate to Specification and Go to Feature requirements section
4. Click “Add/Edit Feature” button
5. Now navigate to Project Feature page
6. Add a custom feature say 'NewFeature'
7. And Save Changes
8. Now try to **Edit** the same custom feature and update the name to 'MyFeature'
9. Click Save feature

### Expected Result ###

The existing feature name is updated to MyFeature

### Actual  Result ###

A new feature is created with name MyFeature and also update the exiting feature name to MyFeature

### Screenshots ###

In Comments

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Window 7

Browser: Chrome

**Comment by sdgun** [comment]
#339
