### ISSUE TITLE
Whoops we ran in to a problem try again later error appears

### ISSUE THREAD

**Issue by kaygee1** [topcoderinc/connect-test-cycle-1#35]
Open https://connect.topcoder-dev.com/
Login as pshah_manager/topcoder123

Make sure there is a project created with members and manager added to it.

Now
GO to the project dashboard
And First remove yourself  from the project and then Select a manager and remove him

Now observe the screen

Actual - error message - whoops we ran into a problem, try again later appears

expected - this should be handled

Frequency - always
Desktop
OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2
![9](https://user-images.githubusercontent.com/5115050/36344491-2bc7b568-1441-11e8-874c-0361e5a440dc.png)
![10](https://user-images.githubusercontent.com/5115050/36344492-2c03dc0a-1441-11e8-9768-acd685a23c6b.png)
![11](https://user-images.githubusercontent.com/5115050/36344493-2c3da8ae-1441-11e8-9f1b-9da65fdbdabd.png)

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/15
