### ISSUE TITLE
Issue with Wireframe project adding number of screens

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#350]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2695/specification/

### Reproduction Steps ###

1. Log in to https://connect.topcoder-dev.com/ with pshah_manager/topcoder123
2. Create a new Wireframe project
3. Navigate to Specifications
4.  How many screens do you need designed? As **15**
5 Go to App Screens section
6 Start adding screen

### Expected Result ###

User is able to add 15 screens and their details

### Actual  Result ###

User is able to add only 10 screens and their details and post that Define another screen button is disabled.

Screenshots
Comment section

Issue Information
Frequency: Always

Device: Desktop

OS: Window 7

Browser: Chrome

**Comment by gargsaurabh86** [comment]
![image](https://user-images.githubusercontent.com/29735376/36391495-a77f94ce-159e-11e8-9f3a-28dada0bebb0.png)

**Comment by sdgun** [comment]
This happens when user selects 10 screen project and switch to the 15 screens and try to add 15 screens. So when user switch to the 15 screens section 'Save button' must enable and user should able to save before adding screens

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1796
