### ISSUE TITLE
 Wireframe project with 15 screens but only 10 impotance

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#351]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2695/specification/

### Reproduction Steps ###
Log in to https://connect.topcoder-dev.com/ with pshah_manager/topcoder123
1. Create a new Wireframe project with 15 screens
2. Navigate to Specifications
3. Go to App Screens section
5 Start adding screen
6 Check the dropdown of Screen importance

### Expected Result ###

The list should have 15 importance based on number of screens

### Actual  Result ###

Only upto 10 importance

### Screenshots ###
![image](https://user-images.githubusercontent.com/29735376/36391525-c5d667d6-159e-11e8-98a1-e3634152f834.png)

*Paste screenshots here.*

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Window 7

Browser: Chrome

**Comment by vic-georgiev** [comment]
valid

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1782
