### ISSUE TITLE
Wireframe project allowing different screens with same importance

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#352]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2695/specification/

### Reproduction Steps ###
Log in to https://connect.topcoder-dev.com/ with pshah_manager/topcoder123
Create a new Wireframe project
Navigate to Specifications
Go to App Screens section
Start adding screen
Add Screen 1,  select importance 1
Add Screen 2,  select importance 1
Add Screen 3,  select importance 1

### Expected Result ###

Each screen should have unique importance

### Actual  Result ###

All screens can have the same importance

### Screenshots ###
![image](https://user-images.githubusercontent.com/29735376/36391720-a06d92b6-159f-11e8-8a78-326e32f5d9fa.png)

*Paste screenshots here.*

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Window 7

Browser: Chrome

**Comment by vic-georgiev** [comment]
Importance was not designed to be unique
