### ISSUE TITLE
Window-Manager – In Project Feature page, Long feature name cause “UI Issue”

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#354]
1. Summary:
Window-Manager – In Project Feature page, Long feature name cause “UI Issue”
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a new App project
4.Go to Specification and Go to Feature requirements section
5.Click “Add/Edit Feature” button
6.App navigate to Project Feature page
7. Click “Add a Custom Feature” button
8.In Feature name give name as “Demooooooooooooooooooooooooooooooooooooo” and Click “Save Feature button”
## Expected Result ###
Window-Manager – In Project Feature page, Long feature name should not cause “UI Issue”

### Actual  Result ###
Window-Manager – In Project Feature page, Long feature name cause “UI Issue”

 ### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome 

 ### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/H8KMc8x0LOU

**Comment by sdgun** [comment]
Name without spaces that long is not  valid input
