### ISSUE TITLE
Window-Manager – Feature Requirement are arranged in the reverse order.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#355]
1. Summary:
Window-Manager – Feature Requirement are arranged in the reverse order.
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a new App project
4.Go to Specification and Go to Feature requirements section
5.Click “Add/Edit Feature” button
6.App navigate to Project Feature page
7. Click “Add a Custom Feature” button
8.In Feature name give name as “A1” and Click “Save Feature button”
9.Click “Messaging” and Enable the feature
10. Click “Product Listing” and Enable the feature
11. Click “help” and Enable the feature
12. Click “Onboarding” and Enable the feature

## Expected Result ###
Window-Manager – Feature Requirement are arranged in Login & Registration, General Building Blocks, Ecommerce, social and Custom Feature Order.

### Actual  Result ###
Window-Manager – Feature Requirement are arranged in the reverse order.

 ### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/ZUp_CafoN9c

**Comment by sdgun** [comment]
What activated first will appear on the list as the first item and so on. Not a bug
