### ISSUE TITLE
Add a custom feature button disappears while adding/editing features

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#357]
### Reported URL ###
https://connect.topcoder-dev.com/

### Reproduction Steps ###
1. Login as customer pshah_customer / topcoder123
2. Create a new app project with all valid details 
3. go to the specification of that project  by clicking on specification link from the project description
4. Go to Add/edit feature section
5. click on add/edit feature button
6. Now scroll down to add custom feature ,
7. click on add custom feature button, add feature button disappears as soon as it is clicked
8. Now click on any other system feature

### Expected Result ###

Add custom feature button should appear again

### Actual  Result ###

Add custom feature does not come back

### Screenshots ###

![image](https://user-images.githubusercontent.com/29735376/36394231-2d0a352a-15ab-11e8-95c7-6a8496c3738c.png)
![image](https://user-images.githubusercontent.com/29735376/36394249-448d5074-15ab-11e8-92ab-b1fae6b61573.png)
![image](https://user-images.githubusercontent.com/29735376/36394283-6d9c1b80-15ab-11e8-9568-99c01c2d91c2.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows

Browser: IE11

**Comment by sdgun** [comment]
Not a Bug
