### ISSUE TITLE
Window-Manager – App Project-> What colors do you like? Section, Able to move scroll bar from “Hex R G B A” Area

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#358]
1. Summary:
Window-Manager – App Project-> What colors do you like? Section, Able to move scroll bar from “Hex R G B A” Area

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a new App project
4.Go to Specification and Go to What colors do you like? Section
5.Click “ADD-+” button
6. Move the mouse near the “Hex R G B A” Area and scroll 

## Expected Result ###
Window-Manager – App Project-> What colors do you like? Section, Able to move scroll bar from “Hex R G B A” Area

### Actual  Result ###
Window-Manager – App Project-> What colors do you like? Section, Able to move scroll bar from “Hex R G B A” Area

 ### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/O0ompIt5T9I

**Comment by sdgun** [comment]
Not a bug, It's a feature

**Comment by youdare** [comment]
@sdgun  Please check the video, From the "Hex R G B A” Area , iam able to access the color scrollbar.

here nowhere iam using scroll bar
![image](https://user-images.githubusercontent.com/31862600/36487857-eb10be52-1747-11e8-888c-8b4822d6d287.png)


This is valid defect.

**Comment by sdgun** [comment]
Here you can adjust the R,G,B,A colors by drag and drop near the text R,G,B,A

**Comment by youdare** [comment]
Wow okay Thanks for update.
