### ISSUE TITLE
Window-Manager – App Project-> What colors do you like? Section, Tool tip of the colors should be renamed as “Read” “green” ect.. instead of displaying the #Number

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#359]
1. Summary:
Window-Manager – App Project-> What colors do you like? Section, Tool tip of the colors should be renamed as “Read” “green” ect.. instead of displaying the #Number

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a new App project
4.Go to Specification and Go to What colors do you like? Section
5.Click “ADD-+” button
6. Move the mouse over the colors 

## Expected Result ###
Window-Manager – App Project-> What colors do you like? Section, Tool tip of the colors should be renamed as “Read” “green” ect.. instead of displaying the #Number

### Actual  Result ###
Window-Manager – App Project-> What colors do you like? Section, Tool tip of the colors is displaying the #Number

 ### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/36394795-d302d02e-15db-11e8-8dbd-ed16d4fd419e.png)

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/36394809-eb408b4a-15db-11e8-8791-e703fa8a976f.png)

**Comment by sdgun** [comment]
Not a Bug, It's hexa value
