### ISSUE TITLE
No Save option for short bio

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#36]
### Reported URL ###
*URL where the issue occured, if applicable*
https://www.topcoder-dev.com/settings/profile/

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123	
2. Navigate to https://www.topcoder-dev.com/settings/profile/
3. Enter a short bio like I'm tester

### Expected Result ###

*Enter the expected result here.*
There is save option for short bio

### Actual  Result ###

*Enter the expected result here.*
There is no save button for Short bio
### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36344521-9eca11a6-1413-11e8-9499-08f53be1b1e1.png)

### Issue Information ###

Frequency: Always
Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
There is a 'Save' button below 'TRACKS' section
