### ISSUE TITLE
half of the features getting greyed out when Add custom feature button is clicked

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#360]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2698/specification/

### Reproduction Steps ###
Log in to https://connect.topcoder-dev.com/ with pshah_manager/topcoder123
Create a new App project
Navigate to Specification and Go to Feature requirements section
Click “Add/Edit Feature” button
Now navigate to Project Feature page
Click on Add new custom feature button
Now scroll up using left hand side scrolling
Observe all the features shown

### Expected Result ###

All features should be enabled and clickable in order to select
### Actual  Result ###

half of the features are getting greyed out Features starting from 'email login' till 'sharing' are disabled and greyed out while features from 'tags' till 'messages' (last feature) are only enabled

### Screenshots ###

![image](https://user-images.githubusercontent.com/29735376/36394804-c9dc4828-15ad-11e8-95da-a65adb21f658.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Window 7

Browser: IE11

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/353
