### ISSUE TITLE
File upload note going out of frame

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#361]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2696/specification/

### Reproduction Steps ###

1. Login to https://connect.topcoder-dev.com using pshah_customer/topcoder123
2. Create a new Visual design project and Navigate to Specification page of any project like https://connect.topcoder-dev.com/projects/2696/specification
3. Now upload a file like test.txt
4. Now click edit and add notes
5 Add note as ververververververververververververververververververververververververververververververververververververververververververververlong

6. Save notes

### Expected Result ###
Notes not going out of frame
User is still able to edit the file and notes
User can delete file

### Actual  Result ###

Notes going out of frame
User is not able to edit the file and notes
User is not able to delete file

### Screenshots ###

![image](https://user-images.githubusercontent.com/29735376/36395058-fc6abe7c-15ae-11e8-8562-8cab4fafc9f3.png)

![image](https://user-images.githubusercontent.com/29735376/36395161-963a356e-15af-11e8-849b-30aa0d5da56e.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS:  Windows10

Browser: Chrome

**Comment by sdgun** [comment]
Can't expect such a long file name without spaces
