### ISSUE TITLE
Window-Manager –Common- App Project-> All the “Save Changes” buttons are getting disabled if we delete the mandatory field in the specification page.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#362]
1. Summary:
Window-Manager –Common- App Project-> All the “Save Changes” buttons are getting disabled if we delete the mandatory field in the specification page.

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a new App project
4.Go to Specification
5.Delete any mandatory field
6.Go to other section ->Edit and try to save.

## Expected Result ###
Window-Manager –Common- App Project-> All the “Save Changes” buttons should not get disabled if we delete the mandatory field in the specification page.
Only specific area should be disabled

### Actual  Result ###
Window-Manager –Common- App Project-> All the “Save Changes” buttons are getting disabled if we delete the mandatory field in the specification page.

 ### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/3dGdePA4Xkk

**Comment by sdgun** [comment]
'Save' button is disabled because a required field is missing. All the 'Save Changes' buttons served the same purpose. They are not bound to different sections.
