### ISSUE TITLE
Add file popup window is not showing in IE11, user not able to upload files

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#363]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2699/specification/

### Reproduction Steps ###
1 .Log in to https://connect.topcoder-dev.com/ with pshah_customer/topcoder123
2. Create a new mobility testing project
3. Navigate to Specification and Go to Feature requirements section
4. Scroll to the end of page to Add file
5. Click on Add file button

### Expected Result ###

Pop up window should be shown to upload files

### Actual  Result ###

nothing happens when we click on Add file button, Pop up windows is not showing at all to upload files

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36396046-0ded4f98-15b4-11e8-9e5b-bad1e8325b7c.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 7

Browser: IE11

**Comment by sdgun** [comment]
I can see the popup

**Comment by gargsaurabh86** [comment]
@sdgun Please test this on IE11 only on Window 7.

This issue is not reproducible on any other browser. Thank you.

**Comment by sdgun** [comment]
I have tested on IE11

![2018-02-22_4-48-07](https://user-images.githubusercontent.com/4592712/36534242-9ab418e8-178b-11e8-9864-27836d29432a.jpg)
