### ISSUE TITLE
Window-Manager – Mobility Testing Project-> What kind of application would you like to test? Drop down is having UI issue.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#364]
1. Summary:
Window-Manager – Mobility Testing Project-> What kind of application would you like to test? Drop down is having UI issue.
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a Mobility Testing Project
4.Go to Specification
5.Click drop down list in “What kind of application would you like to test?”

## Expected Result ###
Window-Manager – Mobility Testing Project-> What kind of application would you like to test? Drop down should not have UI issue.

### Actual  Result ###
Window-Manager – Mobility Testing Project-> What kind of application would you like to test? Drop down is having UI issue.

 ### Screenshots ###
![image](https://user-images.githubusercontent.com/31862600/36396298-540f0e92-15e3-11e8-9756-b9fbc9cf31ec.png)

### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
No an issue, as per the design
