### ISSUE TITLE
Window-Manager – Title of the notification page is named as “Profile and setting” instead of “Notification Setting”

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#365]
1. Summary:
Window-Manager – Title of the notification page is named as “Profile and setting” instead of “Notification Setting”
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Click Notification bell
4.Click View all notification
5.Click “Notification Setting” button

## Expected Result ###
Window-Manager – Title of the notification page should be named as “Notification Setting
### Actual  Result ###
Window-Manager – Title of the notification page is named as “Profile and setting” instead of “Notification Setting
 ### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/ytJaRgY_qlk

**Comment by sdgun** [comment]
@vic-topcoder

**Comment by vic-georgiev** [comment]
valid

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1783
