### ISSUE TITLE
Window-Customer – Able to view delete project in “My project List”

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#366]
1. Summary:
Window-Customer – Able to view delete project in “My project List”
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create App roject
4.Click “Delete” button and Delete the project
5.Verify Delete project is available in “My project List”

## Expected Result ###
Window-Customer – Application should not to view delete project in “My project List”
### Actual  Result ###
Window-Customer – Able to view delete project in “My project List”
 ### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/bjFLVtFtXWI

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/237
