### ISSUE TITLE
Window-Customer – Increment logic is wrong in What is your project budget? Field 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#367]
1. Summary:
Window-Customer – Increment logic is wrong in What is your project budget? Field 
 
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create App project
4.Go to What is your project budget? Field
5. Enter “1234567891011121314”
6.Click “increment “ button

## Expected Result ###
Window-Customer – Increment logic should be correct in What is your project budget? Field 
### Actual  Result ###
Window-Customer – Increment logic is wrong in What is your project budget? Field 
Getting increment count in 1.222…..
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/MXw0FfL3fss

**Comment by sdgun** [comment]
Not a Bug
