### ISSUE TITLE
Window-Customer –Not able to use increment and Decrement button in What is your project budget? Field 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#368]
1. Summary:
Window-Customer –Not able to use increment and Decrement button in What is your project budget? Field 
 Note: Please follow the mentioned steps
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create App project
4.Go to What is your project budget? Field
5. Copy Paste Project budget as “1234567891011121314”
6.Click outside of the What is your project budget? Field 
7.Now move the mouse over the increment and Decrement button and Start incrementing or decrementing 

## Expected Result ###
Window-Customer –Should allow to increment and Decrement button in What is your project budget? Field 
### Actual  Result ###
Window-Customer –Not able to use increment and Decrement button in What is your project budget? Field 
Getting increment count in 1.222…..
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/nqbbbqScT1g

**Comment by sdgun** [comment]
Not a Bug
