### ISSUE TITLE
Window-Customer –Project is submitted for review while clicking “cancel” button on the message prompt “You have unsaved changes. Are you sure you want to leave?

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#369]
1. Summary:
Window-Customer –Project is submitted for review while clicking “cancel” button on the message prompt “You have unsaved changes. Are you sure you want to leave?”

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create App project
4.. Go to specification and Fill all the mandatory fields
5.After Filling all the mandatory fields, Try to edit some extra fields
6. Click “Submit For Review” button
7. App will throw message prompt as ““You have unsaved changes. Are you sure you want to leave?”
With “OK” and “Cancel” button
8.Click “Cancel: button

## Expected Result ###
Window-Customer –Project should not be submitted for review while clicking “cancel” button on the message prompt “You have unsaved changes. Are you sure you want to leave?”
### Actual  Result ###
Window-Customer –Project is submitted for review while clicking “cancel” button on the message prompt “You have unsaved changes. Are you sure you want to leave?”
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/YcTpi6qCb28

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1795
