### ISSUE TITLE
Co-pilot changed to member when it make another member as owner

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#370]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2722

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ as pshah_copilot/topcoder123
2. Create a new App project
3. Now you are on project dashboard page
4. Also Under PROJECT TEAM co-pilot is owner
5. Add member as pshah_customer
6. Refresh the page
7. Change member as owner
8. Check under project team

### Expected Result ###

The role of pshah_copilot is changed to co-pilot

### Actual  Result ###

The role of pshah_copilot is changed to member

### Screenshots ###

In comment section

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Edge

**Comment by gargsaurabh86** [comment]
https://youtu.be/GtTx-gauDqw

**Comment by sdgun** [comment]
Not a Bug, You must add the copilot using the copilot tab, If he is the one who created the project he will become owner and then member if the permission revoked
