### ISSUE TITLE
Page just reload automatically without suggesstion

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#374]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2724

### Reproduction Steps ###
Login as customer on Chrome 
Add Copilot pshah_copilot as member to project like https://connect.topcoder-dev.com/projects/2724/ and stay on dashboard of project i.e. https://connect.topcoder-dev.com/projects/2724/
Open Edge browser and login as copilot
If Copilot is newly added then create 2+ views to above project dashboard by moving back to All projects then to this project couple of times 
Now 4th time stay on Dashboard
Go to Customer view in Chrome and comment
Now come back to member view opened in edge browser and wait May be 10-20 sec
 

### Expected Result ###

As per Spec: Member of a project - new post/comment since I loaded the page - page reload suggestion (notification)

### Actual  Result ###

The member of project does not get any suggestion as notification but the page re-loads automatically
### Screenshots ###

Comment section

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome, Edge

**Comment by gargsaurabh86** [comment]
https://youtu.be/hkisK8yXZ-A

**Comment by vic-georgiev** [comment]
as designed - when the page is at the top. The purpose is to reduce the need for a customer to reload the page.

**Comment by gargsaurabh86** [comment]
@vic-topcoder  please note the extract from specs : Member of a project - new post/comment since I loaded the page - page reload suggestion (notification).

Regards

**Comment by gargsaurabh86** [comment]
@sdgun  @vic-topcoder  please check that irrespective of page position, irrespective of whether suggestion(never in the form of notification) comes or not. The page is reloading automatically.
And specs clearly mention,  new post/comment since I loaded the page - page reload suggestion (notification).
Please consider.

Thank you.

**Comment by gargsaurabh86** [comment]
@sdgun @vic-topcoder waiting for your kind reply.

thank you.
