### ISSUE TITLE
Not working feed : Member of a project - 2+ views - show what’s new since last time I viewed the feed

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#375]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2724

### Reproduction Steps ###
Login as customer on Chrome 
Add Copilot pshah_copilot as member to project like https://connect.topcoder-dev.com/projects/2724/ and stay on dashboard of project i.e. https://connect.topcoder-dev.com/projects/2724/
Open Edge browser and login as copilot
If Copilot is newly added then create 2+ views to above project dashboard by moving back to All projects then to this project couple of times 
Now 4th time stay on All projects
Go to Customer view in Chrome and update Spec and also comment
Now come back to member view and Navigate to Project dashboard page

### Expected Result ###

As per Spec: Feed: Member of a project - 2+ views - show what’s new since last time I viewed the feed
This is not a notification.

### Actual  Result ###

Not working feed: There is no section on the page that show what’s new since last time I viewed the feed
### Screenshots ###

https://youtu.be/TCiE2YxWv-Q

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome, Edge

**Comment by sdgun** [comment]
@vic-topcoder

**Comment by vic-georgiev** [comment]
Valid

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1792
