### ISSUE TITLE
Customer allowed to add team members to a project after the project is completed

### ISSUE THREAD

**Issue by kaygee1** [topcoderinc/connect-test-cycle-1#378]
Open https://connect.topcoder-dev.com/
and login as Customer pshah_customer/topcoder123

In the home page Go to a project that has already been completed
I went to this 
https://connect.topcoder-dev.com/projects/2725/

Click Add Team members and add a couple of them

actual result - It allows a customer to add 2 team members even after the project is completed

expected result - Customer should not be allowed to add

Screenshots
See the end of the bug

Issue Information
Frequency: Always

Device: Desk top *

OS: Win 10*

Browser: Firefox*

![25](https://user-images.githubusercontent.com/5115050/36405601-86cbf7a8-1617-11e8-8843-dc2d5797c7c3.png)

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/162
