### ISSUE TITLE
Grid and List view options as well as diff phases view for a project is not seen

### ISSUE THREAD

**Issue by kaygee1** [topcoderinc/connect-test-cycle-1#379]
Open https://connect.topcoder-dev.com/
and login as Customer pshah_customer/topcoder123

In the home page See the listings

actual - everything is displayed as  grid
Try to change to list

actual - no option present to change to list view
Also no option present to see the projects in diff phases like draft review cancelled etd

expected - the options should be included like when the user logs in as a manager

Screenshots
See the end of the bug

Issue Information
Frequency: Always

Device: Desk top *

OS: Win 10*

Browser: Firefox*

![26](https://user-images.githubusercontent.com/5115050/36405783-67eb065c-1618-11e8-8364-85be8461d264.png)

**Comment by sdgun** [comment]
Not for pshah_customer
