### ISSUE TITLE
Skill not found on Profile page

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#38]
### Reported URL ###
*URL where the issue occured, if applicable*
https://www.topcoder-dev.com/settings/profile/

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123	
2. Navigate to https://www.topcoder-dev.com/settings/profile/
3. Enter Skill language as Java

### Expected Result ###

*Enter the expected result here.*

Search result Java language is shown

### Actual  Result ###

No Result found

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36344547-4530ba90-1414-11e8-9e71-4e930f4ede8b.png)

### Issue Information ###

Frequency: Always

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by vic-georgiev** [comment]
Topcoder - out of scope

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/topcoder-app#1284
