### ISSUE TITLE
Window-Customer –Able to change project specification after moving the project status to Completed or Cancelled 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#380]
1. Summary:
Window-Customer –Able to change project specification after moving the project status to Completed or Cancelled 
 
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create App project and using manager Move the project status to Completed or Cancelled 
4.. Now click Completed or Cancelled project and Go to specification section and start editing and save

## Expected Result ###
Window-Customer –should not allow to change project specification after moving the project status to Completed or Cancelled 
### Actual  Result ###
Window-Customer –Able to change project specification after moving the project status to Completed or Cancelled 
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
Note:- We are able to edit and while clicking save button app is throwing wrong error message to Customer, Need to change the error message or Disable all the fields

**Comment by youdare** [comment]
https://youtu.be/c5KuRIwUSvs

**Comment by sdgun** [comment]
By looking at the video the changes are not applied when the user goes to the project again. Also the error message issue in reported earlier

**Comment by youdare** [comment]
@sdgun  here only issue is The changes are not applied when the user goes to the project again.

iam not reporting on error message, Please take a look again Thanks

**Comment by sdgun** [comment]
In the comment > **here only issue is **The changes are not applied** when the user goes to the project again.**

in the ticket Actual Result > Window-Customer –**Able to change project specification** after moving the project status to Completed or Cancelled

Total different ideas now. Why?
