### ISSUE TITLE
Manager can delete a file from specification even before joining the project

### ISSUE THREAD

**Issue by kaygee1** [topcoderinc/connect-test-cycle-1#383]
Open https://connect.topcoder-dev.com/
and login as Customer pshah_customer/topcoder123

Create a project, enter all valid details
Create specificaiton, upload a file and then send it for review

Now login as a manager  pshah_manager/topcoder123 

Open that project. Before joining the project Open it. Go to Specifications and go the files section

Delete the uploaded file

actual - the file is deleted

expected - should not be able to delete the file before joining the project

Device: Desk top *

OS: Win 10*

Browser: Firefox* ( customer login) Chrome ( Manager login)

![27](https://user-images.githubusercontent.com/5115050/36406458-010231ea-161d-11e8-8474-0658f33be730.png)

**Comment by vic-georgiev** [comment]
Not a bug. Administrators can modify properties on projects without joining.
