### ISSUE TITLE
Window-Customer – Only project status such as in “Review” , “Draft” and “Completed” are shown in the in Project List.( Example:- Project status such as “Cancelled” , Paused ect.. are not shown.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#384]
1. Summary:
Window-Customer – Only project status such as in “Review” , “Draft” and “Completed” are shown in the in Project List.( Example:- Project status such as “Cancelled” , Paused ect.. are not shown.
 
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
Pre-condition 1- Customer need to create 3 project
Pre-condition 2- Manager need to change the project status to “Cancelled” , Paused ect..
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Try to find Project status such as “Cancelled” , Paused ect

## Expected Result ###
Window-Customer – All the project status should be shown in the in Project List
### Actual  Result ###
Window-Customer – Only project status such as in “Review” , “Draft” and “Completed” are shown in the in Project List.( Example:- Project status such as “Cancelled” , Paused ect.. are not shown.
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/59nGRTYQXxY

**Comment by vic-georgiev** [comment]
Not a bug. Customers should not see canceled projects. Paused should be showned
