### ISSUE TITLE
Description field showing error at 160 characters.

### ISSUE THREAD

**Issue by BPragyan** [topcoderinc/connect-test-cycle-1#386]
Reported URL:
https://connect.topcoder-dev.com/new-project/frontend-development

Reproduction Steps :
1. In the Description field provide exact 160 characters

Expected Result:
It should not throw any error as the minimum requirement is 160 characters

Actual  Result:
Showing error

Screenshots:
![top coder 1](https://user-images.githubusercontent.com/36656206/36410289-1c8c081e-1636-11e8-8c13-b28895ca277f.PNG)

Issue Information:

Frequency: always

Device: Desktop

OS: Windows 10

Browser: Chrome Latest

**Comment by sdgun** [comment]
Error is popping up at 160 chars, 
Can't reproduce the bug using the provided steps and details
