### ISSUE TITLE
Missing text in the popup when a manager leaves the project

### ISSUE THREAD

**Issue by pratn75** [topcoderinc/connect-test-cycle-1#388]
### Reported URL ###
*URL where the issue occured, if applicable*

### Reproduction Steps ###
1. As a manager of a project, click on the exit option.

### Expected Result ###

Following text should be displayed:
Once you leave, somebody on the team has to add you for you to be able to see the project. Do you still want to leave the project?

### Actual  Result ###

Following text is displayed:
Once you leave, somebody on the team has to add you fo you to be able to see the project. Do you still want to leave the project?

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/31875915/36412024-6046abba-163e-11e8-9d9d-76f12804c71f.png)

### Issue Information ###

Frequency: Regular

Device: Desktop

OS: Windows 8

Browser: Chrome

**Comment by vic-georgiev** [comment]
Managers/Copilots/Admins should not see such warnings as they can always rejoin a project. Not a bug
