### ISSUE TITLE
Window-Common –Firefox – Tabs are highlighted with dotted box while clicking 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#389]
1. Summary:
Window-Common –Firefox – Tabs are highlighted with dotted box while clicking 
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Click tabs like “My Project” , “Getting Started” , Help.
4.Click any project , Select tabs like Dashboard or Specification 

## Expected Result ###
Window-Common –Firefox – Tabs should not get highlighted with dotted box while clicking 
### Actual  Result ###
Window-Common –Firefox – Tabs are highlighted with dotted box while clicking 
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/36413878-32d354aa-1646-11e8-9e81-fbedaec5226a.png)
![image](https://user-images.githubusercontent.com/31862600/36413892-3af03f5e-1646-11e8-8711-6e2b49e899f7.png)
![image](https://user-images.githubusercontent.com/31862600/36413897-3ff40d3c-1646-11e8-87ba-22978481e69b.png)
![image](https://user-images.githubusercontent.com/31862600/36413902-42922b32-1646-11e8-86a1-0fa9da587517.png)

**Comment by sdgun** [comment]
Trivial issue
