### ISSUE TITLE
Error 500 - Load more projects

### ISSUE THREAD

**Issue by macs054** [topcoderinc/connect-test-cycle-1#392]
### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc

### Reproduction Steps ###
Go to https://connect.topcoder-dev.com/
Login as pat_monahan/topcoder123!
Click 'All projects'
Switch to tile view
Scroll down and click 'Load more projects'

### Expected Result ###

Should load more projects

### Actual  Result ###

Error 500 is shown

### Screencast ###

https://youtu.be/YGS9l0JPxe4

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2

**Comment by sdgun** [comment]
Different user but same functionality https://github.com/topcoderinc/connect-test-cycle-1/issues/193
