### ISSUE TITLE
Can't drag and drop files in IE

### ISSUE THREAD

**Issue by macs054** [topcoderinc/connect-test-cycle-1#393]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2734/specification

### Reproduction Steps ###
Go to https://connect.topcoder-dev.com/ 
Login as pat_monahan/topcoder123!
Create a project of type Website
Go to the Specification tab
Under Project Files click Add File
Drag and drop a text file to the modal window

### Expected Result ###

File must get uploaded 

### Actual  Result ###

Error appears and can't upload file by drag and drop to this window. Though it works if you drop a file under 'Drag and drop your files here' without opening 'Add File' window.

### Screenshots ###

![image](https://user-images.githubusercontent.com/1199534/36415182-e497cd10-165f-11e8-933b-bb430fd14036.png)
Files get uploaded if you drop here
![image](https://user-images.githubusercontent.com/1199534/36415228-05843db0-1660-11e8-9009-a70476dd9c6e.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: IE 11.576.14393.0

**Comment by sdgun** [comment]
Not supported by IE
