### ISSUE TITLE
support@TopCoder.com link is brocken

### ISSUE THREAD

**Issue by neethyashok** [topcoderinc/connect-test-cycle-1#394]
### Reported URL ###
https://connect.topcoder-dev.com/new-project/

### Reproduction Steps ###
1. Create a New Project by opening https://connect.topcoder-dev.com/new-project/
2.Click Select Project in App
3. Enter the details in Let's setup your App project and cliik on continue
4.In the next Page "Your project has been created, and we're ready for your specification" Text Is displayed 
5. Right click and open support@TopCoder.com
![image](https://user-images.githubusercontent.com/34745773/36415869-66b2bb4c-164d-11e8-9dd4-29f2242d8122.png)

### Expected Result ###

User Should be able to Contact Suppot@topcoer.com

### Actual  Result ###

User is not able to  contact support@topcoder.com
### Screenshots ###
![image](https://user-images.githubusercontent.com/34745773/36415864-5c1c88ca-164d-11e8-9b1b-cc6031c61cca.png)

### Issue Information ###
Frequency: 3/3

Device: Desktop

OS: Windows 10

Browser: Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by sdgun** [comment]
No need to right click, just click on the link
