### ISSUE TITLE
Tooltip id displayed incorrectly when hovered on Add Team member option

### ISSUE THREAD

**Issue by pratn75** [topcoderinc/connect-test-cycle-1#396]
### Reported URL ###
*URL where the issue occured, if applicable*

### Reproduction Steps ###
1. Open a project
2. Hover the mouse on Add Team Member option

### Expected Result ###

Tooltip should display 'Add Team Member' consistently

### Actual  Result ###

Sometimes the tooltip displays 'IconUIBoldAdd'

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/31875915/36417018-c7fad04e-1650-11e8-9579-8d393464100c.png)

![image](https://user-images.githubusercontent.com/31875915/36417026-cd929faa-1650-11e8-89f2-b65b1650633e.png)

### Issue Information ###

Frequency: Intermittently

Device: Desktop

OS: Windows 8

Browser: Chrome

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1785
