### ISSUE TITLE
Able to add project team members to a project after it is cancelled

### ISSUE THREAD

**Issue by pratn75** [topcoderinc/connect-test-cycle-1#398]
### Reported URL ###
*URL where the issue occured, if applicable*

### Reproduction Steps ###
1. Open a project and change the status to Cancelled.
2. Click on Add Team Member option and add a member to the project.
3. Click on Create New Link and add a link

### Expected Result ###

User should not be able to add a new team member to a cancelled project.

### Actual  Result ###

1. Initially, an error message is displayed when a user tries to add a new team member.
2. However, after adding a new link both the link and team member get added to the project.

### Screenshots ###

After adding a team member:
![image](https://user-images.githubusercontent.com/31875915/36417843-02123aae-1653-11e8-8336-b4b6d44ad899.png)

After adding a link:
![image](https://user-images.githubusercontent.com/31875915/36417870-12f6d76c-1653-11e8-82cb-16672d519fa6.png)

### Issue Information ###

Frequency: The first time when a user adds a new team member after changing the project status to Cancelled

Device: Desktop

OS: Windows 8

Browser: Chrome

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/147
