### ISSUE TITLE
No ceiling value set for Notes field in project specification

### ISSUE THREAD

**Issue by pratn75** [topcoderinc/connect-test-cycle-1#399]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2071/specification

### Reproduction Steps ###
1. Open a project
2. Navigate to the Specification tab
3. Enter text into any of the Notes fields

### Expected Result ###

There has to be a ceiling value for the Notes fields.

### Actual  Result ###

Notes fields do not have a ceiling value.

### Screenshots ###

Check the specification in the below URL:
https://connect.topcoder-dev.com/projects/2071/specification

### Issue Information ###

Frequency: Regular

Device: Desktop

OS: Windows 8

Browser: Chrome

**Comment by vic-georgiev** [comment]
not a bug. we want customer to be able to provide as much information as they want
