### ISSUE TITLE
UI issue while login

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#4]
### Reported URL ###
*https://connect.topcoder-dev.com*

### Reproduction Steps ###
1. open https://connect.topcoder-dev.com/
2. enter credentials to login, observe

### Expected Result ###

*spinner should not overlap the text*

### Actual Result ###

*See screenshot.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="513" alt="2" src="https://user-images.githubusercontent.com/4590317/36344131-dae8bcf4-1450-11e8-90ea-23c52660bf66.png">

**Comment by sdgun** [comment]
Not a Bug
