### ISSUE TITLE
Contact us broken on profile page

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#40]
### Reported URL ###
*URL where the issue occured, if applicable*
https://help.topcoder-dev.com/hc/en-us/articles/219069687-Contact-Support

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123	
2. Navigate to https://www.topcoder-dev.com/settings/profile/
3. Go to footer of page
4. Click Contact us

### Expected Result ###

Page opens and loaded

### Actual  Result ###

Error

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36344599-f59e5068-1414-11e8-97d6-27e3001a3699.png)

### Issue Information ###

Frequency: Always
Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
Same section: Duplicate with https://github.com/topcoderinc/connect-test-cycle-1/issues/40

**Comment by vic-georgiev** [comment]
Topcoder - out of scope

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/topcoder-app#1285
