### ISSUE TITLE
Spaces should not be considered as a valid text

### ISSUE THREAD

**Issue by kaygee1** [topcoderinc/connect-test-cycle-1#400]
Reproduction Steps
Open the site Test URLs: https://connect.topcoder-dev.com/

Login as pat_monahan/topcoder123!

Click on any existing project
Click on Create  a new comment box
Now enter spaces in the box and Post

actual - The page refreshes, but nothing happens

expected - spaces must be trimmed and user should be asked to enter a text before posting.

Frequency - always
Desktop
Win 10 
Fire fox 58

![29](https://user-images.githubusercontent.com/5115050/36418408-c693e43a-1654-11e8-8f6d-0f37f38ee909.png)

**Comment by sdgun** [comment]
Validation is there, Not a bug
