### ISSUE TITLE
Able to save changes by leaving mandatory values empty

### ISSUE THREAD

**Issue by pratn75** [topcoderinc/connect-test-cycle-1#401]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2071/specification

### Reproduction Steps ###
1. Open a project
2. Navigate to the specification tab
3. Make all the changes and leave few mandatory values (like Project Files or users of the application) blank
4. Click Save changes button

### Expected Result ###

Appropriate error message should be displayed.

### Actual  Result ###

Changes are saved.

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/31875915/36418424-d55315d6-1654-11e8-937a-5a5d11aff3f2.png)

### Issue Information ###

Frequency: Regular

Device: Desktop

OS: Windows 8

Browser: Chrome

**Comment by vic-georgiev** [comment]
Not a bug. The required fields are only for the owner/team member to be able to submit project. Save is preserving the state of the form
