### ISSUE TITLE
Error message appears twice

### ISSUE THREAD

**Issue by kaygee1** [topcoderinc/connect-test-cycle-1#403]
Reproduction Steps
Open the site Test URLs: https://connect.topcoder-dev.com/

Login as pat_monahan/topcoder123!

Click on any existing project and go to its discussion

I used
https://connect.topcoder-dev.com/projects/513/discussions

Create a first discussion ( it should be the first discussion thread of the project)
Subject and message both as First 

Click on post twice back to back and Observe

actual - error message appears twice

expected - this should not happen

Frequency - always
Desktop
Win 10 
Fire fox 58

![32](https://user-images.githubusercontent.com/5115050/36418936-82ad1dac-1656-11e8-99ca-de6c240cf70f.png)

**Comment by sdgun** [comment]
Not a Bug, https://github.com/topcoderinc/connect-test-cycle-1/issues/88 and https://github.com/topcoderinc/connect-test-cycle-1/issues/183
