### ISSUE TITLE
Only icons are shown for dashboard, specification and discussion on top bar, with no description or Tooltip

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#404]
### Reported URL ###
https://connect.topcoder-dev.com/projects/

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ as pshah_manager/ topcoder123
2. Navigate to any active  project say https://connect.topcoder-dev.com/projects/625
3. observe the dashboard, specification and discussion icons shown in the top bar

### Expected Result ###

the icons should be consistent and should show icon + description as shown for example reviewed projects

### Actual  Result ###

Issue1. Only icons are shown for dashboard, specification and discussion 
Issue 2. there is no tool tip for these icons when you hover over to understand which icon is for what purpose

### Screenshots ###
![image](https://user-images.githubusercontent.com/29735376/36419544-200a41e2-162a-11e8-8261-9b7f1e876cf9.png)

### Issue Information ###

Frequency: Repeated

Device: Desktop

OS: Windows 7

Browser: Chrome

**Comment by gargsaurabh86** [comment]
just to compare, Icons looks perfectly fine in IE11 for same user and same project. (by following same steps)
![image](https://user-images.githubusercontent.com/29735376/36428391-af2ba344-1647-11e8-82e5-9d19ad746b84.png)

**Comment by gargsaurabh86** [comment]
Yep just tested again on my Dell Windows 7 laptop with 14 inches screen and 1366*768 screen resolution on IE11 and was able to reproduce again.

**Comment by sdgun** [comment]
Not a bug. In small screens only icons are displayed

**Comment by gargsaurabh86** [comment]
oh ok no problems. Thank for letting know :)
