### ISSUE TITLE
Not able to  register / Sign on with single sign on User 

### ISSUE THREAD

**Issue by neethyashok** [topcoderinc/connect-test-cycle-1#405]
### Reported URL ###
https://accounts.topcoder-dev.com/connect/registration

### Reproduction Steps ###
1. Click on register for free
2.Enter the deatailsl for registration
3. Enter the single sign on email address and the password field is disappeared
5. Right on register
![reg](https://user-images.githubusercontent.com/34745773/36420616-a2c92644-165b-11e8-9854-44cc2ea0233d.png)

### Expected Result ###

User Should be able to register or sign in with single sign on user id

### Actual  Result ###

User is not able to  register or sign on with single sign on user id
### Screenshots ###
![error](https://user-images.githubusercontent.com/34745773/36420735-f74a4072-165b-11e8-9710-87fa37a4323c.png)

### Issue Information ###
Frequency: 3/3

Device: Desktop

OS: Windows 10

Browser: Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by sdgun** [comment]
Not a Bug
