### ISSUE TITLE
Window-Firefox – Topcoder or Connect logo is missing in the  Mozilla Firefox tab.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#406]
1. Summary:
Window-Firefox – Topcoder or Connect logo is missing in the  Mozilla Firefox tab.
Note:- We are able see the logo in IE11,Edge and Chrome.
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123

## Expected Result ###
Window-Firefox – Topcoder or Connect logo should be displayed in the  Mozilla Firefox tab.
### Actual  Result ###
Window-Firefox – Topcoder or Connect logo is missing in the  Mozilla Firefox tab.
### Screenshots ###
Firefox:
![image](https://user-images.githubusercontent.com/31862600/36418401-c09bfda6-1654-11e8-9f37-8572880d8f9a.png)

Chrome:
![image](https://user-images.githubusercontent.com/31862600/36418445-df97e5c6-1654-11e8-9ce8-966a03860685.png)

IE11:
![image](https://user-images.githubusercontent.com/31862600/36420583-892426d0-165b-11e8-83ac-15e8e66d46e1.png)

### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
Not in scope
