### ISSUE TITLE
Window-Firefox –After adding the Feature requirement we have UI issue.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#407]
1. Summary:
Window-Firefox –After adding the Feature requirement we have UI issue.
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3. Create App project
4.Go to specification tab
5. go to Feature requirement section and Add some features
6.Obsever the UI
## Expected Result ###
Window-Firefox –After adding the Feature requirement should not have UI issue.
.
### Actual  Result ###
Window-Firefox –After adding the Feature requirement we have UI issue.
### Screenshots ###
![image](https://user-images.githubusercontent.com/31862600/36421502-a99e60a8-165e-11e8-82ee-f8c288283b47.png)

### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Firefox

**Comment by vic-georgiev** [comment]
SVG icons are not rendered properly in this case.

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1786
