### ISSUE TITLE
User is able to register 2 times using the same email id

### ISSUE THREAD

**Issue by neethyashok** [topcoderinc/connect-test-cycle-1#409]
### Reported URL ###
https://accounts.topcoder-dev.com/connect/registration

### Reproduction Steps ###
1. Open https://accounts.topcoder-dev.com/connect/registration
2. Create account with an email id and verify the Email id using the One time password
3. Create another account with same email  

### Expected Result ###

User should not be allowed to create in the second time with same email id

### Actual  Result ###

I have created nashok and Neethy123 usernames with same email id.

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/34745773/36421671-7c144476-165f-11e8-932b-b3e51a69ae7b.png)

### Issue Information ###
Frequency: 3/3

Device: Desktop

OS: Windows 10

Browser: Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by sdgun** [comment]
Out of scope
