### ISSUE TITLE
Help center link broken on footer of profile page

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#41]
### Reported URL ###
*URL where the issue occured, if applicable*
https://help.topcoder-dev.com/

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123	
2. Navigate to https://www.topcoder-dev.com/settings/profile/
3. Go to footer of page
4. Click Help Center

### Expected Result ###

Page opens and loaded

### Actual  Result ###

Error

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36344618-1aa0c760-1415-11e8-9c7b-2d1c36a32190.png)

### Issue Information ###

Frequency: Always
Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
Same section: Duplicate with https://github.com/topcoderinc/connect-test-cycle-1/issues/40
