### ISSUE TITLE
Save button once enabled don't get disabled on profile page

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#410]
### Reported URL ###
*URL where the issue occured, if applicable*
https://www.topcoder-dev.com/settings/profile/

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123	
2. Navigate to https://www.topcoder-dev.com/settings/profile/
3. Change track. Remeber the changes that you are making on page
4. Save button is enabled. Don't click
5. Revert track Changes that you made earlier on step-3
6. Observe Save button

### Expected Result ###

The Save button should be disabled

Save button is disabled

### Actual  Result ###

The Save button is enabled

Save button is enabled.

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36344511-64b89c44-1413-11e8-8586-7e616a4e186d.png)

### Issue Information ###

Frequency: Always

Device: *Desktop

OS: Windows 10

Browser: Edge

**Comment by sdgun** [comment]
Not an issue
