### ISSUE TITLE
Log out is not redirecting to https://connect.topcoder-dev.com/

### ISSUE THREAD

**Issue by neethyashok** [topcoderinc/connect-test-cycle-1#411]
### Reported URL ###
https://connect.topcoder-dev.com/

### Reproduction Steps ###
1. open https://connect.topcoder-dev.com/
2. Click on Sign in button
3.Sign in and redirected to https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc
3. Click on User Short Name and Select Preferences
4.click on Log out

### Expected Result ###

User should Redirect to https://connect.topcoder-dev.com/

### Actual  Result ###

User is re directed to https://www.topcoder-dev.com/

### Issue Information ###

Frequency: *how often the issue occurs*

Frequency: 3/3

Device: Desktop

OS: Windows 10

Browser: Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by vic-georgiev** [comment]
not going to be fixed. Works fine in production
