### ISSUE TITLE
Window-Chrome – Not able to create project if we have big description 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#413]
1. Summary:
Window-Chrome – Not able to create project if we have big description 
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3. Create App project with big description ( Description should go beyond 5000 Words)

## Expected Result ###
Window-Chrome – should allow to create project if with big description 
.
### Actual  Result ###
Window-Chrome – Not able to create project if we have big description 
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrom

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/36425882-533dd63e-166e-11e8-8458-ef7e246e0bb6.png)
![image](https://user-images.githubusercontent.com/31862600/36425912-662535bc-166e-11e8-921d-1d44ecf7d5c2.png)
![image](https://user-images.githubusercontent.com/31862600/36425920-71780a8e-166e-11e8-9a5b-4efcbc9b4c9c.png)

**Comment by sdgun** [comment]
Created a project with description char limit 5573 > https://connect.topcoder-dev.com/new-project/app
[5573.txt](https://github.com/topcoderinc/connect-test-cycle-1/files/1744525/5573.txt)
