### ISSUE TITLE
Window-Chrome – Scroll bar and Footer  text is getting overlapped , if we crate project with big description.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#414]
1. Summary:
Window-Firefox– Scroll bar and Footer  text is getting overlapped , if we crate project with big description.
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3. Create App project with big description
4.Scroll down and view the Footer  text “In 24 hours our project managers will contact you for more information and a detailed quote that accurately reflects your project needs”

## Expected Result ###
Window-Firefox– Scroll bar and Footer  text should not get overlapped , if we crate project with big description.
.
### Actual  Result ###
Window-Firefox– Scroll bar and Footer  text is getting overlapped , if we crate project with big description.
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Firefox

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/36426786-3faaea82-1671-11e8-80d2-b116c7aed120.png)

**Comment by youdare** [comment]
Browser used _ Firefox,

**Comment by sdgun** [comment]
Can't reproduce on my end. But it is too trivial
