### ISSUE TITLE
Manager: Direct project is created even though the project is not in Active status

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#415]
### Reported URL ###
https://www.topcoder-dev.com/direct/projectOverview?formData.projectId=12995

### Reproduction Steps ###
1. Open https://www.topcoder-dev.com/
2. Login as pshah_manager
3.  Select project which is not in Active status 
4. Selected a draft project
5. Open the project
6. Click on Project in Topcoder Direct link
7. Observe

### Expected Result ###
As per the doc: https://docs.google.com/document/d/1OBUhMGUtqU-Eqpufaom_eAKDbLiR8mq6syb-PSavXDI/edit
Direct project is created when the project goes into Active status

### Actual  Result ###

Direct project is created even though the project is not in Active status

### Screenshots ###

[direct.docx](https://github.com/topcoderinc/connect-test-cycle-1/files/1740219/direct.docx)

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 7 64-bit

Browser: Chrome 64.0

**Comment by vic-georgiev** [comment]
As expected. SFDC lead and Direct project should be created when a Connect project is created.

**Comment by bikakk** [comment]
@vic-topcoder , @sdgun 
As per the document provided, it should be created only when the status is Active. So please look into this.
I have followed the provided document to raise this defect.

![image](https://user-images.githubusercontent.com/31851673/36533945-07f5503a-17bd-11e8-8668-c0deece06b4d.png)

**Comment by bikakk** [comment]
@vic-topcoder @sdgun : 
Can you please look into this again.

**Comment by sdgun** [comment]
Duplicate https://github.com/topcoderinc/connect-test-cycle-1/issues/277

**Comment by vic-georgiev** [comment]
the document is not corrected, thanks for pointing it out.
