### ISSUE TITLE
Window-Mozilla – Notification is not displayed to customer if project manager move the project from In-Review to Draft 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#416]
1. Summary:
Window-Mozilla – Notification is not displayed to customer if project manager move the project from In-Review to Draft 
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3. Create App project 
4.Go to specification and fill the required information and Click “Submit For Review”
5.Log out the app
6.Log in with  pshah_manager/topcoder123
7.Move the project from in-review to draft
8. Log out the app
9.Again log in to Log in with pshah_customer/topcoder123
10. Verify the notification.

## Expected Result ###
Window-Mozilla – Notification should displayed to customer as “Your project is moved to draft” if project manager move the project from In-Review to Draft 
.
### Actual  Result ###
Window-Mozilla – Notification is not displayed to customer if project manager move the project from In-Review to Draft 

### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrom

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/36427495-5f0bfe32-1673-11e8-8565-08188dc70697.png)
![image](https://user-images.githubusercontent.com/31862600/36427504-67d14478-1673-11e8-9128-e50b17f6b76c.png)

![image](https://user-images.githubusercontent.com/31862600/36427370-0efc5090-1673-11e8-90f2-7e2b501dc689.png)

**Comment by sdgun** [comment]
Not a bug.
