### ISSUE TITLE
Window-Mozilla –Manager and Admin don’t have option to delete the project for the created one (Manger and Admin created there project)

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#420]
1. Summary:
Window-Mozilla –Manager and Admin don’t have option to delete the project for the created one (Manger and Admin created there project)
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123 and  pat_monahan/topcoder123!
3. Create a project 
4.Go to dash board and Try to delete the created project

## Expected Result ###
Window-Mozilla –Manager and Admin Should have option to delete the project for the created one(Manger and Admin created there project)
.
### Actual  Result ###
Window-Mozilla –Manager and Admin don’t have option to delete the project for the created one (Manger and Admin created there project)

### Screenshots ###
![image](https://user-images.githubusercontent.com/31862600/36428885-1e39d268-1677-11e8-919b-c410b3660a34.png)
![image](https://user-images.githubusercontent.com/31862600/36428906-28227834-1677-11e8-89fc-31f76869de88.png)

### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrom

**Comment by sdgun** [comment]
Only Project Owner can delete the item
