### ISSUE TITLE
Window-Mozilla – Manager log in –Click user Drop down -> in log out click right click and open a new window  Here we should not allow to right click or If we allow trigger the log out action

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#421]
1. Summary:
Window-Mozilla – Manager log in –Click user Drop down -> in log out click right click and open a new window 
Here we should not allow to right click or If we allow trigger the log out action
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123 and  pat_monahan/topcoder123!
3. Click user Drop down -> in log out click right click and open a new window 

## Expected Result ###
Window-Mozilla – Manager log in –Click user Drop down -> in log out click right click and open a new window 
Here we should not allow to right click or If we allow trigger the log out action
.
### Actual  Result ###
Window-Mozilla – Manager log in –Click user Drop down -> in log out click right click and open a new window 

### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrom

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/36430000-1d30d27e-167a-11e8-8d1a-b2d51ddec8c9.png)

In new tab - Log out
![image](https://user-images.githubusercontent.com/31862600/36430021-2b0f0cda-167a-11e8-81da-bfcb73e4f11c.png)

**Comment by sdgun** [comment]
Not a Bug
