### ISSUE TITLE
Window-Mozilla – Common-Link Drag and Drop option should be disabled across all page

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#422]
1. Summary:
Window-Mozilla – Common-Link Drag and Drop option should be disabled across all page
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123 and  pat_monahan/topcoder123!
3. Drag any button or link to search field  or in New tab 

## Expected Result ###
Window-Mozilla – Common-Link Drag and Drop option should be disabled across all page
.
### Actual  Result ###
Window-Mozilla – Common-Link Drag and Drop option is enable across all page

### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrom

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/36430388-0c277464-167b-11e8-9b14-225312a57ab8.png)
![image](https://user-images.githubusercontent.com/31862600/36430394-1156bab2-167b-11e8-8dc4-72359794e4a8.png)
![image](https://user-images.githubusercontent.com/31862600/36430406-1c5c7384-167b-11e8-9543-b9db406055ef.png)

**Comment by sdgun** [comment]
Not a Bug
