### ISSUE TITLE
Window-Mozilla – Add member should not show same member as suggestion when user already in role

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#423]
1. Summary:
Window-Mozilla – Add member should not show same member as suggestion when user already in role
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2.Crate a project
3.Add a same member 

## Expected Result ###
Window-Mozilla – Add member should not show same member as suggestion when user already in role
.
### Actual  Result ###
Window-Mozilla – Add member should not show same member as suggestion when user already in role

### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrom

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/36430903-3f73d906-167c-11e8-8827-504c6fec22f2.png)

**Comment by youdare** [comment]
@sdgun  i have edited I have 59 seconds remaning ,,, FYI
![image](https://user-images.githubusercontent.com/31862600/36430950-5916f474-167c-11e8-8154-77c660c0396f.png)

**Comment by sdgun** [comment]
As per the design
