### ISSUE TITLE
404 error appears while opening the notification in a new tab

### ISSUE THREAD

**Issue by kaygee1** [topcoderinc/connect-test-cycle-1#43]
Open https://connect.topcoder-dev.com/
Login as pshah_manager/topcoder123

Make sure there are existing projects
and there are sufficient notifications

Now click on Notification Bell and Right click on any notification message in a new tab
See the error message

actual- 404 error appears

expected - error should be handled

Frequency - always

Desktop
OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2'

![15](https://user-images.githubusercontent.com/5115050/36344649-aa534170-1443-11e8-8269-72c63f5b0407.png)
![16](https://user-images.githubusercontent.com/5115050/36344650-aa92d9d4-1443-11e8-8fb5-20d62cc571d3.png)

**Comment by sdgun** [comment]
Tried 4-5 notifications and can't reproduce this issue
