### ISSUE TITLE
layout issue for description

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#45]
### Reported URL ###
*https://connect.topcoder-dev.com/projects/2502*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123
2. select App as the project type
3. create a new project, then fill description with "testingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtesting"
4. fill other fields properly, proceed, observe

### Expected Result ###

*should have no layout issues.*

### Actual Result ###

*See screenshots.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="1284" alt="layout" src="https://user-images.githubusercontent.com/4590317/36344686-10f0098a-1459-11e8-9dde-20c0f1b8a8e5.png">

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/5
