### ISSUE TITLE
Payment preference link not loading on Edge

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#46]
### Reported URL ###
*URL where the issue occured, if applicable*
https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123
2. Navigate to https://www.topcoder-dev.com/settings/profile/
3. Click on PREFERENCES tab
4. Click on PAYMENT PREFERENCES

### Expected Result ###

Page open and loaded

### Actual  Result ###

*Enter the expected result here.*

Page is not loading

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36344679-fe0ee5e0-1415-11e8-9038-c4ff70d899b7.png)

### Issue Information ###

Frequency: Always
Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
Same as https://github.com/topcoderinc/connect-test-cycle-1/issues/44
