### ISSUE TITLE
Invitation letter not loaded

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#47]
### Reported URL ###
*URL where the issue occured, if applicable*
https://community.topcoder-dev.com/tc?module=VisaSelection

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123
2. Navigate to https://www.topcoder-dev.com/settings/profile/
3. Click on PREFERENCES tab
4. Click on INVITATION LETTER

### Expected Result ###

Page open and loaded

### Actual  Result ###

*Enter the expected result here.*

Link is Error as screensot attached. Your request could not be processed. Please inform TopCoder.
### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36344707-4df5b656-1416-11e8-908c-f4d2144de397.png)

### Issue Information ###

Frequency: Always
Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
Same as #44
