### ISSUE TITLE
Referrals page not loaded

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#49]
### Reported URL ###
*URL where the issue occured, if applicable*
https://community.topcoder-dev.com/tc?module=ViewReferrals

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123
2. Navigate to https://www.topcoder-dev.com/settings/profile/
3. Click on PREFERENCES tab
4. Click on Referrals

### Expected Result ###

Page open and loaded

### Actual  Result ###

*Enter the expected result here.*

Link is Error as screensot attached.
### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36344733-80fc484e-1416-11e8-9440-f7dea95f63d6.png)

### Issue Information ###

Frequency: Always
Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
Same as https://github.com/topcoderinc/connect-test-cycle-1/issues/44
