### ISSUE TITLE
Project outline issue

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#5]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/new-project/website
or https://connect.topcoder-dev.com/new-project/app

### Reproduction Steps ###
1. Navigate to https://connect.topcoder-dev.com/new-project/website
2; Enter vary very long descrption like sdhdjhjsdhjsdhjjhdshjhsdkjkjdsbjkzsdbkfbzsvfjhzsvjhvzhjvbdjhzvbdjhvbzhjdfvjhbdfzjjhdfvhjzdfjhvjhzdjhvjzdhvjhzdvjzdjhvjdhfvjdzhvhbjdfbvzhdhvzhjsdvffjzsdvfjhzdsjhvfzshdjvfhjzsdvfzshvjfvjszfsjhzjsdvjhsdvjhsd
3. Observe under Project outline on rght side

### Expected Result ###

The Project outline should be shown correctly

### Actual  Result ###

The description shown in the Project outline is going out of text box

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36343992-a9caeeb6-140b-11e8-8394-34998f08666c.png)

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *Desktop

OS: All

Browser: Edge

**Comment by sdgun** [comment]
Not a Problem, Paragraph without spaces
