### ISSUE TITLE
Terms not loading Preferences page

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#50]
### Reported URL ###
*URL where the issue occured, if applicable*
https://apps.topcoder-dev.com/forums/?module=Settings

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123
2. Navigate to https://www.topcoder-dev.com/settings/profile/
3. Click on PREFERENCES tab
4. Click on Terms in footer of page

### Expected Result ###

Page open and loaded

### Actual  Result ###

Link is Error as screensot attached.
### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36344755-ce13a208-1416-11e8-9cd0-d52b72457fc4.png)

### Issue Information ###

Frequency: Always
Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
Same section: Duplicate with https://github.com/topcoderinc/connect-test-cycle-1/issues/40
