### ISSUE TITLE
Specification link loads the page instead of just switching tabs

### ISSUE THREAD

**Issue by macs054** [topcoderinc/connect-test-cycle-1#51]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2500/specification/

### Reproduction Steps ###
Go to https://connect.topcoder-dev.com/
Login as pat_monahan/topcoder123!
Create a new project of any type.
From the Dashboard click the 'Specification' link from the message of Coder Bot

### Expected Result ###

Should switch to Specification tab

### Actual  Result ###

The link loads the page instead of just switching tabs

### Screencast ###

https://youtu.be/T5_umwIfkFY

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2t*

**Comment by sdgun** [comment]
As per the design
