### ISSUE TITLE
Files should be Project Files 

### ISSUE THREAD

**Issue by kaygee1** [topcoderinc/connect-test-cycle-1#52]
Open https://connect.topcoder-dev.com/
Login as pshah_manager/topcoder123

Go to this link as this user
https://connect.topcoder-dev.com/projects/2357/specification

SEe the last 2 headers - Notes and Files

SEe the actual headers on the right side

actual - Notes and Project files
expected - Files should be Project Files on the left menu

requency - always

Desktop
OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2

![18](https://user-images.githubusercontent.com/5115050/36344764-1596e7e2-1445-11e8-90a3-358b3198c712.png)

**Comment by sdgun** [comment]
Not a Bug
