### ISSUE TITLE
Project name is not shown fully in the project outline

### ISSUE THREAD

**Issue by kaygee1** [topcoderinc/connect-test-cycle-1#54]
Open https://connect.topcoder-dev.com/
Login as pshah_manager/topcoder123

cLICK ON + and create a new project
Enter a text  and see the project name in the project outline

actual - it is not seen fully

expected - it should be seen fully as it is a project outline

frequency - always

Desktop
OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2

![19](https://user-images.githubusercontent.com/5115050/36344826-f3c537b2-1445-11e8-90d6-b7abbc284bad.png)

**Comment by sdgun** [comment]
Project name without spaces of that long is not a valid input
