### ISSUE TITLE
gateway timout error shown

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#56]
### Reported URL ###
*https://connect.topcoder-dev.com/projects/2502*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pat_monahan/topcoder123!
2. create a new project (id is 2502)
3. then go to https://connect.topcoder-dev.com/projects/2502
4. enter "<script>alert(200);</script>" as comment title, "<script>alert(100);</script>" as body , post it, observe

### Expected Result ###

*should have no error shown.*

### Actual Result ###

*See screenshot.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Sometimes*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="1376" alt="gate" src="https://user-images.githubusercontent.com/4590317/36344857-8ae22adc-145b-11e8-8f8f-e7eea7d69963.png">

**Comment by sdgun** [comment]
Can't reproduce the bug using the provided steps and details
