### ISSUE TITLE
dropdown list should be sorted alphabetically

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#58]
### Reported URL ###
*https://connect.topcoder-dev.com/projects/2502*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pat_monahan/topcoder123!
2. create a new project (id is 2502)
3. then go to https://connect.topcoder-dev.com/projects/2502
4. on leftside, click the + button for adding new members,
5. enter "pash", scroll the list and observe

### Expected Result ###

*dropdown list should be sorted alphabetically.*

### Actual Result ###

*See screenshot.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="382" alt="sort" src="https://user-images.githubusercontent.com/4590317/36344886-f94ba958-145b-11e8-99df-37b4bb5cfd1e.png">

**Comment by sdgun** [comment]
Not a Bug
