### ISSUE TITLE
Account name validation issue

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#59]
### Reported URL ###
*URL where the issue occured, if applicable*
https://www.topcoder-dev.com/settings/account/

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123
2. Navigate to https://www.topcoder-dev.com/settings/account/
3. Under Name section
4.Enter invalid First name

### Expected Result ###

Valid error is shown and Save button is disabled
### Actual  Result ###

No error is shown and user able to save invalid name.

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36344915-54336d9e-1419-11e8-8d4d-f11808389861.png)

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
Not a Bug

**Comment by gargsaurabh86** [comment]
@sdgun Just clarifying since this issue is marked as invalid.
1. User is able to Save numbers in name field and backend code is not validating?- Functional issue.
2. Also when there is Error on the First name field, even Last name is getting highlighted by Javascript? - UI issue
3. When you revert the Changes and make name as valid, JavaScript is not working and removing the highlight? UI-issue.

Request you to please consider. 
Still a newbie to Topcoder challenges, so try to understand :)
Sorry for taking your extra bit of time for clarification
Thank you.
