### ISSUE TITLE
Time on the message should not be clickable

### ISSUE THREAD

**Issue by kaygee1** [topcoderinc/connect-test-cycle-1#63]
Open https://connect.topcoder-dev.com/
Login as pshah_manager/topcoder123

Click on any existing project
Click on the time notification on any message

observe

actual - it moves to the next message

expected - the time should not be clickable. It should just be a sense of the time when the message was posted

requency - always

Desktop
OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2

![22](https://user-images.githubusercontent.com/5115050/36344966-680c6864-1448-11e8-9c3b-8a9a97e0a527.png)

**Comment by sdgun** [comment]
As expected
