### ISSUE TITLE
some icons are overlapped

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#64]
### Reported URL ###
*https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc&status=paused*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pat_monahan/topcoder123!
2. go to Paused tab: https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc&status=paused
3. observe

### Expected Result ###

*icons should not be overlapped*

### Actual Result ###

*See screenshot.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="611" alt="ov" src="https://user-images.githubusercontent.com/4590317/36344992-d1171db2-145d-11e8-96e8-999764af382f.png">

**Comment by sdgun** [comment]
as per the design
