### ISSUE TITLE
filter values should be sorted alphabetically

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#66]
### Reported URL ###
*https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pat_monahan/topcoder123!
2. open filter section, observe the filter options

### Expected Result ###

*filter options should be sorted alphabetically*

### Actual Result ###

*See screenshot.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="510" alt="filter" src="https://user-images.githubusercontent.com/4590317/36347164-4647b7f4-148b-11e8-9847-001adbc3479a.png">

**Comment by sdgun** [comment]
Not an issue
