### ISSUE TITLE
All Save enabled simultaneously Specification page

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#68]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2503/specification

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123
2. Navigate to project specification using https://connect.topcoder-dev.com/projects/2503/specification
3. Make any change on the page like Development Specification as How should your application be built?
4. Select ios and android

### Expected Result ###

Save button only under that section is enabled

### Actual  Result ###

All the save buttons on the page are enabled

### Screenshots ###
Screenshot take on edge on very less zoom to show button enabled :)
*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36345076-5c6a8ab2-141c-11e8-81dc-ec3f1ee2e074.png)

### Issue Information ###

Frequency: *how often the issue occurs*

Device: Desktop 
OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
Not a Bug

**Comment by gargsaurabh86** [comment]
@sdgun this is surely a bug as the site is providing the user with save button for each section.
If all save are enabled then:

Assume the user has entered some value in section 1 but not saved it because he did not want to save it.
Now he scrolls down and enter some values in section 2 and want to Save it and it Clicks Save button.

Due to this the unwanted changes are also saved leading to Specification being updated with wrong/unwanted information.

Please review. 

Best Regards

**Comment by sdgun** [comment]
As per the design, the behavior is correct.
