### ISSUE TITLE
should not show table header if no results found

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#69]
### Reported URL ###
*https://connect.topcoder-dev.com/projects?keyword=%2A%2A%2A%2A&sort=best%20match*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pat_monahan/topcoder123!
2. enter "****" to search

### Expected Result ###

*should not show table header if no results found.*

### Actual Result ###

*See screenshot*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="1439" alt="nor" src="https://user-images.githubusercontent.com/4590317/36345131-4cc6a3b8-1460-11e8-81eb-57187dfa81b9.png">

**Comment by sdgun** [comment]
Not an issue
