### ISSUE TITLE
Copyright year should be updated

### ISSUE THREAD

**Issue by kaygee1** [topcoderinc/connect-test-cycle-1#7]
Open Open https://connect.topcoder-dev.com/
Click on Login and see the copyright info

actual - it is © Topcoder 2017

expected - it should be © Topcoder 2018

![2](https://user-images.githubusercontent.com/5115050/36344050-788c5838-143a-11e8-8068-89477d06bb99.png)

**Comment by sdgun** [comment]
Only functional and UI accepted

**Comment by kaygee1** [comment]
@sdgun 
Yes, but see the Spec - The last bullet point on the spec - it very clearly asks the tester to test if 
Miscellaneous:
Footer links work
Copyright year is current

**Comment by sdgun** [comment]
Accepted

**Comment by vic-georgiev** [comment]
This issue was moved to appirio-tech/connect-app#1756
