### ISSUE TITLE
dashboard logic error while switching tabs

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#70]
### Reported URL ###
*https://connect.topcoder-dev.com/projects?keyword=****&sort=best%20match*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pat_monahan/topcoder123!
2. enter "****" to search
3. then click "Active" tab, observe

### Expected Result ###

*"Active" tab should not show any results, just like "All projects" tab does.*

### Actual Result ###

*See screenshots, in All projects tab, it has no results, but in Active tab it has.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="1438" alt="all" src="https://user-images.githubusercontent.com/4590317/36345174-f22184e0-1460-11e8-8283-85e1d4ad324f.png">


<img width="1312" alt="ac" src="https://user-images.githubusercontent.com/4590317/36345177-f8ff5fbc-1460-11e8-9c1f-0156f640d832.png">

**Comment by sdgun** [comment]
Switching tab will display all the items within that tab
