### ISSUE TITLE
should validate discussion comment properly

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#72]
### Reported URL ###
*https://connect.topcoder-dev.com/projects/800/discussions*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. go to https://connect.topcoder-dev.com/projects/800/discussions
3. select a topic on left side
4. enter "<script>alert('hello');</script>" as comment, click to send, observe

### Expected Result ###

*should validate the input properly.*

### Actual Result ###

*See screenshots, empty comment is saved.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="726" alt="reply" src="https://user-images.githubusercontent.com/4590317/36345244-08864fbc-1462-11e8-8170-72916ab4bd29.png">

**Comment by sdgun** [comment]
Similar to https://github.com/topcoderinc/connect-test-cycle-1/issues/55.  This is already covered
