### ISSUE TITLE
[common] should restrict the length of input

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/connect-test-cycle-1#74]
### Reported URL ###
*https://connect.topcoder-dev.com/projects/800/discussions/2124*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. go to https://connect.topcoder-dev.com/projects/800/discussions
3. create a new discussion named "hey"
4. then reply it with a super long text, say more 10000 chars, save it, observe

### Expected Result ###

*should not show error.*

### Actual Result ###

*See screenshot.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

**Comment by winterflame** [comment]
<img width="1421" alt="err" src="https://user-images.githubusercontent.com/4590317/36345304-c2248af6-1462-11e8-8996-9b74be10923a.png">

**Comment by sdgun** [comment]
I can see a proper validation "Error updating topic" when a user exceeds 10,000 chars.
