### ISSUE TITLE
Filter always show 1

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#75]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc&status=active&type=website%2Cchatbot%2Cvisual_design

### Reproduction Steps ###
1. Login to site using pshah_copilot/topcoder123
2. Click on filter
3. Under Filter Project type :  Website and Chatbot and Design or anything
4. Check number value on Filter button

### Expected Result ###

*Enter the expected result here.*

The number on filter is number of filters selected
### Actual  Result ###

*Enter the expected result here.*
The number on filter is always 1
### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36345339-494a865e-1420-11e8-94e0-1ac992e0c37a.png)

### Issue Information ###

Frequency: Always

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
As per the design, Only one filter available.

**Comment by gargsaurabh86** [comment]
@sdgun  Sorry to comment again.
But then it should say Filter everywhere and not Filters :( like Filters next to search bar, and Filters bar Clear filters
![image](https://user-images.githubusercontent.com/29735376/36427786-044bcb4e-1646-11e8-9ddd-79568a425133.png)

Please consider.
