### ISSUE TITLE
404 error for discussion for copilot user

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#82]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/800/discussions

### Reproduction Steps ###
1. Login to site using pshah_copilot/topcoder123
2. Navigate to URL https://connect.topcoder-dev.com/projects/800/discussions

### Expected Result ###

Discussions page should be loaded

### Actual  Result ###

404 error is shown

### Screenshots ###

![image](https://user-images.githubusercontent.com/29735376/36345732-61f9430e-1428-11e8-99e7-7717cd68450b.png)

### Issue Information ###

Frequency: Always

Device: *device used for testing*

OS: *operating system used on test*

Browser: *browser and version used on test*

**Comment by sdgun** [comment]
Not a Bug, This project is not on the list for the copilot login, Accessing it directly will show this message
