### ISSUE TITLE
No create new discussion option for pat_monahan user

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#83]
### Reported URL ###
https://connect.topcoder-dev.com/projects/800/discussions/2125

### Reproduction Steps ###
1. Login to site using pat_monahan/topcoder123!
2. Navigate to URL https://connect.topcoder-dev.com/projects/800/discussions
3. Try to create a new discussion

### Expected Result ###

+ button should be shown in the right side of Discussions Bar to create a new discussion

### Actual  Result ###

There is no + Button to create a new discussion. Screenshot attached with area highlighted in yellow

### Screenshots ###

![image](https://user-images.githubusercontent.com/29735376/36345834-77244934-142a-11e8-84c0-9d947601971e.png)

### Issue Information ###

Frequency: Always

Device: *device used for testing*

OS: *operating system used on test*

Browser: *browser and version used on test*

**Comment by sdgun** [comment]
I can see the button

**Comment by gargsaurabh86** [comment]
@sdgun yes even I can see button now.  Its because these were shared testing account and now Admin has joined the project.
Please try this: https://connect.topcoder-dev.com/projects/2787/discussions
https://connect.topcoder-dev.com/projects/2686/discussions
Or in https://connect.topcoder-dev.com/projects/800/discussions we first need to remove Admin from project and then test :)
Also, note that he even can't see Discussions in Menu bar and if we edit the URL to force it to go to discussions then you can't create new discussion option.
![image](https://user-images.githubusercontent.com/29735376/36438249-3b98b5e2-1661-11e8-9b8a-b501bdc400a5.png)

Sorry for the inconvenience.

**Comment by sdgun** [comment]
Discussion tab is only available for Old projects. For newly created projects that tab is not visible

**Comment by gargsaurabh86** [comment]
So it's an issue right?
It should always be visible and admin should be able to create new discussion post.
Thanks

**Comment by sdgun** [comment]
Because these projects are new [FEB 20, 2018] (https://connect.topcoder-dev.com/projects/2787) discussion tab is not there by the design. Not a bug

Old project have the 'Discussion' tab (https://connect.topcoder-dev.com/projects/139)

**Comment by gargsaurabh86** [comment]
So **when** does project become old so that Admin can see discussion tab please?
None of the below projects have Discussion tab:
I can see projects like : 
[Feb 17, 2018] https://connect.topcoder-dev.com/projects/2502/discussions - Able to create discussion
[Feb 17, 2018] https://connect.topcoder-dev.com/projects/2503/discussions - **Not** able to create discussion
[Feb 17, 2018] https://connect.topcoder-dev.com/projects/2525/discussions - **Not** able to create discussion
[Feb 18, 2018] https://connect.topcoder-dev.com/projects/2606 - **Not** able to create discussion
[Feb 18, 2018] https://connect.topcoder-dev.com/projects/2629 - **Not** able to create discussion

Please check.

Thank you.

**Comment by gargsaurabh86** [comment]
[Feb 17, 2018] https://connect.topcoder-dev.com/projects/2490/discussions - Unable to create discussion
[Feb 15, 2018] https://connect.topcoder-dev.com/projects/2480/discussions - Unable to create discussion
![image](https://user-images.githubusercontent.com/29735376/36449492-dad93df4-1682-11e8-815c-7b3cd6a63ee5.png)

![image](https://user-images.githubusercontent.com/29735376/36449510-ea6c8672-1682-11e8-91b0-4c5f6d7c0761.png)

Thank you.

**Comment by sdgun** [comment]
If you create a new project now 'You don't have 'Discussion' tab. In the recent development cycle, topcoder has removed the 'Discussion tab' from the page

[Feb 17, 2018] https://connect.topcoder-dev.com/projects/2502/discussions - Able to create discussion
[Feb 17, 2018] https://connect.topcoder-dev.com/projects/2503/discussions - Not able to create discussion
[Feb 17, 2018] https://connect.topcoder-dev.com/projects/2525/discussions - Not able to create discussion

You have manually added the /discussions to the above URLs. Below are the correct URLs

https://connect.topcoder-dev.com/projects/2502/
https://connect.topcoder-dev.com/projects/2503/
https://connect.topcoder-dev.com/projects/2525/

**Comment by sdgun** [comment]
1. Also check the 'Scope' in the contest details page **Discussions tab (Use project id <1000 to test the functionality) - Eg: https://connect.topcoder-dev.com/projects/800/discussions**
2. In your second step (Navigate to URL https://connect.topcoder-dev.com/projects/800/discussions) project id is 800 so you will see the 'Discussion' tab
3. In your first comment all the Project Ids are above 1000 > 2787 and 2686 so you won't see the discussion tab so the provided URLs are changed by adding /discussions at the end which is not done by the typical user
https://connect.topcoder-dev.com/projects/2787/discussions, https://connect.topcoder-dev.com/projects/2686/discussions

**Comment by gargsaurabh86** [comment]
Please try this:

https://connect.topcoder-dev.com/projects/700/discussions
![image](https://user-images.githubusercontent.com/29735376/36450886-32406b9a-1687-11e8-96ad-ead117c54846.png)

Sorry for taking so much of your time on 1 bug but found another :)
And many thanks for clarifying.

**Comment by sdgun** [comment]
This is due to old incomplete data. Not a bug
