### ISSUE TITLE
Customer: REF code is accepting special characters

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#84]
### Reported URL ###
https://connect.topcoder-dev.com/new-project/app?returnUrl=https://connect.topcoder-dev.com/projects/2509/specification

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com/
2. Login as pshah_customer
3. Click on New project icon
4. Now Enter special character in REF code and observe

### Expected Result ###
REF code should not accept the special character.

### Actual  Result ###

There is no validation for REF code. It is accepting special character also.

### Screenshots ###
![image](https://user-images.githubusercontent.com/31851673/36345695-d19a542e-1427-11e8-96b3-35a12ddfaf30.png)

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 64-bit

Browser: Chrome 64.0.3

**Comment by sdgun** [comment]
Not a Bug
