### ISSUE TITLE
Specification not loading 

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#85]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/273

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. Navigate to My Amazing Application project i.e. https://connect.topcoder-dev.com/projects/273
3. Click on Specification

### Expected Result ###

Navigation to specification page

### Actual  Result ###

No navigation occurs
Also, if you hit URL https://connect.topcoder-dev.com/projects/273/specification directly page will keep on loading but nothing is displayed

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36346017-ec0d63c2-142d-11e8-8caa-29d11a0ea3e7.png)
![image](https://user-images.githubusercontent.com/29735376/36346028-0d431b90-142e-11e8-9a66-9f43cf63fdb5.png)

### Issue Information ###

Frequency: Always

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
This is because of old test data. Not a bug. For new Projects this function is working properly

**Comment by gargsaurabh86** [comment]
Please use below project name to test and reproduce the issue when there are spaces in the project name.
Browser : IE11
Window 7
Project name: 
**Just testing the long project name app project**

Thank you

**Comment by gargsaurabh86** [comment]
Please ignore my above comment it was for  #71

**Comment by gargsaurabh86** [comment]
@sdgun  will appreciate if you can clarify what is meant when you say project is new or it's old as I don't see these words in the Specification document.
This will clarify doubt in #85 #86 #83
Thank you.

**Comment by sdgun** [comment]
I can see you are using project I’d 123 which is an old  project created long time ago. So those test data have some issues. For newly created projects I can’t see  this issue.

**Comment by gargsaurabh86** [comment]
@sdgun  please try below ones with old and new ones. Here not only Specification is not clickable but when you force it to navigate via URL it never opens.

[**OCT 09, 2017**] https://connect.topcoder-dev.com/projects/1580/specification
![image](https://user-images.githubusercontent.com/29735376/36476870-0aca835a-16f7-11e8-875a-4cc4f299cd81.png)

![image](https://user-images.githubusercontent.com/29735376/36476837-ee69a29a-16f6-11e8-9774-27920d3dbf3b.png)

[**FEB 20, 2018**] https://connect.topcoder-dev.com/projects/800/specification

![image](https://user-images.githubusercontent.com/29735376/36476736-a1486f64-16f6-11e8-8cec-639badf37cb4.png)
![image](https://user-images.githubusercontent.com/29735376/36476757-afe39e5e-16f6-11e8-9fa4-1da9103bfcb0.png)

[**FEB 20, 2018**] https://connect.topcoder-dev.com/projects/263/specification

![image](https://user-images.githubusercontent.com/29735376/36477017-a136e130-16f7-11e8-8cc9-24854beec123.png)
![image](https://user-images.githubusercontent.com/29735376/36476998-8bfc3428-16f7-11e8-851b-e163811d22c8.png)

Please consider

**Comment by sdgun** [comment]
[OCT 09, 2017] https://connect.topcoder-dev.com/projects/1580/specification > Too old I need 2018 one
[FEB 20, 2018] https://connect.topcoder-dev.com/projects/800/specification > This is updated on 2018, check teh ID 800
[FEB 20, 2018] https://connect.topcoder-dev.com/projects/263/specification > This is updated on 2018, check teh ID 263

If you can reproduce this issue in a new project, then I can accept that as a bug.
