### ISSUE TITLE
Navigation to Discussion failing

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#86]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/273

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. Navigate to My Amazing Application project i.e. https://connect.topcoder-dev.com/projects/273
3. Click on Discussions

### Expected Result ###

Navigation to Discussions page

### Actual  Result ###

No navigation occurs
(Also, if you hit URL https://connect.topcoder-dev.com/projects/273/discussions directly page then load)

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36346096-9cea4d9e-142f-11e8-84ad-98a72f6fa05c.png)

### Issue Information ###

Frequency: Always

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/85
