### ISSUE TITLE
Error adding member to project team

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#87]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/273

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. Navigate to My Amazing Application project i.e. https://connect.topcoder-dev.com/projects/273
3. On left side click + on Project team
4. Select/add a member whcih is not in list
5. Click add
6 Wait on page for bit long

### Expected Result ###

*Enter the expected result here.*
User is added to project team
### Actual  Result ###

Error on page as per screenshot after around 30 second

### Screenshots ###
![image](https://user-images.githubusercontent.com/29735376/36346128-7bc5b30a-1430-11e8-8dbc-6f1fe9fec368.png)

*Paste screenshots here.*

### Issue Information ###

Frequency: Always

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/8
