### ISSUE TITLE
Manager: Error message displayed for 3 times if click on the button again and again

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#88]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2514

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com/
2. Login as pshah_manager
3. Click on any project which is completed
4. Try to change the status to Cancelled
5. Select the Reason for cancellation
6. Click on Cancel project button for 3 times

### Expected Result ###
Error message should display only once.

### Actual  Result ###

Error message displayed for 3 times if click on the Cancel project button again and again immediately.

### Screenshots ###
![image](https://user-images.githubusercontent.com/31851673/36346208-fadf1d92-1431-11e8-8ca3-8b3aa2406b8f.png)

https://youtu.be/94uKoL5sqRw

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 64-bit

Browser: Chrome 64.0.3

**Comment by sdgun** [comment]
Not a Bug
