### ISSUE TITLE
All project filter Issue

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#89]
### Reported URL ###
https://connect.topcoder-dev.com/projects

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. Select Active filter, 3 results are shown
3. Now click My Amazing Application project 
4. Click  view all projects to go back

### Expected Result ###
Active filter button should be selected or if All project filter is selected then all the projects should be shown

### Actual  Result ###
All project filter highlighted but results are shown as Active filter is selected i.e only 3 projects are shown

![image](https://user-images.githubusercontent.com/29735376/36346227-7df411d8-1432-11e8-90ee-4572f4a7b39a.png)
![image](https://user-images.githubusercontent.com/29735376/36346234-96db5382-1432-11e8-9b02-d9b375b43d15.png)
![image](https://user-images.githubusercontent.com/29735376/36346224-664dffc6-1432-11e8-80f3-a8acb6596548.png)
Error: 
![image](https://user-images.githubusercontent.com/29735376/36346189-bd4d0b10-1431-11e8-9726-9a2a6c94a6f5.png)

### Screenshots ###

*Paste screenshots here.*

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/29
