### ISSUE TITLE
Website does not load in IE

### ISSUE THREAD

**Issue by macs054** [topcoderinc/connect-test-cycle-1#9]
### Reported URL ###
https://connect.topcoder-dev.com/

### Reproduction Steps ###
Go to the above link using IE11

### Expected Result ###

Website should load properly

### Actual  Result ###

Page is blank

### Screenshots ###

![image](https://user-images.githubusercontent.com/1199534/36344046-660bd67e-144f-11e8-9d71-7f4cab627cb0.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: IE 11.576.14393.0

**Comment by sdgun** [comment]
Can't reproduce the bug using the provided steps and detail. Website is loading properly in IE11
