### ISSUE TITLE
ToolTip not shown for project Status

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#90]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc&status=active

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. Hover mouse over Project status

### Expected Result ###

Tool tip is shown

### Actual  Result ###

Tooltipo is not shown
### Screenshots ###
![image](https://user-images.githubusercontent.com/29735376/36346268-35a12866-1433-11e8-88ef-6e84bfa2d369.png)

*Paste screenshots here.*

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
Not a Bug

**Comment by gargsaurabh86** [comment]
@sdgun again mentioned in specs: User roles should see affordances


Thank you.

**Comment by sdgun** [comment]
For heading, we don't need. For roles already there

![2018-02-22_3-46-56](https://user-images.githubusercontent.com/4592712/36531325-156a6492-1783-11e8-88d2-1789762d0e1a.jpg)
