### ISSUE TITLE
Manager: Description of the error message is wrong

### ISSUE THREAD

**Issue by bikakk** [topcoderinc/connect-test-cycle-1#91]
### Reported URL ###
https://connect.topcoder-dev.com/projects/2514

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com/
2. Login as pshah_manager
3. Click on any project which is completed
4. Try to change the status to Cancelled
5. Select the Reason for cancellation
6. Click on Cancel project button and observe the error message

### Expected Result ###
Error message should show the meaning like " you can't cancel the project which is completed"

### Actual  Result ###

currently it showing as below:
Please add a name for your project and then try saving again.
which is wrong indication for the user. The project is already have a name .
The message displayed for all other invalid status changes.

### Screenshots ###

![image](https://user-images.githubusercontent.com/31851673/36346263-1f594a34-1433-11e8-8db2-15b06e0f3eae.png)

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 64-bit

Browser: Chrome 64.0.3

**Comment by sdgun** [comment]
Fixing #21 will fix this also
