### ISSUE TITLE
Tooltip issue for project type icon

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#92]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. Hover mouse over Project type icon

### Expected Result ###

One image/icon should be used for 1 tooltip

### Actual  Result ###
Sometimes same icon/image shows different tool tip which means projectype

*Enter the expected result here.*

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36346326-82533996-1434-11e8-885b-a13ae2889c8e.png)
![image](https://user-images.githubusercontent.com/29735376/36346332-8e60d23e-1434-11e8-9ca5-62b450a392be.png)
![image](https://user-images.githubusercontent.com/29735376/36346367-159bb50c-1435-11e8-844c-4e50fbf9df08.png)

### Issue Information ###

Frequency: Always
Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

**Comment by sdgun** [comment]
This is because of old test data. Not a bug. Newly created item will have new icon set
