### ISSUE TITLE
Clicking on specification link throws an error

### ISSUE THREAD

**Issue by arku** [topcoderinc/connect-test-cycle-1#93]
### Reported URL ###
https://connect.topcoder-dev.com/projects/800/specification

### Reproduction Steps ###
1. Go to https://connect.topcoder-dev.com/
2. Click 'Login' button in the top right.
3. Login with the following credentials.
username - pshah_manager
password - topcoder123
4. Go to https://connect.topcoder-dev.com/projects/800
5. Click on 'Specification' link

### Expected Result ###
The specification view should be rendered

### Actual  Result ###

`Uncaught TypeError: Cannot read property '0' of undefined` error is thrown and the `ProjectSpecification ` component is not rendered

### Screenshots ###

![rsz_test 1](https://user-images.githubusercontent.com/7039523/36346362-12f6bf56-140b-11e8-9fa1-bd5b34e03e5a.png)

### Issue Information ###

Frequency: Always

Device: HP 

OS: Ubuntu 16.04 LTS

Browser: Google Chrome | 63.0.3239.132 (Official Build) (64-bit)

**Comment by sdgun** [comment]
Test data issue, For new projects this won't happen
