### ISSUE TITLE
Window-Member – Long Project name should be aligned properly

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#97]
Summary:
Window-Member – Long Project name should be aligned properly  
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2.Log in with pshah_customer/topcoder123
2. Create a project with long name.”BigProjectBigProjectBigProjectBigProjectBigProjectBigProject BigProjectBigProjectBigProject BigProjectBigProjectBigProjectBigProjectBigProjectBigProject BigProjectBigProjectBigProject BigProjectBigProjectBigProjectBigProjectBigProjectBigProject BigProjectBigProjectBigProject”
3. Open a project and check the project header name.
### Expected Result ###
Window-Member – Long Project name should be aligned properly  

### Actual  Result ###
Window-Member – Long Project name is not aligned properly  
### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36346495-be880a46-1465-11e8-869c-31c051e1891a.png)

### Issue Information ###

Frequency: Repeated

Device: Ipad

OS: IOS10

Browser: Safari

**Comment by sdgun** [comment]
#71 and #5
