### ISSUE TITLE
Keyboard tab order issue for chatbot project

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#98]
## Reported URL ###
https://connect.topcoder-dev.com/new-project/chatbot?returnUrl=https://connect.topcoder-dev.com/projects/263

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. Click + to add new project
3. Click chatbot
4. Enter project name as test
5. Enter project description as yusegfuesyfuefaueyusegfuesyfuefaueyusegfuesyfuefaueyusegfuesyfuefaueyusegfuesyfuefaueyusegfuesyfuefaueyusegfuesyfuefaueyusegfuesyfuefaueyusegfuesyfuefauejjjjjjjjjjjj
6. Now use **Keyboard TAB key**

### Expected Result ###

Under What capabilities does the chatbot need to support?-> Order Management should be highlighted

### Actual  Result ###

Keyboard **TAB skips** the order to highlight Order Management and move directly to next text box which is : 
Will the chatbot need to access data from any systems to support the capabilities you listed above? If so, please list the systems below.

### Screenshots ###

*Paste screenshots here.*

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: *browser and version used on test*

**Comment by sdgun** [comment]
Not an issue
